(function(){function h(a){throw a;}var ba=void 0,i=!0,k=null,m=!1;function ca(a){return function(){return a}}var n,da=this;function fa(){}
function o(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){return a!==ba}function q(a){return a!=k}function ga(a){return"array"==o(a)}function r(a){var b=o(a);return"array"==b||"object"==b&&"number"==typeof a.length}function s(a){return"string"==typeof a}function t(a){return"boolean"==typeof a}function ha(a){return"number"==typeof a}function ia(a){return"function"==o(a)}function ja(a){var b=typeof a;return"object"==b&&a!=k||"function"==b}
var ka="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),la=0;function u(a,b){var c=a.split("."),d=da;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function ma(a,b){function c(){}c.prototype=b.prototype;a.Xa=b.prototype;a.prototype=new c;a.prototype.constructor=a};var v=Array.prototype,na=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if(s(a))return!s(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},oa=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=s(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ra=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=s(a)?
a.split(""):a,j=0;j<d;j++)if(j in g){var l=g[j];b.call(c,l,j,a)&&(e[f++]=l)}return e},w=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=s(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function sa(a,b){if(a.reduce)return a.reduce(b,0);var c=0;oa(a,function(d,e){c=b.call(ba,c,d,e,a)});return c}
function ua(a,b){var c;a:{c=a.length;for(var d=s(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(ba,d[e],e,a)){c=e;break a}c=-1}return 0>c?k:s(a)?a.charAt(c):a[c]}function va(a,b){var c=na(a,b);0<=c&&v.splice.call(a,c,1)}function wa(a){return v.concat.apply(v,arguments)}function xa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function ya(a,b,c){return 2>=arguments.length?v.slice.call(a,b):v.slice.call(a,b,c)}
function za(a){for(var b=[],c=0;c<a;c++)b[c]=0;return b}function Da(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var x="StopIteration"in da?da.StopIteration:Error("StopIteration");function y(){}y.prototype.next=function(){h(x)};y.prototype.q=function(){return this};function Ea(a){if(a instanceof y)return a;if("function"==typeof a.q)return a.q(m);if(r(a)){var b=0,c=new y;c.next=function(){for(;;){b>=a.length&&h(x);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}
function z(a,b,c){if(r(a))try{oa(a,b,c)}catch(d){d!==x&&h(d)}else{a=Ea(a);try{for(;;)b.call(c,a.next(),ba,a)}catch(e){e!==x&&h(e)}}}function A(a,b,c){var d=Ea(a),a=new y;a.next=function(){for(;;){var a=d.next();return b.call(c,a,ba,d)}};return a}function Fa(a,b,c){var d=c;z(a,function(a){d=b.call(ba,d,a)});return d}function Ia(a){var b=arguments,c=b.length,d=0,e=new y;e.next=function(){try{return d>=c&&h(x),Ea(b[d]).next()}catch(a){return(a!==x||d>=c)&&h(a),d++,this.next()}};return e}
function Ja(a){if(r(a))return xa(a);var a=Ea(a),b=[];z(a,function(a){b.push(a)});return b};function Ka(){}Ka.fa=function(){return Ka.ha?Ka.ha:Ka.ha=new Ka};Ka.prototype.za=0;Ka.fa();var La={};u("jsnx.utils.is_list_of_ints",function(a){if(!r(a))return m;for(var b=0,c=a.length;b<c;b++)if(window.isNaN(a[b]))return m;return i});u("jsnx.utils.cumulative_sum",function(a){var b=0;return A(a,function(a){return b+=a})});u("jsnx.utils.generate_unique_node",function(){return":"+(Ka.fa().za++).toString(36)});function B(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ma(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function C(a){var b=0,c;for(c in a)b++;return b}function Na(a){for(var b in a)return b}function Oa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function D(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Pa(a){for(var b in a)delete a[b]}function E(a,b){b in a&&delete a[b]}function F(a,b,c){return b in a?a[b]:c}
function G(a){var b={},c;for(c in a)b[c]=a[c];return b}var Qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function H(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Qa.length;f++)c=Qa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function Ra(a){var b=arguments.length;if(1==b&&ga(arguments[0]))return Ra.apply(k,arguments[0]);b%2&&h(Error("Uneven number of arguments"));for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function Sa(a){if("function"==typeof a.K)return a.K();if(s(a))return a.split("");if(r(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Oa(a)};function Ta(a,b){this.i={};this.h=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.$(a)}n=Ta.prototype;n.v=0;n.W=0;n.w=function(){return this.v};n.K=function(){Ua(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.i[this.h[b]]);return a};n.clear=function(){this.i={};this.W=this.v=this.h.length=0};
n.remove=function(a){return Object.prototype.hasOwnProperty.call(this.i,a)?(delete this.i[a],this.v--,this.W++,this.h.length>2*this.v&&Ua(this),i):m};function Ua(a){if(a.v!=a.h.length){for(var b=0,c=0;b<a.h.length;){var d=a.h[b];Object.prototype.hasOwnProperty.call(a.i,d)&&(a.h[c++]=d);b++}a.h.length=c}if(a.v!=a.h.length){for(var e={},c=b=0;b<a.h.length;)d=a.h[b],Object.prototype.hasOwnProperty.call(e,d)||(a.h[c++]=d,e[d]=1),b++;a.h.length=c}}
n.set=function(a,b){Object.prototype.hasOwnProperty.call(this.i,a)||(this.v++,this.h.push(a),this.W++);this.i[a]=b};n.$=function(a){var b;a instanceof Ta?(Ua(a),b=a.h.concat(),a=a.K()):(b=D(a),a=Oa(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};n.X=function(){return new Ta(this)};
n.q=function(a){Ua(this);var b=0,c=this.h,d=this.i,e=this.W,f=this,g=new y;g.next=function(){for(;;){e!=f.W&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(x);var g=c[b++];return a?g:d[g]}};return g};function I(a){this.i=new Ta;a&&this.$(a)}function Va(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ka]||(a[ka]=++la)):b.substr(0,1)+a}n=I.prototype;n.w=function(){return this.i.w()};n.add=function(a){this.i.set(Va(a),a)};n.$=function(a){for(var a=Sa(a),b=a.length,c=0;c<b;c++)this.add(a[c])};n.remove=function(a){return this.i.remove(Va(a))};n.clear=function(){this.i.clear()};n.contains=function(a){a=Va(a);return Object.prototype.hasOwnProperty.call(this.i.i,a)};
function Xa(a,b){for(var c=new I,d=Sa(b),e=0;e<d.length;e++){var f=d[e];a.contains(f)&&c.add(f)}return c}function Ya(a,b){for(var c=a.X(),d=Sa(b),e=d.length,f=0;f<e;f++)c.remove(d[f]);return c}n.K=function(){return this.i.K()};n.X=function(){return new I(this)};n.q=function(){return this.i.q(m)};function Za(a){if(q(a))try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new La.Ga;return a}
function $a(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=ab(a.adj,b,a.l()),"graph"in a&&"object"===o(a.graph)&&(d.graph=G(a.graph)),"node"in a&&"object"===o(a.node)&&(d.node=Ma(a.node,function(a){return G(a)})),d}catch(e){h(Error("Input is not a correct jsnx graph"))}if("object"===o(a))try{return ab(a,b,c)}catch(f){try{return bb(a,b)}catch(g){h(Error("Input is not known type."))}}if(r(a))try{return cb(a,b)}catch(j){h(Error("Input is not valid edge list"))}}u("jsnx.to_networkx_graph",$a);
u("jsnx.convert_to_undirected",La.Ma);u("jsnx.convert_to_undirected",La.La);u("jsnx.to_dict_of_lists",La.Ya);function bb(a,b){var c=Za(b);c.g(a);if(c.l()&&!c.c()){var d={};B(a,function(a,b){oa(a,function(a){a in d||c.j(b,a)});d[b]=1})}else{var e=[];B(a,function(a,b){oa(a,function(a){e.push([b,a])})});c.a(e)}return c}
function ab(a,b,c){var d=Za(b),e,f;d.g(a);c?d.c()?(d.l()?(e=[],B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){B(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){B(a,function(a){e.push([b,c,a])})})})),d.a(e)):d.l()?(f=new I,B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){f.contains([b,c].toString())||(e=[],B(a,function(a,d){e.push([b,c,d,a])}),d.a(e),f.add([c,b].toString()))})})):(f=new I,B(a,function(a,b){r(a)&&h(Error());B(a,function(a,
c){f.contains([b,c].toString())||(e=[],B(a,function(a){e.push([b,c,a])}),d.a(e),f.add([c,b].toString()))})})):d.l()&&!d.c()?(f=new I,B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){f.contains([b,c].toString())||(d.j(b,c,a),f.add([c,b].toString()))})})):(e=[],B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){e.push([b,c,a])})}),d.a(e));return d}function cb(a,b){var c=Za(b);c.a(a);return c};function db(a){this.name="JSNetworkXException";this.message=a}db.prototype=Error();db.prototype.constructor=db;u("jsnx.JSNetworkXException",db);function J(a){db.call(this,a);this.name="JSNetworkXError"}ma(J,db);u("jsnx.JSNetworkXError",J);function eb(a){db.call(this,a);this.name="JSNetworkXPointlessConcept"}ma(eb,db);u("jsnx.JSNetworkXPointlessConcept",eb);function fb(a){db.call(this,a);this.name="JSNetworkXAlgorithmError"}ma(fb,db);u("jsnx.JSNetworkXAlgorithmError",fb);
function gb(a){fb.call(this,a);this.name="JSNetworkXUnfeasible"}ma(gb,fb);u("jsnx.JSNetworkXUnfeasible",gb);function hb(a){gb.call(this,a);this.name="JSNetworkXNoPath"}ma(hb,gb);u("jsnx.JSNetworkXNoPath",hb);function ib(a){fb.call(this,a);this.name="JSNetworkXUnbounded"}ma(ib,fb);u("jsnx.JSNetworkXUnbounded",ib);function jb(a){return Fa(lb(a),function(a,c){a[c[0]]=c[1];return a},{})}function mb(a){return a instanceof y||ia(a.q)}function nb(a){if(s(a)||r(a)||"length"in a)return a.length;if(ob(a))return C(a);h(new TypeError)}function K(a,b,c,d){t(c)&&(d=c,c=k);if(d)var e=b,b=function(a){e.apply(this,a)};mb(a)?z(a,b,c):r(a)||s(a)?oa(a,b,c):ja(a)&&K(D(a),b,c)}u("jsnx.forEach",K);function L(a,b,c){if(r(a))return w(a,b,c);if(mb(a))return A(a,b,c);if(ja(a))return Ma(a,b,c);h(new TypeError)}
function pb(){var a=arguments,b=a[0];if(r(b))return Da.apply(k,a);if(mb(b)){var b=new y,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(ja(b))return Da.apply(k,w(a,D));h(new TypeError)}function qb(a,b){a=ia(b)?L(a,function(){return b.apply(k,arguments)}):M(a);return Math.max.apply(k,a)}
function rb(a,b,c){if(0===arguments.length)return[];1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new y,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(x);g=f;f=f+c;return g};return d}
function sb(a){var b=M(a),c=b.length;if(2>c)return new y;var d=M(rb(2)),a=new y;a.next=function(){var a=w(d,function(a){return b[a]});this.next=function(){var a=m,e;for(e=2;e--;)if(d[e]!=e+c-2){a=i;break}a||h(x);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return w(d,function(a){return b[a]})};return a};return a}
function tb(a){var b=M(a),c=b.length,d=ha(2)?2:c;if(d>c)return new y;var e=M(rb(c)),f=M(rb(c,c-d,-1)),a=new y,g=new y,j,l=i;a.next=function(){this.next=j.next;return w(e.slice(0,d),function(a){return b[a]})};g.next=function(){return l};j=N(g,function(a){a||h(x);l=m;return rb(d-1,-1,-1)},function(a){if(!l)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var g=f[a],j=e[a];e[a]=e[e.length-g];e[e.length-g]=j;l=i;return lb([w(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function ub(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!p(a[c])||"object"!==o(a[c])?a[c]=P(d[c]):"object"===o(a[c])&&"object"===o(d)&&ub(a[c],d[c]);for(var f=0;f<Qa.length;f++)c=Qa[f],Object.prototype.hasOwnProperty.call(d,c)&&(!p(a[c])||"object"!==o(a[c])?a[c]=P(d[c]):"object"===o(a[c])&&"object"===o(d)&&ub(a[c],d[c]))}}function M(a){if(r(a))return xa(a);if(mb(a))return Ja(a);if(ja(a))return D(a);h(new TypeError)}u("jsnx.toArray",M);
function vb(a){var b=[];B(a,function(a,d){b.push([d,a])});return b}function R(a){var b=new y,c=Ea(D(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function lb(a){"object"===o(a)&&(!r(a)&&!mb(a))&&(a=D(a));return Ea(a)}
function N(a){var b=new y,c=ya(arguments,1);if(0===c.length)return a;try{a=Ea(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&h(new TypeError)},b}var e=k;b.next=function(){var d,g;try{for(;!p(d);)d=e.next()}catch(j){for(;!p(g)||!p(d);)g=a.next(),d=c[0](g);if(mb(d))return e=N.apply(k,wa([d],ya(c,1))),b.next();e=k}return d};return b}u("jsnx.sentinelIterator",function(a,b){var c=new y;c.next=function(){var c;try{c=Ea(a).next()}catch(e){e!=x&&h(e),c=b}return c};return c});
function ob(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==o(a)||a.nodeType||a==a.window)return m;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return m}catch(c){return m}for(var d in a);return d===ba||b.call(a,d)}
function P(a,b){var b=b||[],c=o(a);if("object"==c&&ob(a)||"array"==c){var d=ua(b,function(b){return a===b[0]});if(d!==k)return d[1];if(a.X)return d=[a,a.X()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var e in a)c[e]=P(a[e],b);return c}return a}function wb(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=P(c);a=new b;for(d in c)a[d]=c[d];return a};function xb(a){var b=[];yb(new zb,a,b);return b.join("")}function zb(){this.Z=ba}
function yb(a,b,c){switch(typeof b){case "string":Ab(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==k){c.push("null");break}if(ga(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],yb(a,a.Z?a.Z.call(b,""+f,e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Ab(f,c),c.push(":"),
yb(a,a.Z?a.Z.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var Bb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Cb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Ab(a,b){b.push('"',a.replace(Cb,function(a){if(a in Bb)return Bb[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Bb[a]=e+b.toString(16)}),'"')};var S={Ua:function(a){return Math.floor(Math.random()*a)},$a:function(a,b){return a+Math.random()*(b-a)},Ka:function(a,b,c){return Math.min(Math.max(a,b),c)},ya:function(a,b){var c=a%b;return 0>c*b?c+b:c},Ra:function(a,b,c){return a+c*(b-a)},Ta:function(a,b,c){return Math.abs(a-b)<=(c||1.0E-6)},da:function(a){return S.ya(a,360)},la:function(a){return a*Math.PI/180},Fa:function(a){return 180*a/Math.PI},Ia:function(a,b){return b*Math.cos(S.la(a))},Ja:function(a,b){return b*Math.sin(S.la(a))},ea:function(a,
b,c,d){return S.da(S.Fa(Math.atan2(d-b,c-a)))},Ha:function(a,b){var c=S.da(b)-S.da(a);180<c?c-=360:-180>=c&&(c=360+c);return c},Va:function(a){return 0==a?0:0>a?-1:1},Sa:function(a,b,c,d){for(var c=c||function(a,b){return a==b},d=d||function(b){return a[b]},e=a.length,f=b.length,g=[],j=0;j<e+1;j++)g[j]=[],g[j][0]=0;for(var l=0;l<f+1;l++)g[0][l]=0;for(j=1;j<=e;j++)for(l=1;l<=e;l++)g[j][l]=c(a[j-1],b[l-1])?g[j-1][l-1]+1:Math.max(g[j-1][l],g[j][l-1]);for(var O=[],j=e,l=f;0<j&&0<l;)c(a[j-1],b[l-1])?(O.unshift(d(j-
1,l-1)),j--,l--):g[j-1][l]>g[j][l-1]?j--:l--;return O},B:function(a){return sa(arguments,function(a,c){return a+c})},sa:function(a){return S.B.apply(k,arguments)/arguments.length},Wa:function(a){var b=arguments.length;if(2>b)return 0;var c=S.sa.apply(k,arguments),b=S.B.apply(k,w(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},Qa:function(a){return isFinite(a)&&0==a%1},Pa:function(a){return isFinite(a)&&!isNaN(a)}};function U(a,b){if(!(this instanceof U))return new U(a,b);this.graph={};this.node={};this.adj={};q(a)&&$a(a,this);H(this.graph,b||{});this.edge=this.adj}u("jsnx.classes.Graph",U);u("jsnx.Graph",U);U.__name__="Graph";U.prototype.va=k;U.prototype.graph=U.prototype.va;U.prototype.ba=k;U.prototype.node=U.prototype.ba;U.prototype.qa=k;U.prototype.adj=U.prototype.qa;U.prototype.ta=k;U.prototype.edge=U.prototype.ta;
U.prototype.name=function(a){if(p(a))this.graph.name=a.toString();else return this.graph.name||""};U.prototype.name=U.prototype.name;U.prototype.toString=function(){return this.name()};U.prototype.toString=U.prototype.toString;U.prototype.q=function(){return lb(this.adj)};U.prototype.__iterator__=U.prototype.q;U.prototype.m=function(a){a in this.adj||h({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};U.prototype.get_node=U.prototype.m;
U.prototype.D=function(a,b){q(b)||(b={});"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));a in this.adj?H(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};U.prototype.add_node=U.prototype.D;U.prototype.g=function(a,b){var c,d,e,f,g,b=b||{};K(a,function(a){c=!(a in this.adj);ga(a)?(d=a[0],e=a[1],d in this.adj?(g=this.node[d],H(g,b,e)):(this.adj[d]={},f=G(b),H(f,e),this.node[d]=f)):c?(this.adj[a]={},this.node[a]=G(b)):H(this.node[a],b)},this)};
U.prototype.add_nodes_from=U.prototype.g;U.prototype.J=function(a){var b=this.adj,c;a in this.node||h(new J("The node "+a+" is not in the graph"));c=D(b[a]);E(this.node,a);oa(c,function(c){E(b[c],a)});E(b,a)};U.prototype.remove_node=U.prototype.J;U.prototype.T=function(a){var b=this.adj;K(a,function(a){try{E(this.node,a),B(b[a],function(d,f){E(b[f],a)}),E(b,a)}catch(d){}},this)};U.prototype.remove_nodes_from=U.prototype.T;U.prototype.H=function(a){return a?R(this.node):lb(D(this.adj))};
U.prototype.nodes_iter=U.prototype.H;U.prototype.nodes=function(a){return Ja(this.H(a))};U.prototype.nodes=U.prototype.nodes;U.prototype.R=function(){return C(this.adj)};U.prototype.number_of_nodes=U.prototype.R;U.prototype.Ca=function(){return C(this.adj)};U.prototype.order=U.prototype.Ca;U.prototype.k=function(a){return!ga(a)&&a in this.adj};U.prototype.has_node=U.prototype.k;
U.prototype.j=function(a,b,c){c=c||{};"object"!==o(c)&&h(new J("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=F(this.adj[a],b,{});H(d,c);this.adj[a][b]=d;this.adj[b][a]=d};U.prototype.add_edge=U.prototype.j;
U.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));K(a,function(a){var d=nb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new J("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});f in this.adj||(this.adj[f]={},this.node[f]={});a=F(this.adj[e],f,{});H(a,b,g);this.adj[e][f]=a;this.adj[f][e]=a},this)};U.prototype.add_edges_from=U.prototype.a;
U.prototype.pa=function(a,b,c){c=c||{};s(b)||(c=b,b="weight");this.a(L(a,function(a){var c={};c[b]=a[2];p(c[b])||h(new TypeError("Values must consist of three elements: "+xb(a)));return[a[0],a[1],c]}),c)};U.prototype.add_weighted_edges_from=U.prototype.pa;U.prototype.p=function(a,b){try{E(this.adj[a],b),a!=b&&E(this.adj[b],a)}catch(c){c instanceof TypeError&&h(new J("The edge "+a+"-"+b+" is not in the graph")),h(c)}};U.prototype.remove_edge=U.prototype.p;
U.prototype.t=function(a){K(a,function(a){var c=a[0],a=a[1];c in this.adj&&a in this.adj[c]&&(E(this.adj[c],a),c!=a&&E(this.adj[a],c))},this)};U.prototype.remove_edges_from=U.prototype.t;U.prototype.z=function(a,b){return a in this.adj&&b in this.adj[a]};U.prototype.has_edge=U.prototype.z;U.prototype.Q=function(a){a in this.adj||h(new J("The node "+a+" is not in the graph."));return M(this.adj[a])};U.prototype.neighbors=U.prototype.Q;
U.prototype.aa=function(a){a in this.adj||h(new J("The node "+a+" is not in the graph."));return lb(this.adj[a])};U.prototype.neighbors_iter=U.prototype.aa;U.prototype.o=function(a,b){return M(this.d(a,b))};U.prototype.edges=U.prototype.o;
U.prototype.d=function(a,b){t(a)&&(b=a,a=k);var c={},d,e;d=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):R(this.adj);return b?N(d,function(a){e=a[0];var b=new y,d=R(a[1]);b.next=function(){try{return d.next()}catch(a){a===x&&(c[e]=1);h(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):N(d,function(a){e=a[0];var b=new y,d=lb(a[1]);b.next=function(){try{return d.next()}catch(a){a===x&&(c[e]=1);h(a)}};return b},function(a){if(!(a in c))return[e,a]})};
U.prototype.edges_iter=U.prototype.d;U.prototype.L=function(a,b,c){p(c)||(c=k);return a in this.adj?F(this.adj[a],b,c):c};U.prototype.get_edge_data=U.prototype.L;U.prototype.ra=function(){return M(L(this.s(),function(a){return D(a[1])}))};U.prototype.adjacency_list=U.prototype.ra;U.prototype.s=function(){return R(this.adj)};U.prototype.adjacency_iter=U.prototype.s;U.prototype.F=function(a,b){return this.k(a)?this.n(a,b).next()[1]:jb(Ja(this.n(a,b)))};U.prototype.degree=U.prototype.F;
U.prototype.n=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):R(this.adj);return b?L(c,function(a){var c=a[0],a=a[1],f=0,g;for(g in a)f+=+F(a[g],b,1);f+=+(c in a&&F(a[c],b,1));return[c,f]}):L(c,function(a){return[a[0],C(a[1])+ +(a[0]in a[1])]})};U.prototype.degree_iter=U.prototype.n;U.prototype.clear=function(){this.name("");Pa(this.adj);Pa(this.node);Pa(this.graph)};U.prototype.clear=U.prototype.clear;U.prototype.copy=function(){return wb(this)};U.prototype.copy=U.prototype.copy;
U.prototype.l=ca(m);U.prototype.is_multigraph=U.prototype.l;U.prototype.c=ca(m);U.prototype.is_directed=U.prototype.c;U.prototype.C=function(){var a=new V;a.name(this.name());a.g(this);a.a(function(){var a;return N(this.s(),function(c){a=c[0];return R(c[1])},function(c){return[a,c[0],P(c[1])]})}.call(this));a.graph=P(this.graph);a.node=P(this.node);return a};U.prototype.to_directed=U.prototype.C;U.prototype.V=function(){return wb(this)};U.prototype.to_undirected=U.prototype.V;
U.prototype.u=function(a){var a=this.b(a),b=new this.constructor,c=b.adj,d=this.adj;K(a,function(a){var b={};c[a]=b;B(d[a],function(d,j){j in c&&(b[j]=d,c[j][a]=d)})});K(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};U.prototype.subgraph=U.prototype.u;U.prototype.Aa=function(){return w(ra(vb(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};U.prototype.nodes_with_selfloops=U.prototype.Aa;
U.prototype.U=function(a){return a?w(ra(vb(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):w(ra(vb(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};U.prototype.selfloop_edges=U.prototype.U;U.prototype.Ba=function(){return this.U().length};U.prototype.number_of_selfloops=U.prototype.Ba;U.prototype.size=function(a){var b=S.B.apply(k,Oa(this.F(k,a)))/2;return q(a)?b:Math.floor(b)};U.prototype.size=U.prototype.size;
U.prototype.I=function(a,b){return!q(a)?Math.floor(this.size()):b in this.adj[a]?1:0};U.prototype.number_of_edges=U.prototype.I;U.prototype.oa=function(a,b){var c=M(a),d=c[0];this.a(L(ya(c,1),function(a){return[d,a]}),b)};U.prototype.add_star=U.prototype.oa;U.prototype.na=function(a,b){var c=M(a);this.a(Da(ya(c,0,c.length-1),ya(c,1)),b)};U.prototype.add_path=U.prototype.na;U.prototype.ma=function(a,b){var c=M(a);this.a(Da(c,wa(ya(c,1),[c[0]])),b)};U.prototype.add_cycle=U.prototype.ma;
U.prototype.b=function(a){return q(a)?this.k(a)?lb([a.toString()]):function(a,c){var d=new y,e=N(a,function(a){if(a in c)return a.toString()});d.next=function(){try{return e.next()}catch(a){a instanceof TypeError&&h(new J("nbunch is not a node or a sequence of nodes")),h(a)}};return d}(a,this.adj):lb(this.adj)};U.prototype.nbunch_iter=U.prototype.b;function V(a,b){if(!(this instanceof V))return new V(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;q(a)&&$a(a,this);H(this.graph,b||{});this.edge=this.adj}u("jsnx.classes.DiGraph",V);u("jsnx.DiGraph",V);ma(V,U);V.__name__="DiGraph";V.prototype.D=function(a,b){q(b)||(b={});"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));a in this.succ?H(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};V.prototype.add_node=V.prototype.D;
V.prototype.g=function(a,b){var c,d,e,f,g,b=b||{};K(lb(a),function(a){c=!(a in this.succ);ga(a)?(d=a[0],e=a[1],d in this.succ?(g=this.node[d],H(g,b,e)):(this.succ[d]={},this.pred[d]={},f=G(b),H(f,e),this.node[d]=f)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=G(b)):H(this.node[a],b)},this)};V.prototype.add_nodes_from=V.prototype.g;
V.prototype.J=function(a){a in this.node||h(new J("The node "+a+" is not in the graph"));var b=this.succ[a];E(this.node,a);B(b,function(b,d){E(this.pred[d],a)},this);E(this.succ,a);B(this.pred[a],function(b,d){E(this.succ[d],a)},this);E(this.pred,a)};V.prototype.remove_node=V.prototype.J;
V.prototype.T=function(a){var b;K(a,function(a){a in this.succ&&(b=this.succ[a],E(this.node,a),B(b,function(b,e){E(this.pred[e],a)},this),E(this.succ,a),B(this.pred[a],function(b,e){E(this.succ[e],a)},this),E(this.pred,a))},this)};V.prototype.remove_nodes_from=V.prototype.T;
V.prototype.j=function(a,b,c){c=c||{};"object"!==o(c)&&h(new J("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=F(this.adj[a],b,{});H(d,c);this.succ[a][b]=d;this.pred[b][a]=d};V.prototype.add_edge=V.prototype.j;
V.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));K(a,function(a){var d=nb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new J("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});f in this.succ||(this.succ[f]={},this.pred[f]={},this.node[f]={});a=F(this.adj[e],f,{});H(a,b,g);this.succ[e][f]=a;this.pred[f][e]=a},this)};
V.prototype.add_edges_from=V.prototype.a;V.prototype.p=function(a,b){try{E(this.succ[a],b),E(this.pred[b],a)}catch(c){c instanceof TypeError&&h(new J("The edge "+a+"-"+b+" is not in the graph")),h(c)}};V.prototype.remove_edge=V.prototype.p;V.prototype.t=function(a){K(a,function(a){var c=a[0],a=a[1];c in this.succ&&a in this.succ[c]&&(E(this.succ[c],a),E(this.pred[a],c))},this)};V.prototype.remove_edges_from=V.prototype.t;V.prototype.xa=function(a,b){return a in this.succ&&b in this.succ[a]};
V.prototype.has_successor=V.prototype.xa;V.prototype.wa=function(a,b){return a in this.pred&&b in this.pred[a]};V.prototype.has_predecessor=V.prototype.wa;V.prototype.ka=function(a){a in this.succ||h(new J("The node "+a+" is not in the digraph."));return lb(this.succ[a])};V.prototype.successors_iter=V.prototype.ka;V.prototype.Ea=function(a){a in this.pred||h(new J("The node "+a+" is not in the digraph."));return lb(this.pred[a])};V.prototype.predecessors_iter=V.prototype.Ea;
V.prototype.ja=function(a){a in this.succ||h(new J("The node "+a+" is not in the digraph."));return M(this.succ[a])};V.prototype.successors=V.prototype.ja;V.prototype.Da=function(a){a in this.succ||h(new J("The node "+a+" is not in the digraph."));return M(this.pred[a])};V.prototype.predecessors=V.prototype.Da;V.prototype.Q=V.prototype.ja;V.prototype.neighbors=V.prototype.Q;V.prototype.aa=V.prototype.ka;V.prototype.neighbors_iter=V.prototype.aa;
V.prototype.d=function(a,b){t(a)&&(b=a,a=k);var c,d,e;c=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):vb(this.adj);return b?N(c,function(a){d=a[0];e=a[1];return R(e)},function(a){return[d,a[0],a[1]]}):N(c,function(a){d=a[0];e=a[1];return R(e)},function(a){return[d,a[0]]})};V.prototype.edges_iter=V.prototype.d;V.prototype.Y=V.prototype.d;V.prototype.out_edges_iter=V.prototype.Y;V.prototype.ca=U.prototype.o;V.prototype.out_edges=V.prototype.ca;
V.prototype.A=function(a,b){t(a)&&(b=a,a=k);var c,d;c=q(a)?L(this.b(a),function(a){return[a,this.pred[a]]},this):vb(this.pred);return b?N(c,function(a){d=a[0];return R(a[1])},function(a){return[a[0],d,a[1]]}):N(c,function(a){d=a[0];return R(a[1])},function(a){return[a[0],d]})};V.prototype.in_edges_iter=V.prototype.A;V.prototype.N=function(a,b){return M(this.A(a,b))};V.prototype.in_edges=V.prototype.N;
V.prototype.n=function(a,b){var c;c=q(a)?pb(L(this.b(a),function(a){return[a,this.succ[a]]},this),L(this.b(a),function(a){return[a,this.pred[a]]},this)):pb(R(this.succ),R(this.pred));return b?L(c,function(a){var c=a[0][1],f=a[1][1],g=0,j;for(j in c)g+=+F(c[j],b,1);for(j in f)g+=+F(f[j],b,1);return[a[0][0],g]}):L(c,function(a){return[a[0][0],nb(a[0][1])+nb(a[1][1])]})};V.prototype.degree_iter=V.prototype.n;
V.prototype.M=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.pred[a]]},this):R(this.pred);return b?L(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+F(f[g],b,1);return[a[0],c]}):L(c,function(a){return[a[0],C(a[1])]})};V.prototype.in_degree_iter=V.prototype.M;V.prototype.S=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.succ[a]]},this):R(this.succ);return b?L(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+F(f[g],b,1);return[a[0],c]}):L(c,function(a){return[a[0],C(a[1])]})};
V.prototype.out_degree_iter=V.prototype.S;V.prototype.ga=function(a,b){return this.k(a)?this.M(a,b).next()[1]:jb(this.M(a,b))};V.prototype.in_degree=V.prototype.ga;V.prototype.ia=function(a,b){return this.k(a)?this.S(a,b).next()[1]:jb(this.S(a,b))};V.prototype.out_degree=V.prototype.ia;V.prototype.clear=function(){Pa(this.succ);Pa(this.pred);Pa(this.node);Pa(this.graph)};V.prototype.clear=V.prototype.clear;V.prototype.l=ca(m);V.prototype.is_multigraph=V.prototype.l;V.prototype.c=ca(i);
V.prototype.is_directed=V.prototype.c;V.prototype.C=function(){return wb(this)};V.prototype.to_directed=V.prototype.C;V.prototype.V=function(a){var b=new U;b.name(this.name());b.g(this);var c=this.pred,d;a?b.a(N(this.s(),function(a){d=a[0];return R(a[1])},function(a){if(a[0]in c[d])return[d,a[0],P(a[1])]})):b.a(N(this.s(),function(a){d=a[0];return R(a[1])},function(a){return[d,a[0],P(a[1])]}));b.graph=P(this.graph);b.node=P(this.node);return b};V.prototype.to_undirected=V.prototype.V;
V.prototype.reverse=function(a){(a=!p(a)||a)?(a=new this.constructor(k,{name:"Reverse of ("+this.name()+")"}),a.g(this),a.a(L(this.d(i),function(a){return[a[1],a[0],P(a[2])]})),a.graph=P(this.graph),a.node=P(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};V.prototype.reverse=V.prototype.reverse;
V.prototype.u=function(a){var a=this.b(a),b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;K(a,function(a){c[a]={};d[a]={}});K(c,function(a){var b=c[a];B(e[a],function(e,l){l in c&&(b[l]=e,d[l][a]=e)})});K(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};V.prototype.subgraph=V.prototype.u;function W(a,b){if(!(this instanceof W))return new W(a,b);U.call(this,a,b)}ma(W,U);u("jsnx.classes.MultiGraph",W);u("jsnx.MultiGraph",W);W.__name__="MultiGraph";
W.prototype.j=function(a,b,c,d){var e,f;q(c)&&(!s(c)&&!ha(c))&&(d=c,c=k);d=d||{};"object"!==o(d)&&h(new J("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});if(b in this.adj[a]){f=this.adj[a][b];if(!q(c))for(c=C(f);c in f;)c+=1;e=F(f,c,{});H(e,d);f[c]=e}else q(c)||(c=0),e={},H(e,d),f=Ra(c,e),this.adj[a][b]=f,this.adj[b][a]=f};W.prototype.add_edge=W.prototype.j;
W.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));K(a,function(a){var d=nb(a),e,f,g=k,j={};4===d?(e=a[0],f=a[1],g=a[2],j=a[3]):3===d?(e=a[0],f=a[1],j=a[2]):2===d?(e=a[0],f=a[1]):h(new J("Edge tuple "+xb(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=e in this.adj?F(this.adj[e],f,{}):{};if(!q(g))for(g=C(a);g in a;)g+=1;a=F(a,g,{});H(a,b,j);this.j(e,f,g,a)},this)};W.prototype.add_edges_from=W.prototype.a;
W.prototype.p=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new J("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];q(c)?(c in d||h(new J("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),E(d,c)):E(d,Na(d));0===C(d)&&(E(this.adj[a],b),a!=b&&E(this.adj[b],a))};W.prototype.remove_edge=W.prototype.p;W.prototype.t=function(a){K(a,function(a){try{this.p(a[0],a[1],a[2])}catch(c){c instanceof J||h(c)}},this)};W.prototype.remove_edges_from=W.prototype.t;
W.prototype.z=function(a,b,c){return q(c)?a in this.adj&&b in this.adj[a]&&c in this.adj[a][b]:a in this.adj&&b in this.adj[a]};W.prototype.has_edge=W.prototype.z;W.prototype.o=function(a,b,c){return Ja(this.d(a,b,c))};W.prototype.edges=W.prototype.o;
W.prototype.d=function(a,b,c){t(a)&&(t(b)&&(c=b),b=a,a=k);var d={},e,f,a=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):R(this.adj);return b?N(a,function(a){e=a[0];var b=new y,c=R(a[1]);b.next=function(){try{return c.next()}catch(a){a===x&&(d[e]=1);h(a)}};return b},function(a){f=a[0];if(!(f in d))return R(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):N(a,function(a){e=a[0];var b=new y,c=R(a[1]);b.next=function(){try{return c.next()}catch(a){a===x&&(d[e]=1);h(a)}};return b},function(a){f=
a[0];if(!(f in d))return R(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};W.prototype.edges_iter=W.prototype.d;W.prototype.L=function(a,b,c,d){p(d)||(d=k);return a in this.adj&&b in this.adj[a]?q(c)?F(this.adj[a][b],c,d):this.adj[a][b]:d};W.prototype.get_edge_data=W.prototype.L;
W.prototype.n=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):R(this.adj);return q(b)?A(c,function(a){var c=a[0],a=a[1],f=0;B(a,function(a){B(a,function(a){f+=F(a,b,1)})});c in a&&B(a[c],function(a){f+=F(a,b,1)});return[c,f]}):A(c,function(a){var b=a[0],a=a[1],c=0;B(a,function(a){c+=C(a)});return[b,c+ +(b in a&&C(a[b]))]})};W.prototype.degree_iter=W.prototype.n;W.prototype.l=ca(i);W.prototype.is_multigraph=W.prototype.l;W.prototype.c=ca(m);W.prototype.is_directed=W.prototype.c;
W.prototype.C=function(){var a=new Y;a.g(this);a.a(function(){var a,c;return N(this.s(),function(c){a=c[0];return R(c[1])},function(a){c=a[0];return R(a[1])},function(d){return[a,c,d[0],P(d[1])]})}.call(this));a.graph=P(this.graph);a.node=P(this.node);return a};W.prototype.to_directed=W.prototype.C;
W.prototype.U=function(a,b){var c=[];a?b?B(this.adj,function(a,b){b in a&&B(a[b],function(a,d){c.push([b,b,d,a])})}):B(this.adj,function(a,b){b in a&&B(a[b],function(a){c.push([b,b,a])})}):b?B(this.adj,function(a,b){b in a&&B(a[b],function(a,d){c.push([b,b,d])})}):B(this.adj,function(a,b){b in a&&B(a[b],function(){c.push([b,b])})});return c};W.prototype.selfloop_edges=W.prototype.U;W.prototype.I=function(a,b){return!q(a)?this.size():a in this.adj&&b in this.adj[a]?C(this.adj[a][b]):0};
W.prototype.number_of_edges=W.prototype.I;W.prototype.u=function(a){var a=this.b(a),b=new this.constructor,c=b.adj,d=this.adj;z(a,function(a){var b={};c[a]=b;B(d[a],function(d,j){if(j in c){var l=G(d);b[j]=l;c[j][a]=l}})});B(this.node,function(a,c){b.node[c]=a});b.graph=this.graph;return b};W.prototype.subgraph=W.prototype.u;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);V.call(this,a,b)}ma(Y,V);var Db=Y.prototype,Eb=W.prototype,Fb;for(Fb in Eb)Eb.hasOwnProperty(Fb)&&"constructor"!==Fb&&(Db[Fb]=Eb[Fb]);u("jsnx.classes.MultiDiGraph",Y);u("jsnx.MultiDiGraph",Y);Y.__name__="MultiDiGraph";
Y.prototype.j=function(a,b,c,d){var e,f;q(c)&&(!s(c)&&!ha(c))&&(d=c,c=k);d=d||{};"object"!==o(d)&&h(new J("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});if(b in this.succ[a]){f=this.adj[a][b];if(!q(c))for(c=C(f);c in f;)c+=1;e=F(f,c,{});H(e,d);f[c]=e}else q(c)||(c=0),e={},H(e,d),f=Ra(c,e),this.succ[a][b]=f,this.pred[b][a]=f};Y.prototype.add_edge=Y.prototype.j;
Y.prototype.p=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new J("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];q(c)?(c in d||h(new J("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),E(d,c)):E(d,Na(d));0===C(d)&&(E(this.succ[a],b),E(this.pred[b],a))};Y.prototype.remove_edge=Y.prototype.p;
Y.prototype.d=function(a,b,c){t(a)&&(t(b)&&(c=b),b=a,a=k);var d,e,a=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):vb(this.adj);return b?N(a,function(a){d=a[0];return R(a[1])},function(a){e=a[0];return R(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):N(a,function(a){d=a[0];return R(a[1])},function(a){e=a[0];return R(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};Y.prototype.edges_iter=Y.prototype.d;Y.prototype.Y=Y.prototype.d;Y.prototype.out_edges_iter=Y.prototype.Y;
Y.prototype.ca=function(a,b,c){return Ja(this.Y(a,b,c))};Y.prototype.out_edges=Y.prototype.ca;Y.prototype.A=function(a,b,c){t(a)&&(b=a,a=k);var d,e,a=q?L(this.b(a),function(a){return[a,this.pred[a]]},this):vb(this.pred);return b?N(a,function(a){d=a[0];return R(a[1])},function(a){e=a[0];return R(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):N(a,function(a){d=a[0];return R(a[1])},function(a){e=a[0];return R(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};Y.prototype.in_edges_iter=Y.prototype.A;
Y.prototype.N=function(a,b,c){return Ja(this.A(a,b,c))};Y.prototype.in_edges=Y.prototype.N;
Y.prototype.n=function(a,b){var c;c=q(a)?pb(A(this.b(a),function(a){return[a,this.succ[a]]},this),A(this.b(a),function(a){return[a,this.pred[a]]},this)):pb(R(this.succ),R(this.pred));return q(b)?L(c,function(a){var c=a[0][1],f=0;B(a[1][1],function(a){B(a,function(a){f+=+F(a,b,1)})});B(c,function(a){B(a,function(a){f+=+F(a,b,1)})});return[a[0][0],f]}):L(c,function(a){var b=0,c=0;B(a[1][1],function(a){b+=nb(a)});B(a[0][1],function(a){c+=nb(a)});return[a[0][0],b+c]})};Y.prototype.degree_iter=Y.prototype.n;
Y.prototype.M=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.pred[a]]},this):R(this.pred);return q(b)?L(c,function(a){var c=0;B(a[1],function(a){B(a,function(a){c+=+F(a,b,1)})});return[a[0][0],c]}):L(c,function(a){var b=0;B(a[1],function(a){b+=C(a)});return[a[0],b]})};Y.prototype.in_degree_iter=Y.prototype.M;
Y.prototype.S=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.succ[a]]},this):R(this.succ);return q(b)?L(c,function(a){var c=0;B(a[1],function(a){B(a,function(a){c+=+F(a,b,1)})});return[a[0][0],c]}):L(c,function(a){var b=0;B(a[1],function(a){b+=C(a)});return[a[0],b]})};Y.prototype.out_degree_iter=Y.prototype.S;Y.prototype.l=ca(i);Y.prototype.is_multigraph=Y.prototype.l;Y.prototype.c=ca(i);Y.prototype.is_directed=Y.prototype.c;Y.prototype.C=function(){return wb(this)};
Y.prototype.to_directed=Y.prototype.C;Y.prototype.V=function(a){var b=new W;b.name(this.name());b.g(this);var c=this,d,e;a?b.a(N(this.s(),function(a){d=a[0];return R(a[1])},function(a){e=a[0];return R(a[1])},function(a){if(c.z(e,d,a[0]))return[d,e,a[0],P(a[1])]})):b.a(N(this.s(),function(a){d=a[0];return R(a[1])},function(a){e=a[0];return R(a[1])},function(a){return[d,e,a[0],P(a[1])]}));b.graph=P(this.graph);b.node=P(this.node);return b};Y.prototype.to_undirected=Y.prototype.V;
Y.prototype.u=function(a){var a=this.b(a),b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;z(a,function(a){c[a]={};d[a]={}});K(c,function(a){var b=c[a];B(e[a],function(e,l){if(l in c){var O=G(e);b[l]=O;d[l][a]=O}})});K(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.u;
Y.prototype.reverse=function(a){(a=!p(a)||a)?(a=new this.constructor(k,{name:"Reverse of ("+this.name()+")"}),a.g(this),a.a(A(this.d(i,i),function(a){return[a[1],a[0],a[2],P(a[3])]})),a.graph=P(this.graph),a.node=P(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Y.prototype.reverse=Y.prototype.reverse;u("jsnx.nodes",function(a){return a.nodes()});u("jsnx.nodes_iter",function(a){return a.H()});u("jsnx.edges",function(a,b){return a.o(b)});u("jsnx.edges_iter",function(a,b){return a.d(b)});u("jsnx.degree",function(a,b,c){return a.F(b,c)});u("jsnx.neighbors",function(a,b){return a.Q(b)});u("jsnx.number_of_nodes",function(a){return a.R()});u("jsnx.number_of_edges",function(a){return a.I()});u("jsnx.density",function(a){var b=a.R(),c=a.I();return 0===c?0:a.c()?c/(b*(b-1)):2*c/(b*(b-1))});
u("jsnx.degree_histogram",function(a){var a=Oa(a.F()),b=Math.max.apply(Math,a)+1,c=za(b);oa(a,function(a){c[a]+=1});return c});u("jsnx.is_directed",function(a){return a.c()});u("jsnx.freeze",function(a){function b(){h(new J("Frozen graph can't be modified"))}a.D=b;a.g=b;a.J=b;a.T=b;a.j=b;a.a=b;a.p=b;a.t=b;a.clear=b;a.ua=i;return a});u("jsnx.is_frozen",function(a){return!!a.ua});u("jsnx.subgraph",function(a,b){return a.u(b)});
u("jsnx.create_empty_copy",function(a,b){p(b)||(b=i);var c=new a.constructor;b&&c.g(a);return c});
u("jsnx.info",function(a,b){var c="";if(q(b))a.k(b)||h(new J("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.F(b)+"\n"),c+="Neighbors: "+a.Q(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.R()+"\n"),c=c+("Number of edges: "+a.I()+"\n"),d=a.R();if(0<d)if(a.c())c+="Average in degree: "+(S.B.apply(k,Oa(a.ga()))/d).toFixed(4)+"\n",c+="Average out degree: "+(S.B.apply(k,Oa(a.ia()))/d).toFixed(4);
else var e=S.B.apply(k,Oa(a.F())),c=c+("Average degree: "+(e/d).toFixed(4))}return c});u("jsnx.set_node_attributes",function(a,b,c){B(c,function(c,e){a.ba[e][b]=c})});function Hb(a,b){var c={};B(a.ba,function(a,e){b in a&&(c[e]=a[b])});return c}u("jsnx.get_node_attributes",Hb);u("jsnx.set_edge_attributes",function(a,b,c){B(c,function(b,c){c=c.split(",");a.m(c[0])[c[1]]=b})});Hb=function(a,b){var c={};B(a.o(i),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};
u("jsnx.get_edge_attributes",{}.Oa);var Ib={};u("jsnx.triangles",function(a,b){a.c()&&h(new J("triangles() is not defined for directed graphs."));if(a.k(b))return Math.floor(Lb(a,b).next()[2]/2);var c={};z(Lb(a,b),function(a){c[a[0]]=Math.floor(a[2]/2)});return c});
function Lb(a,b){a.l()&&h(new J("Not defined for multigraphs."));var c;c=q(b)?N(a.b(b),function(b){return[b,a.m(b)]}):R(a.adj);return A(c,function(b){var c=new I(D(b[1])),f=0;c.remove(b[0]);z(c,function(b){var d=new I(D(a.m(b)));d.remove(b);f+=Xa(c,d).w()});return[b[0],c.w(),f]})}
function Mb(a,b,c){a.l()&&h(new J("Not defined for multigraphs."));p(c)||(c="weight");var d;d=0===a.o().length?1:qb(a.o(i),function(a){return F(a[2],c,1)});b=q(b)?N(a.b(b),function(b){return[b,a.m(b)]}):R(a.adj);return A(b,function(b){var f=b[0],g=new I(D(b[1]));g.remove(f);var j=0,l=new I;z(g,function(b){var e=F(a.m(f)[b],c,1)/d;l.add(b);var ea=Ya(new I(D(a.m(b))),l);z(Xa(g,ea),function(g){var l=F(a.m(b)[g],c,1)/d,g=F(a.m(f)[g],c,1)/d;j+=Math.pow(e*l*g,1/3)})});return[f,g.w(),2*j]})}
u("jsnx.average_clustering",function(a,b,c,d){2===arguments.length?s(b)?(c=b,b=k):t(b)&&(d=b,b=k):3===arguments.length&&t(c)&&(d=c,c=k);q(c)||(c=k);q(d)||(d=i);var e=Oa(Nb(a,b,c));d||(e=ra(e,function(a){return a>0}));return S.B.apply(S,e)/e.length});function Nb(a,b,c){a.c()&&h(new J("Clustering algorithms are not defined for directed graphs."));var c=q(c)?Mb(a,b,c):Lb(a,b),d={};z(c,function(a){d[a[0]]=0===a[2]?0:a[2]/(a[1]*(a[1]-1))});return a.k(b)?Oa(d)[0]:d}u("jsnx.clustering",Nb);
u("jsnx.transitivity",function(a){var b=0,c=0;z(Lb(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c});u("jsnx.square_clustering",function(a,b){var c=!q(b)?a:a.b(b),d={};z(c,function(b){var c=d[b]=0;z(sb(D(a.m(b))),function(g){var j=g[0],g=g[1],l=Xa(new I(D(a.m(j))),D(a.m(g)));l.remove(b);l=l.w();d[b]+=l;var O=l+1,Q=a.m(j);g in Q&&(O+=1);c+=(C(a.m(j))-O)*(C(a.m(g))-O)+l});0<c&&(d[b]/=c)});return a.k(b)?Oa(d)[0]:d});var Ob,Pb=k,Qb="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
u("jsnx.draw",function(a,b,c){function d(){pa.e.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",$,")"].join("")});kb()}t(b)&&(c=b,b=k);var b=b||Pb||{},e=b.d3||window.d3,f={};ub(f,Rb,b);Pb=b;e||h(Error("D3 requried for draw()"));!q(f.element)&&!q(Ob)&&h(Error("Output element required for draw()"));Ob=F(f,"element",Ob);e.select(Ob).select("svg.jsnx").remove();var g=e.select(Ob),j=g.append("svg").classed("jsnx",i).attr("pointer-events","all"),l=j.append("g"),b=l.append("g").classed("edges",
i).selectAll("g.edge"),O=l.append("g").classed("nodes",i).selectAll("g.node"),Q=e.layout.force(),ea=f.width||parseInt(g.style("width"),10),Z=f.height||parseInt(g.style("height"),10),Gb=f.layout_attr,g=f.nodelist||k,T,aa,X,Jb=a.c(),qa=f.weighted,pa={e:O,f:b};if(f.with_labels){var ta=f.labels;T="object"===o(ta)?function(a){return F(ta,a.node,"")}:ia(ta)?ta:s(ta)?function(a){return a.data[ta]}:function(a){return a.node}}f.labels=T;if(qa){var Aa=f.weights;X="object"===o(Aa)?function(a){return F(Aa,a.node,
1)}:ia(Aa)?Aa:s(Aa)?function(a){return F(a.data,Aa,1)}:ca(1)}if(f.with_edge_labels){var Ba=f.edge_labels;aa=qa&&!p(Ba)?X:"object"===o(Ba)?function(a){return F(ta,a.node,"")}:ia(Ba)?Ba:s(Ba)?function(a){return a.data[Ba]}:function(a){return a.edge};f.edge_labels=aa}if(qa&&f.weighted_stroke){var qa=Fa(a.d(i),function(a,b){b=X({data:b[2]});return a>b?a:b},0),gc=e.scale.linear().range([1,f.edge_style["stroke-width"]]).domain([0,qa]);f.edge_style["stroke-width"]=function(a){return gc(X.call(this,a))}}j.select("svg.jsnx").remove();
j.attr("width",ea+"px").attr("height",Z+"px").style("opacity",1.0E-6).transition().duration(1E3).style("opacity",1);var hc={size:i,nodes:i,links:i,start:i};K(Gb,function(a){if(!(a in hc))Q[a](Gb[a])});Q.nodes([]).links([]).size([ea,Z]);var Ga=1,$=1;if(f.pan_zoom.enabled){var Kb=f.pan_zoom.scale,Ca=f.edge_style["stroke-width"];ia(Ca)?f.edge_style["stroke-width"]=function(){var a=Ca.apply(this,arguments);return $*(+a||parseInt(a,10))}:(Ca=+Ca||parseInt(Ca,10),f.edge_style["stroke-width"]=function(){return $*
Ca});(function(){var a=m,b=1,c=Ga;j.call(e.behavior.zoom().on("zoom",function(){var g=e.event.sourceEvent.shiftKey;if((g=Kb&&g||!(Kb||g))&&!a){b=e.event.scale;c=Ga;a=i}else!g&&a&&(a=m);Ga=g?c*(e.event.scale/b):Ga;$=!g?Ga/e.event.scale:$;g=e.event.translate;l.attr("transform","translate("+g[0]+","+g[1]+")scale("+e.event.scale+")");l.selectAll("g.edge > .line").style("stroke-width",f.edge_style["stroke-width"]);d()}))})()}var kb=fa;if(Jb){j.append("defs").append("marker").attr("id","Triangle").attr("markerUnits",
"strokeWidth").attr("refX","7").attr("refY","5").attr("viewBox","0 0 10 10").attr("orient","auto").append("path").attr("d","M 0 0 L 10 5 L 0 10 z");f.edge_attr["marker-end"]="url(#Triangle)";f.edge_style.fill="none";var Wa=f.layout_attr.linkDistance,Ha=f.edge_offset;ia(Wa)||(Wa=function(){return f.layout_attr.linkDistance});ga(Ha)&&(Ha=function(){return f.edge_offset});ha(Ha)&&(Ha=function(){return[f.edge_offset,f.edge_offset]});kb=function(){pa.f.each(function(a){if(a.source!==a.target){var b=e.select(this),
c=a.source.x,d=a.source.y,f=a.target.x,g=a.target.y,j=S.ea(c,d,f,g),f=Math.sqrt(Math.pow(f-c,2)+Math.pow(g-d,2)),g=Ha(a),g=[g[0]*$,g[1]*$];b.attr("transform",["translate(",c,",",d,")rotate(",j,")"].join(""));if(c=a.G.z(a.target.node,a.source.node)){var d=Wa(a)/3,j=-d/(f/2),l=j*f;b.select(".line").attr("d",["M",g[0],j*g[0],"Q",f/2,-d,f-g[1],-j*(f-g[1])+l].join(" "))}else b.select(".line").attr("d",["M",g[0],"0 L",f-g[1],0].join(" "));g=1/$;b.select("text").attr("x",f*g/2).attr("y",c?g*(-Wa(a)/4):0).attr("transform",
"scale("+$+")")}})}}else kb=function(){pa.f.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,j=a.target.y,a=S.ea(c,d,g,j),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(j-d,2)),j=g/2;b.attr("transform",["translate(",c,",",d,")rotate(",a,")"].join(""));b.select(".line").attr("d",["M 0 0 L",g,"0"].join(" "));f.with_edge_labels&&b.select("text").attr("x",j*(1/$)).attr("y",0).attr("transform","scale("+$+")"+(a>90&&a<279?"rotate(180,"+j*(1/$)+",0)":""))}})};Q.on("tick",
d);ea=a.H();Z=a.d();g&&(c=m,ea=a.b(g),Z=a.d(g));pa.e=Sb(a,ea,Q,O,f.node_shape,T);pa.f=Tb(a,Z,Q,b,aa);Ub(pa.e,{attr:f.node_attr,style:f.node_style,P:f.label_style,O:f.label_attr},f.with_labels);Vb(pa.f,{attr:f.edge_attr,style:f.edge_style,P:f.edge_label_style,O:f.edge_label_attr},f.with_edge_labels,k,Jb);c?Wb(a,Q,f,pa):a.bound?Xb(a):Yb(a);Q.start();return Q});
function Sb(a,b,c,d,e,f){var g=c.nodes();K(b,function(b){var c=a.node[b],b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,Zb);b=d.enter().append("g").classed("node",i).call(c.drag);b.append(e).classed("node-shape",i);f&&b.append("text").text(f);return d}
function Tb(a,b,c,d,e){var f=c.links();K(b,function(b){var c=b[0],d=b[1],b=b[2]||a.L(c,d),c={edge:[c,d],redge:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,$b);b=d.enter().append("g").classed("edge",i);b.append("path").classed("line",i);e&&b.append("text").text(e);return d}
function Ub(a,b,c,d){if(q(d)){var e={};K(d,function(a){e[r(a)?a[0]:a]=i});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");B(b.attr,function(a,b){f.attr(b,a)});B(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");B(b.O,function(a,b){g.attr(b,a)});B(b.P,function(a,b){g.style(b,a)})}}
function Vb(a,b,c,d,e){if(q(d)){var f={};K(d,function(a){f[[a[0],a[1]]]=i});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");B(b.attr,function(a,b){g.attr(b,a)});B(b.style,function(a,b){g.style(b,a)});if(c){var j=a.selectAll("text");B(b.O,function(a,b){j.attr(b,a)});B(b.P,function(a,b){j.style(b,a)})}}function Zb(a){return a.node}function $b(a){return a.edge}
function ac(a,b,c,d){var e=c.nodes();K(a.b(b),function(b){va(e,a.node[b].__d3datum__)});d=d.data(e,Zb);d.exit().remove();return d}function bc(a,b,c,d){var e=c.links();K(b,function(b){va(e,F(a.L(b[0],b[1],{}),"__d3datum__",k))});d=d.data(e,$b);d.exit().remove();return d}
function Wb(a,b,c,d){Xb(a,m);var e=a.constructor.prototype,f=c.node_shape,g={attr:c.node_attr,style:c.node_style,O:c.label_attr,P:c.label_style},j={attr:c.edge_attr,style:c.edge_style,O:c.edge_label_attr,P:c.edge_label_style},l=c.labels,O=c.edge_labels,Q=c.with_labels,ea=c.with_edge_labels,Z=a.c();a.add_node=a.D=function(a){var c=!this.k(a);e.add_node.apply(this,arguments);c&&(d.e=Sb(this,[a],b,d.e,f,l));Ub(d.e,g,Q,[a]);b.start()};a.add_nodes_from=a.g=function(a){var c=ra(M(a),function(a){return!this.k(r(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.e=Sb(this,c,b,d.e,f,l));Ub(d.e,g,Q,a);b.start()};a.add_edge=a.j=function(c,T){var aa=!this.z(c,T),X=[];aa&&(X=ra(c==T?[c]:[c,T],function(a){return!this.k(a)},this));e.add_edge.apply(a,arguments);0<X.length&&(d.e=Sb(this,X,b,d.e,f,l),Ub(d.e,g,Q,X));aa&&(d.f=Tb(this,[[c,T]],b,d.f,O));Vb(d.f,j,ea,[[c,T]],Z);b.start()};a.add_edges_from=a.a=function(c){var T=[],aa=[],X={},Z={},qa=this.c();K(c,function(a){var b=a[0],a=a[1];if(!this.z(b,
a)&&!([b,a]in X)&&(qa||!([a,b]in X)))if(T.push([b,a]),X[[b,a]]=i,!this.k(b)&&!(b in Z)&&(aa.push(b),Z[b]=i),!this.k(a)&&!(a in Z))aa.push(a),Z[a]=i},this);e.add_edges_from.apply(a,arguments);0<aa.length&&(d.e=Sb(this,aa,b,d.e,f,l),Ub(d.e,g,Q,aa));0<T.length&&(d.f=Tb(this,T,b,d.f,O));Vb(d.f,j,ea,T,qa);b.start()};a.remove_node=a.J=function(c){try{if(this.k(c)){d.e=ac(this,[c],b,d.e);var f=this.d([c]);this.c()&&(f=Ia(f,this.A([c])));d.f=bc(this,f,b,d.f);b.resume()}}catch(g){}e.remove_node.apply(a,arguments)};
a.remove_nodes_from=a.T=function(c){try{d.e=ac(this,c,b,d.e);var f=this.d(c);this.c()&&(f=Ia(f,this.A(c)));d.f=bc(this,f,b,d.f);b.resume()}catch(g){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.p=function(c,f){try{d.f=bc(this,[[c,f]],b,d.f),b.resume()}catch(g){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.t=function(c){try{d.f=bc(this,c,b,d.f),b.resume()}catch(f){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.e=d.e.data([],Zb);d.e.exit().remove();d.f=d.f.data([],
$b);d.f.exit().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=i}u("jsnx.is_bound",function(a){return a.bound});function Xb(a,b){if(a.bound){var c=a.constructor.prototype;oa(Qb,function(b){a[b]=c[b]});delete a.bound;(!p(b)||b)&&Yb(a)}}u("jsnx.unbind",Xb);function Yb(a){K(a.H(i),function(a){E(a[1],"__d3datum__")});K(a.d(i),function(a){E(a[2],"__d3datum__")})}
var Rb={layout_attr:{charge:-120,linkDistance:40},node_shape:"circle",node_attr:{r:10},node_style:{stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{stroke:"#000","stroke-width":2},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","dominant-baseline":"central","text-anchor":"middle","-webkit-user-select":"none"},with_labels:m,with_edge_labels:m,
edge_offset:10,weighted:m,weights:"weight",weighted_stroke:i,pan_zoom:{enabled:i,scale:i}};function cc(a,b){var c=dc(a,b);c.name("complete_graph("+a+")");1<a&&c.a(c.c()?tb(rb(a)):sb(rb(a)));return c}u("jsnx.complete_graph",cc);u("jsnx.cycle_graph",function(a,b){var c=ec(a,b);c.name("cycle_graph("+a+")");1<a&&c.j(a-1,0);return c});function dc(a,b){a instanceof U&&(b=a,a=k);q(a)||(a=0);var c;q(b)?(c=b,c.clear()):c=new U;c.g(rb(a));c.name("empty_graph("+a+")");return c}u("jsnx.empty_graph",dc);u("jsnx.null_graph",function(a){a=dc(0,a);a.name("null_graph()");return a});
function ec(a,b){var c=dc(a,b);c.name("path_graph("+a+")");c.a(A(rb(a-1),function(a){return[a,a+1]}));return c}u("jsnx.path_graph",ec);u("jsnx.trivial_graph",function(a){a=dc(1,a);a.name("null_graph()");return a});u("jsnx.fast_gnp_random_graph",function(a,b,c){q(c)||(c=m);var d=dc(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return fc(a,b,c);var e=1,f=-1,b=Math.log(1-b);if(c)for(d=V(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.j(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.j(e,f)}return d});
function fc(a,b,c){var d;d=c?V():U();d.g(rb(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return cc(a,d);a=d.c()?tb(rb(a)):sb(rb(a));z(a,function(a){Math.random()<b&&d.j(a[0],a[1])});return d}u("jsnx.gnp_random_graph",fc);u("jsnx.binomial_graph",fc);u("jsnx.erdos_renyi_graph",fc);function ic(a,b,c){var d=b;ia(b)&&(d={},z(a.H(),function(a){d[a]=b(a)}));return!p(c)||c?jc(a,d):kc(a,d)}u("jsnx.relabel_nodes",ic);
function kc(a,b){var c=new I(D(b)),d;if(0<Xa(c,b).w()){c=V(vb(b));c.t(c.U());try{d=Ib.Na.Za(c)}catch(e){e instanceof gb&&h(new gb("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True."))}d.reverse()}else d=c;var f=a.l(),g=a.c(),j;z(d,function(c){var d;c in b&&(d=b[c],a.k(c)||h(new J("Node "+c+" is not in the graph.")),a.D(d,a.node[c]),f?(j=w(a.o(c,i,i),function(a){return[d,a[1],a[2],a[3]]}),g&&(j=wa(j,w(a.N(c,i,i),function(a){return[a[0],d,a[2],a[3]]})))):(j=
w(a.o(c,i),function(a){return[d,a[1],a[2]]}),g&&(j=wa(j,w(a.N(c,i),function(a){return[a[0],d,a[2]]})))),a.J(c),a.a(j))});return a}function jc(a,b){var c=new a.constructor;c.name("("+a.name()+")");a.l()?c.a(A(a.d(i,i),function(a){return[F(b,a[0],a[0]),F(b,a[1],a[1]),a[2],G(a[3])]})):c.a(A(a.d(i),function(a){return[F(b,a[0],a[0]),F(b,a[1],a[1]),G(a[2])]}));c.g(A(a,function(a){return F(b,a,a)}));var d={},e;for(e in a.node)d[F(b,e,e)]=G(a.node[e]);H(c.node,d);H(c.graph,G(a.graph));return c}
u("jsnx.convert_node_labels_to_integers",function(a,b,c,d){3===arguments.length&&t(c)?(d=c,c=k):2===arguments.length&&(t(b)?(d=b,b=k):s(b)&&(c=b,b=k));q(b)||(b=0);q(c)||(c="default");q(d)||(d=i);var e={},f,g,j,l;if("default"===c){f=a.nodes();g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g]]=j}else if("sorted"===c){f=a.nodes();f.sort();g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g]]=j}else if("increasing degree"===c){f=Ja(a.n());f.sort(function(a,b){return a[1]-b[1]});g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g][0]]=
j}else if("decreasing degree"===c){f=Ja(a.n());f.sort(function(a,b){return b[1]-a[1]});g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g][0]]=j}else h(new J("Unkown node ordering: "+c));g=ic(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g});}());
