(function(){function h(a){throw a;}var ca=void 0,i=!0,k=null,m=!1;function da(a){return function(){return a}}var n,ea=this;function fa(){}
function o(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){return a!==ca}function q(a){return a!=k}function ha(a){return"array"==o(a)}function r(a){var b=o(a);return"array"==b||"object"==b&&"number"==typeof a.length}function s(a){return"string"==typeof a}function t(a){return"boolean"==typeof a}function ia(a){return"number"==typeof a}function ja(a){return"function"==o(a)}function ka(a){var b=typeof a;return"object"==b&&a!=k||"function"==b}
var la="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ma=0;function u(a,b){var c=a.split("."),d=ea;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function na(a,b){function c(){}c.prototype=b.prototype;a.Xa=b.prototype;a.prototype=new c;a.prototype.constructor=a};var v=Array.prototype,oa=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if(s(a))return!s(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=s(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=s(a)?
a.split(""):a,j=0;j<d;j++)if(j in g){var l=g[j];b.call(c,l,j,a)&&(e[f++]=l)}return e},w=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=s(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function ua(a,b){if(a.reduce)return a.reduce(b,0);var c=0;ra(a,function(d,e){c=b.call(ca,c,d,e,a)});return c}
function va(a,b){var c;a:{c=a.length;for(var d=s(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(ca,d[e],e,a)){c=e;break a}c=-1}return 0>c?k:s(a)?a.charAt(c):a[c]}function wa(a,b){var c=oa(a,b);0<=c&&v.splice.call(a,c,1)}function xa(a){return v.concat.apply(v,arguments)}function ya(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function za(a,b,c){return 2>=arguments.length?v.slice.call(a,b):v.slice.call(a,b,c)}function Aa(a,b){return a>b?1:a<b?-1:0}
function Ea(a){for(var b=[],c=0;c<a;c++)b[c]=0;return b}function Fa(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var x="StopIteration"in ea?ea.StopIteration:Error("StopIteration");function y(){}y.prototype.next=function(){h(x)};y.prototype.s=function(){return this};function Ia(a){if(a instanceof y)return a;if("function"==typeof a.s)return a.s(m);if(r(a)){var b=0,c=new y;c.next=function(){for(;;){b>=a.length&&h(x);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}
function z(a,b,c){if(r(a))try{ra(a,b,c)}catch(d){d!==x&&h(d)}else{a=Ia(a);try{for(;;)b.call(c,a.next(),ca,a)}catch(e){e!==x&&h(e)}}}function A(a,b,c){var d=Ia(a),a=new y;a.next=function(){for(;;){var a=d.next();return b.call(c,a,ca,d)}};return a}function Ja(a,b,c){var d=c;z(a,function(a){d=b.call(ca,d,a)});return d}function Ka(a){var b=arguments,c=b.length,d=0,e=new y;e.next=function(){try{return d>=c&&h(x),Ia(b[d]).next()}catch(a){return(a!==x||d>=c)&&h(a),d++,this.next()}};return e}
function La(a){if(r(a))return ya(a);var a=Ia(a),b=[];z(a,function(a){b.push(a)});return b};function Ma(){}Ma.fa=function(){return Ma.ha?Ma.ha:Ma.ha=new Ma};Ma.prototype.Aa=0;Ma.fa();var Na={};function Oa(a){if(!r(a))return m;for(var b=0,c=a.length;b<c;b++)if(window.isNaN(a[b]))return m;return i}u("jsnx.utils.is_list_of_ints",Oa);u("jsnx.utils.cumulative_sum",function(a){var b=0;return A(a,function(a){return b+=a})});u("jsnx.utils.generate_unique_node",function(){return":"+(Ma.fa().Aa++).toString(36)});function B(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Pa(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function C(a){var b=0,c;for(c in a)b++;return b}function Qa(a){for(var b in a)return b}function Ra(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function D(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Sa(a){for(var b in a)delete a[b]}function E(a,b){b in a&&delete a[b]}function F(a,b,c){return b in a?a[b]:c}
function G(a){var b={},c;for(c in a)b[c]=a[c];return b}var Ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function H(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ta.length;f++)c=Ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function Ua(a){var b=arguments.length;if(1==b&&ha(arguments[0]))return Ua.apply(k,arguments[0]);b%2&&h(Error("Uneven number of arguments"));for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function Va(a){if("function"==typeof a.K)return a.K();if(s(a))return a.split("");if(r(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ra(a)};function Wa(a,b){this.k={};this.j=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.$(a)}n=Wa.prototype;n.w=0;n.W=0;n.z=function(){return this.w};n.K=function(){Ya(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.k[this.j[b]]);return a};n.clear=function(){this.k={};this.W=this.w=this.j.length=0};
n.remove=function(a){return Object.prototype.hasOwnProperty.call(this.k,a)?(delete this.k[a],this.w--,this.W++,this.j.length>2*this.w&&Ya(this),i):m};function Ya(a){if(a.w!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];Object.prototype.hasOwnProperty.call(a.k,d)&&(a.j[c++]=d);b++}a.j.length=c}if(a.w!=a.j.length){for(var e={},c=b=0;b<a.j.length;)d=a.j[b],Object.prototype.hasOwnProperty.call(e,d)||(a.j[c++]=d,e[d]=1),b++;a.j.length=c}}
n.set=function(a,b){Object.prototype.hasOwnProperty.call(this.k,a)||(this.w++,this.j.push(a),this.W++);this.k[a]=b};n.$=function(a){var b;a instanceof Wa?(Ya(a),b=a.j.concat(),a=a.K()):(b=D(a),a=Ra(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};n.X=function(){return new Wa(this)};
n.s=function(a){Ya(this);var b=0,c=this.j,d=this.k,e=this.W,f=this,g=new y;g.next=function(){for(;;){e!=f.W&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(x);var g=c[b++];return a?g:d[g]}};return g};function I(a){this.k=new Wa;a&&this.$(a)}function Za(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[la]||(a[la]=++ma)):b.substr(0,1)+a}n=I.prototype;n.z=function(){return this.k.z()};n.add=function(a){this.k.set(Za(a),a)};n.$=function(a){for(var a=Va(a),b=a.length,c=0;c<b;c++)this.add(a[c])};n.remove=function(a){return this.k.remove(Za(a))};n.clear=function(){this.k.clear()};n.contains=function(a){a=Za(a);return Object.prototype.hasOwnProperty.call(this.k.k,a)};
function $a(a,b){for(var c=new I,d=Va(b),e=0;e<d.length;e++){var f=d[e];a.contains(f)&&c.add(f)}return c}function ab(a,b){for(var c=a.X(),d=Va(b),e=d.length,f=0;f<e;f++)c.remove(d[f]);return c}n.K=function(){return this.k.K()};n.X=function(){return new I(this)};n.s=function(){return this.k.s(m)};function bb(a){if(q(a))try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new Na.Ga;return a}
function cb(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=db(a.adj,b,a.i()),"graph"in a&&"object"===o(a.graph)&&(d.graph=G(a.graph)),"node"in a&&"object"===o(a.node)&&(d.node=Pa(a.node,function(a){return G(a)})),d}catch(e){h(Error("Input is not a correct jsnx graph"))}if("object"===o(a))try{return db(a,b,c)}catch(f){try{return eb(a,b)}catch(g){h(Error("Input is not known type."))}}if(r(a))try{return fb(a,b)}catch(j){h(Error("Input is not valid edge list"))}}u("jsnx.to_networkx_graph",cb);
u("jsnx.convert_to_undirected",Na.Ma);u("jsnx.convert_to_undirected",Na.La);u("jsnx.to_dict_of_lists",Na.Ya);function eb(a,b){var c=bb(b);c.h(a);if(c.i()&&!c.c()){var d={};B(a,function(a,b){ra(a,function(a){a in d||c.g(b,a)});d[b]=1})}else{var e=[];B(a,function(a,b){ra(a,function(a){e.push([b,a])})});c.a(e)}return c}
function db(a,b,c){var d=bb(b),e,f;d.h(a);c?d.c()?(d.i()?(e=[],B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){B(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){B(a,function(a){e.push([b,c,a])})})})),d.a(e)):d.i()?(f=new I,B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){f.contains([b,c].toString())||(e=[],B(a,function(a,d){e.push([b,c,d,a])}),d.a(e),f.add([c,b].toString()))})})):(f=new I,B(a,function(a,b){r(a)&&h(Error());B(a,function(a,
c){f.contains([b,c].toString())||(e=[],B(a,function(a){e.push([b,c,a])}),d.a(e),f.add([c,b].toString()))})})):d.i()&&!d.c()?(f=new I,B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){f.contains([b,c].toString())||(d.g(b,c,a),f.add([c,b].toString()))})})):(e=[],B(a,function(a,b){r(a)&&h(Error());B(a,function(a,c){e.push([b,c,a])})}),d.a(e));return d}function fb(a,b){var c=bb(b);c.a(a);return c};function gb(a){this.name="JSNetworkXException";this.message=a}gb.prototype=Error();gb.prototype.constructor=gb;u("jsnx.JSNetworkXException",gb);function J(a){gb.call(this,a);this.name="JSNetworkXError"}na(J,gb);u("jsnx.JSNetworkXError",J);function hb(a){gb.call(this,a);this.name="JSNetworkXPointlessConcept"}na(hb,gb);u("jsnx.JSNetworkXPointlessConcept",hb);function ib(a){gb.call(this,a);this.name="JSNetworkXAlgorithmError"}na(ib,gb);u("jsnx.JSNetworkXAlgorithmError",ib);
function jb(a){ib.call(this,a);this.name="JSNetworkXUnfeasible"}na(jb,ib);u("jsnx.JSNetworkXUnfeasible",jb);function kb(a){jb.call(this,a);this.name="JSNetworkXNoPath"}na(kb,jb);u("jsnx.JSNetworkXNoPath",kb);function lb(a){ib.call(this,a);this.name="JSNetworkXUnbounded"}na(lb,ib);u("jsnx.JSNetworkXUnbounded",lb);function nb(a){return Ja(ob(a),function(a,c){a[c[0]]=c[1];return a},{})}function pb(a){return a instanceof y||ja(a.s)}function qb(a){if(s(a)||r(a)||"length"in a)return a.length;if(rb(a))return C(a);h(new TypeError)}function K(a,b,c,d){t(c)&&(d=c,c=k);if(d)var e=b,b=function(a){e.apply(this,a)};pb(a)?z(a,b,c):r(a)||s(a)?ra(a,b,c):ka(a)&&K(D(a),b,c)}u("jsnx.forEach",K);function L(a,b,c){if(r(a))return w(a,b,c);if(pb(a))return A(a,b,c);if(ka(a))return Pa(a,b,c);h(new TypeError)}
function sb(){var a=arguments,b=a[0];if(r(b))return Fa.apply(k,a);if(pb(b)){var b=new y,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(ka(b))return Fa.apply(k,w(a,D));h(new TypeError)}function tb(a,b){a=ja(b)?L(a,function(){return b.apply(k,arguments)}):M(a);return Math.max.apply(k,a)}
function N(a,b,c){if(0===arguments.length)return[];1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new y,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(x);g=f;f=f+c;return g};return d}
function ub(a){var b=M(a),c=b.length;if(2>c)return new y;var d=M(N(2)),a=new y;a.next=function(){var a=w(d,function(a){return b[a]});this.next=function(){var a=m,e;for(e=2;e--;)if(d[e]!=e+c-2){a=i;break}a||h(x);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return w(d,function(a){return b[a]})};return a};return a}
function vb(a){var b=M(a),c=b.length,d=ia(2)?2:c;if(d>c)return new y;var e=M(N(c)),f=M(N(c,c-d,-1)),a=new y,g=new y,j,l=i;a.next=function(){this.next=j.next;return w(e.slice(0,d),function(a){return b[a]})};g.next=function(){return l};j=P(g,function(a){a||h(x);l=m;return N(d-1,-1,-1)},function(a){if(!l)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var g=f[a],j=e[a];e[a]=e[e.length-g];e[e.length-g]=j;l=i;return ob([w(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function wb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!p(a[c])||"object"!==o(a[c])?a[c]=Q(d[c]):"object"===o(a[c])&&"object"===o(d)&&wb(a[c],d[c]);for(var f=0;f<Ta.length;f++)c=Ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(!p(a[c])||"object"!==o(a[c])?a[c]=Q(d[c]):"object"===o(a[c])&&"object"===o(d)&&wb(a[c],d[c]))}}function M(a){if(r(a))return ya(a);if(pb(a))return La(a);if(ka(a))return D(a);h(new TypeError)}u("jsnx.toArray",M);
function xb(a){var b=[];B(a,function(a,d){b.push([d,a])});return b}function S(a){var b=new y,c=Ia(D(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function ob(a){"object"===o(a)&&(!r(a)&&!pb(a))&&(a=D(a));return Ia(a)}
function P(a){var b=new y,c=za(arguments,1);if(0===c.length)return a;try{a=Ia(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&h(new TypeError)},b}var e=k;b.next=function(){var d,g;try{for(;!p(d);)d=e.next()}catch(j){for(;!p(g)||!p(d);)g=a.next(),d=c[0](g);if(pb(d))return e=P.apply(k,xa([d],za(c,1))),b.next();e=k}return d};return b}u("jsnx.sentinelIterator",function(a,b){var c=new y;c.next=function(){var c;try{c=Ia(a).next()}catch(e){e!=x&&h(e),c=b}return c};return c});
function rb(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==o(a)||a.nodeType||a==a.window)return m;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return m}catch(c){return m}for(var d in a);return d===ca||b.call(a,d)}
function Q(a,b){var b=b||[],c=o(a);if("object"==c&&rb(a)||"array"==c){var d=va(b,function(b){return a===b[0]});if(d!==k)return d[1];if(a.X)return d=[a,a.X()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var e in a)c[e]=Q(a[e],b);return c}return a}function yb(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=Q(c);a=new b;for(d in c)a[d]=c[d];return a};function zb(a){var b=[];Ab(new Bb,a,b);return b.join("")}function Bb(){this.Z=ca}
function Ab(a,b,c){switch(typeof b){case "string":Cb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==k){c.push("null");break}if(ha(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Ab(a,a.Z?a.Z.call(b,""+f,e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Cb(f,c),c.push(":"),
Ab(a,a.Z?a.Z.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var Db={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Eb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Cb(a,b){b.push('"',a.replace(Eb,function(a){if(a in Db)return Db[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Db[a]=e+b.toString(16)}),'"')};var T={Ua:function(a){return Math.floor(Math.random()*a)},$a:function(a,b){return a+Math.random()*(b-a)},Ka:function(a,b,c){return Math.min(Math.max(a,b),c)},za:function(a,b){var c=a%b;return 0>c*b?c+b:c},Ra:function(a,b,c){return a+c*(b-a)},Ta:function(a,b,c){return Math.abs(a-b)<=(c||1.0E-6)},da:function(a){return T.za(a,360)},ma:function(a){return a*Math.PI/180},Fa:function(a){return 180*a/Math.PI},Ia:function(a,b){return b*Math.cos(T.ma(a))},Ja:function(a,b){return b*Math.sin(T.ma(a))},ea:function(a,
b,c,d){return T.da(T.Fa(Math.atan2(d-b,c-a)))},Ha:function(a,b){var c=T.da(b)-T.da(a);180<c?c-=360:-180>=c&&(c=360+c);return c},Va:function(a){return 0==a?0:0>a?-1:1},Sa:function(a,b,c,d){for(var c=c||function(a,b){return a==b},d=d||function(b){return a[b]},e=a.length,f=b.length,g=[],j=0;j<e+1;j++)g[j]=[],g[j][0]=0;for(var l=0;l<f+1;l++)g[0][l]=0;for(j=1;j<=e;j++)for(l=1;l<=e;l++)g[j][l]=c(a[j-1],b[l-1])?g[j-1][l-1]+1:Math.max(g[j-1][l],g[j][l-1]);for(var O=[],j=e,l=f;0<j&&0<l;)c(a[j-1],b[l-1])?(O.unshift(d(j-
1,l-1)),j--,l--):g[j-1][l]>g[j][l-1]?j--:l--;return O},o:function(a){return ua(arguments,function(a,c){return a+c})},ta:function(a){return T.o.apply(k,arguments)/arguments.length},Wa:function(a){var b=arguments.length;if(2>b)return 0;var c=T.ta.apply(k,arguments),b=T.o.apply(k,w(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},Qa:function(a){return isFinite(a)&&0==a%1},Pa:function(a){return isFinite(a)&&!isNaN(a)}};function U(a,b){if(!(this instanceof U))return new U(a,b);this.graph={};this.node={};this.adj={};q(a)&&cb(a,this);H(this.graph,b||{});this.edge=this.adj}u("jsnx.classes.Graph",U);u("jsnx.Graph",U);U.__name__="Graph";U.prototype.wa=k;U.prototype.graph=U.prototype.wa;U.prototype.ba=k;U.prototype.node=U.prototype.ba;U.prototype.ra=k;U.prototype.adj=U.prototype.ra;U.prototype.ua=k;U.prototype.edge=U.prototype.ua;
U.prototype.name=function(a){if(p(a))this.graph.name=a.toString();else return this.graph.name||""};U.prototype.name=U.prototype.name;U.prototype.toString=function(){return this.name()};U.prototype.toString=U.prototype.toString;U.prototype.s=function(){return ob(this.adj)};U.prototype.__iterator__=U.prototype.s;U.prototype.m=function(a){a in this.adj||h({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};U.prototype.get_node=U.prototype.m;
U.prototype.D=function(a,b){q(b)||(b={});"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));a in this.adj?H(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};U.prototype.add_node=U.prototype.D;U.prototype.h=function(a,b){var c,d,e,f,g,b=b||{};K(a,function(a){c=!(a in this.adj);ha(a)?(d=a[0],e=a[1],d in this.adj?(g=this.node[d],H(g,b,e)):(this.adj[d]={},f=G(b),H(f,e),this.node[d]=f)):c?(this.adj[a]={},this.node[a]=G(b)):H(this.node[a],b)},this)};
U.prototype.add_nodes_from=U.prototype.h;U.prototype.J=function(a){var b=this.adj,c;a in this.node||h(new J("The node "+a+" is not in the graph"));c=D(b[a]);E(this.node,a);ra(c,function(c){E(b[c],a)});E(b,a)};U.prototype.remove_node=U.prototype.J;U.prototype.T=function(a){var b=this.adj;K(a,function(a){try{E(this.node,a),B(b[a],function(d,f){E(b[f],a)}),E(b,a)}catch(d){}},this)};U.prototype.remove_nodes_from=U.prototype.T;U.prototype.H=function(a){return a?S(this.node):ob(D(this.adj))};
U.prototype.nodes_iter=U.prototype.H;U.prototype.nodes=function(a){return La(this.H(a))};U.prototype.nodes=U.prototype.nodes;U.prototype.R=function(){return C(this.adj)};U.prototype.number_of_nodes=U.prototype.R;U.prototype.ia=function(){return C(this.adj)};U.prototype.order=U.prototype.ia;U.prototype.l=function(a){return!ha(a)&&a in this.adj};U.prototype.has_node=U.prototype.l;
U.prototype.g=function(a,b,c){c=c||{};"object"!==o(c)&&h(new J("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=F(this.adj[a],b,{});H(d,c);this.adj[a][b]=d;this.adj[b][a]=d};U.prototype.add_edge=U.prototype.g;
U.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));K(a,function(a){var d=qb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new J("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});f in this.adj||(this.adj[f]={},this.node[f]={});a=F(this.adj[e],f,{});H(a,b,g);this.adj[e][f]=a;this.adj[f][e]=a},this)};U.prototype.add_edges_from=U.prototype.a;
U.prototype.qa=function(a,b,c){c=c||{};s(b)||(c=b,b="weight");this.a(L(a,function(a){var c={};c[b]=a[2];p(c[b])||h(new TypeError("Values must consist of three elements: "+zb(a)));return[a[0],a[1],c]}),c)};U.prototype.add_weighted_edges_from=U.prototype.qa;U.prototype.q=function(a,b){try{E(this.adj[a],b),a!=b&&E(this.adj[b],a)}catch(c){c instanceof TypeError&&h(new J("The edge "+a+"-"+b+" is not in the graph")),h(c)}};U.prototype.remove_edge=U.prototype.q;
U.prototype.u=function(a){K(a,function(a){var c=a[0],a=a[1];c in this.adj&&a in this.adj[c]&&(E(this.adj[c],a),c!=a&&E(this.adj[a],c))},this)};U.prototype.remove_edges_from=U.prototype.u;U.prototype.A=function(a,b){return a in this.adj&&b in this.adj[a]};U.prototype.has_edge=U.prototype.A;U.prototype.Q=function(a){a in this.adj||h(new J("The node "+a+" is not in the graph."));return M(this.adj[a])};U.prototype.neighbors=U.prototype.Q;
U.prototype.aa=function(a){a in this.adj||h(new J("The node "+a+" is not in the graph."));return ob(this.adj[a])};U.prototype.neighbors_iter=U.prototype.aa;U.prototype.p=function(a,b){return M(this.d(a,b))};U.prototype.edges=U.prototype.p;
U.prototype.d=function(a,b){t(a)&&(b=a,a=k);var c={},d,e;d=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return b?P(d,function(a){e=a[0];var b=new y,d=S(a[1]);b.next=function(){try{return d.next()}catch(a){a===x&&(c[e]=1);h(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):P(d,function(a){e=a[0];var b=new y,d=ob(a[1]);b.next=function(){try{return d.next()}catch(a){a===x&&(c[e]=1);h(a)}};return b},function(a){if(!(a in c))return[e,a]})};
U.prototype.edges_iter=U.prototype.d;U.prototype.L=function(a,b,c){p(c)||(c=k);return a in this.adj?F(this.adj[a],b,c):c};U.prototype.get_edge_data=U.prototype.L;U.prototype.sa=function(){return M(L(this.t(),function(a){return D(a[1])}))};U.prototype.adjacency_list=U.prototype.sa;U.prototype.t=function(){return S(this.adj)};U.prototype.adjacency_iter=U.prototype.t;U.prototype.F=function(a,b){return this.l(a)?this.n(a,b).next()[1]:nb(La(this.n(a,b)))};U.prototype.degree=U.prototype.F;
U.prototype.n=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return b?L(c,function(a){var c=a[0],a=a[1],f=0,g;for(g in a)f+=+F(a[g],b,1);f+=+(c in a&&F(a[c],b,1));return[c,f]}):L(c,function(a){return[a[0],C(a[1])+ +(a[0]in a[1])]})};U.prototype.degree_iter=U.prototype.n;U.prototype.clear=function(){this.name("");Sa(this.adj);Sa(this.node);Sa(this.graph)};U.prototype.clear=U.prototype.clear;U.prototype.copy=function(){return yb(this)};U.prototype.copy=U.prototype.copy;
U.prototype.i=da(m);U.prototype.is_multigraph=U.prototype.i;U.prototype.c=da(m);U.prototype.is_directed=U.prototype.c;U.prototype.C=function(){var a=new W;a.name(this.name());a.h(this);a.a(function(){var a;return P(this.t(),function(c){a=c[0];return S(c[1])},function(c){return[a,c[0],Q(c[1])]})}.call(this));a.graph=Q(this.graph);a.node=Q(this.node);return a};U.prototype.to_directed=U.prototype.C;U.prototype.V=function(){return yb(this)};U.prototype.to_undirected=U.prototype.V;
U.prototype.v=function(a){var a=this.b(a),b=new this.constructor,c=b.adj,d=this.adj;K(a,function(a){var b={};c[a]=b;B(d[a],function(d,j){j in c&&(b[j]=d,c[j][a]=d)})});K(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};U.prototype.subgraph=U.prototype.v;U.prototype.Ba=function(){return w(sa(xb(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};U.prototype.nodes_with_selfloops=U.prototype.Ba;
U.prototype.U=function(a){return a?w(sa(xb(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):w(sa(xb(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};U.prototype.selfloop_edges=U.prototype.U;U.prototype.Ca=function(){return this.U().length};U.prototype.number_of_selfloops=U.prototype.Ca;U.prototype.size=function(a){var b=T.o.apply(k,Ra(this.F(k,a)))/2;return q(a)?b:Math.floor(b)};U.prototype.size=U.prototype.size;
U.prototype.I=function(a,b){return!q(a)?Math.floor(this.size()):b in this.adj[a]?1:0};U.prototype.number_of_edges=U.prototype.I;U.prototype.pa=function(a,b){var c=M(a),d=c[0];this.a(L(za(c,1),function(a){return[d,a]}),b)};U.prototype.add_star=U.prototype.pa;U.prototype.oa=function(a,b){var c=M(a);this.a(Fa(za(c,0,c.length-1),za(c,1)),b)};U.prototype.add_path=U.prototype.oa;U.prototype.na=function(a,b){var c=M(a);this.a(Fa(c,xa(za(c,1),[c[0]])),b)};U.prototype.add_cycle=U.prototype.na;
U.prototype.b=function(a){return q(a)?this.l(a)?ob([a.toString()]):function(a,c){var d=new y,e=P(a,function(a){if(a in c)return a.toString()});d.next=function(){try{return e.next()}catch(a){a instanceof TypeError&&h(new J("nbunch is not a node or a sequence of nodes")),h(a)}};return d}(a,this.adj):ob(this.adj)};U.prototype.nbunch_iter=U.prototype.b;function W(a,b){if(!(this instanceof W))return new W(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;q(a)&&cb(a,this);H(this.graph,b||{});this.edge=this.adj}u("jsnx.classes.DiGraph",W);u("jsnx.DiGraph",W);na(W,U);W.__name__="DiGraph";W.prototype.D=function(a,b){q(b)||(b={});"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));a in this.succ?H(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};W.prototype.add_node=W.prototype.D;
W.prototype.h=function(a,b){var c,d,e,f,g,b=b||{};K(ob(a),function(a){c=!(a in this.succ);ha(a)?(d=a[0],e=a[1],d in this.succ?(g=this.node[d],H(g,b,e)):(this.succ[d]={},this.pred[d]={},f=G(b),H(f,e),this.node[d]=f)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=G(b)):H(this.node[a],b)},this)};W.prototype.add_nodes_from=W.prototype.h;
W.prototype.J=function(a){a in this.node||h(new J("The node "+a+" is not in the graph"));var b=this.succ[a];E(this.node,a);B(b,function(b,d){E(this.pred[d],a)},this);E(this.succ,a);B(this.pred[a],function(b,d){E(this.succ[d],a)},this);E(this.pred,a)};W.prototype.remove_node=W.prototype.J;
W.prototype.T=function(a){var b;K(a,function(a){a in this.succ&&(b=this.succ[a],E(this.node,a),B(b,function(b,e){E(this.pred[e],a)},this),E(this.succ,a),B(this.pred[a],function(b,e){E(this.succ[e],a)},this),E(this.pred,a))},this)};W.prototype.remove_nodes_from=W.prototype.T;
W.prototype.g=function(a,b,c){c=c||{};"object"!==o(c)&&h(new J("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=F(this.adj[a],b,{});H(d,c);this.succ[a][b]=d;this.pred[b][a]=d};W.prototype.add_edge=W.prototype.g;
W.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));K(a,function(a){var d=qb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new J("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});f in this.succ||(this.succ[f]={},this.pred[f]={},this.node[f]={});a=F(this.adj[e],f,{});H(a,b,g);this.succ[e][f]=a;this.pred[f][e]=a},this)};
W.prototype.add_edges_from=W.prototype.a;W.prototype.q=function(a,b){try{E(this.succ[a],b),E(this.pred[b],a)}catch(c){c instanceof TypeError&&h(new J("The edge "+a+"-"+b+" is not in the graph")),h(c)}};W.prototype.remove_edge=W.prototype.q;W.prototype.u=function(a){K(a,function(a){var c=a[0],a=a[1];c in this.succ&&a in this.succ[c]&&(E(this.succ[c],a),E(this.pred[a],c))},this)};W.prototype.remove_edges_from=W.prototype.u;W.prototype.ya=function(a,b){return a in this.succ&&b in this.succ[a]};
W.prototype.has_successor=W.prototype.ya;W.prototype.xa=function(a,b){return a in this.pred&&b in this.pred[a]};W.prototype.has_predecessor=W.prototype.xa;W.prototype.la=function(a){a in this.succ||h(new J("The node "+a+" is not in the digraph."));return ob(this.succ[a])};W.prototype.successors_iter=W.prototype.la;W.prototype.Ea=function(a){a in this.pred||h(new J("The node "+a+" is not in the digraph."));return ob(this.pred[a])};W.prototype.predecessors_iter=W.prototype.Ea;
W.prototype.ka=function(a){a in this.succ||h(new J("The node "+a+" is not in the digraph."));return M(this.succ[a])};W.prototype.successors=W.prototype.ka;W.prototype.Da=function(a){a in this.succ||h(new J("The node "+a+" is not in the digraph."));return M(this.pred[a])};W.prototype.predecessors=W.prototype.Da;W.prototype.Q=W.prototype.ka;W.prototype.neighbors=W.prototype.Q;W.prototype.aa=W.prototype.la;W.prototype.neighbors_iter=W.prototype.aa;
W.prototype.d=function(a,b){t(a)&&(b=a,a=k);var c,d,e;c=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):xb(this.adj);return b?P(c,function(a){d=a[0];e=a[1];return S(e)},function(a){return[d,a[0],a[1]]}):P(c,function(a){d=a[0];e=a[1];return S(e)},function(a){return[d,a[0]]})};W.prototype.edges_iter=W.prototype.d;W.prototype.Y=W.prototype.d;W.prototype.out_edges_iter=W.prototype.Y;W.prototype.ca=U.prototype.p;W.prototype.out_edges=W.prototype.ca;
W.prototype.B=function(a,b){t(a)&&(b=a,a=k);var c,d;c=q(a)?L(this.b(a),function(a){return[a,this.pred[a]]},this):xb(this.pred);return b?P(c,function(a){d=a[0];return S(a[1])},function(a){return[a[0],d,a[1]]}):P(c,function(a){d=a[0];return S(a[1])},function(a){return[a[0],d]})};W.prototype.in_edges_iter=W.prototype.B;W.prototype.N=function(a,b){return M(this.B(a,b))};W.prototype.in_edges=W.prototype.N;
W.prototype.n=function(a,b){var c;c=q(a)?sb(L(this.b(a),function(a){return[a,this.succ[a]]},this),L(this.b(a),function(a){return[a,this.pred[a]]},this)):sb(S(this.succ),S(this.pred));return b?L(c,function(a){var c=a[0][1],f=a[1][1],g=0,j;for(j in c)g+=+F(c[j],b,1);for(j in f)g+=+F(f[j],b,1);return[a[0][0],g]}):L(c,function(a){return[a[0][0],qb(a[0][1])+qb(a[1][1])]})};W.prototype.degree_iter=W.prototype.n;
W.prototype.M=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.pred[a]]},this):S(this.pred);return b?L(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+F(f[g],b,1);return[a[0],c]}):L(c,function(a){return[a[0],C(a[1])]})};W.prototype.in_degree_iter=W.prototype.M;W.prototype.S=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.succ[a]]},this):S(this.succ);return b?L(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+F(f[g],b,1);return[a[0],c]}):L(c,function(a){return[a[0],C(a[1])]})};
W.prototype.out_degree_iter=W.prototype.S;W.prototype.ga=function(a,b){return this.l(a)?this.M(a,b).next()[1]:nb(this.M(a,b))};W.prototype.in_degree=W.prototype.ga;W.prototype.ja=function(a,b){return this.l(a)?this.S(a,b).next()[1]:nb(this.S(a,b))};W.prototype.out_degree=W.prototype.ja;W.prototype.clear=function(){Sa(this.succ);Sa(this.pred);Sa(this.node);Sa(this.graph)};W.prototype.clear=W.prototype.clear;W.prototype.i=da(m);W.prototype.is_multigraph=W.prototype.i;W.prototype.c=da(i);
W.prototype.is_directed=W.prototype.c;W.prototype.C=function(){return yb(this)};W.prototype.to_directed=W.prototype.C;W.prototype.V=function(a){var b=new U;b.name(this.name());b.h(this);var c=this.pred,d;a?b.a(P(this.t(),function(a){d=a[0];return S(a[1])},function(a){if(a[0]in c[d])return[d,a[0],Q(a[1])]})):b.a(P(this.t(),function(a){d=a[0];return S(a[1])},function(a){return[d,a[0],Q(a[1])]}));b.graph=Q(this.graph);b.node=Q(this.node);return b};W.prototype.to_undirected=W.prototype.V;
W.prototype.reverse=function(a){(a=!p(a)||a)?(a=new this.constructor(k,{name:"Reverse of ("+this.name()+")"}),a.h(this),a.a(L(this.d(i),function(a){return[a[1],a[0],Q(a[2])]})),a.graph=Q(this.graph),a.node=Q(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};W.prototype.reverse=W.prototype.reverse;
W.prototype.v=function(a){var a=this.b(a),b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;K(a,function(a){c[a]={};d[a]={}});K(c,function(a){var b=c[a];B(e[a],function(e,l){l in c&&(b[l]=e,d[l][a]=e)})});K(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};W.prototype.subgraph=W.prototype.v;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);U.call(this,a,b)}na(Y,U);u("jsnx.classes.MultiGraph",Y);u("jsnx.MultiGraph",Y);Y.__name__="MultiGraph";
Y.prototype.g=function(a,b,c,d){var e,f;q(c)&&(!s(c)&&!ia(c))&&(d=c,c=k);d=d||{};"object"!==o(d)&&h(new J("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});if(b in this.adj[a]){f=this.adj[a][b];if(!q(c))for(c=C(f);c in f;)c+=1;e=F(f,c,{});H(e,d);f[c]=e}else q(c)||(c=0),e={},H(e,d),f=Ua(c,e),this.adj[a][b]=f,this.adj[b][a]=f};Y.prototype.add_edge=Y.prototype.g;
Y.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&h(new J("The attr_dict argument must be an object."));K(a,function(a){var d=qb(a),e,f,g=k,j={};4===d?(e=a[0],f=a[1],g=a[2],j=a[3]):3===d?(e=a[0],f=a[1],j=a[2]):2===d?(e=a[0],f=a[1]):h(new J("Edge tuple "+zb(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=e in this.adj?F(this.adj[e],f,{}):{};if(!q(g))for(g=C(a);g in a;)g+=1;a=F(a,g,{});H(a,b,j);this.g(e,f,g,a)},this)};Y.prototype.add_edges_from=Y.prototype.a;
Y.prototype.q=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new J("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];q(c)?(c in d||h(new J("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),E(d,c)):E(d,Qa(d));0===C(d)&&(E(this.adj[a],b),a!=b&&E(this.adj[b],a))};Y.prototype.remove_edge=Y.prototype.q;Y.prototype.u=function(a){K(a,function(a){try{this.q(a[0],a[1],a[2])}catch(c){c instanceof J||h(c)}},this)};Y.prototype.remove_edges_from=Y.prototype.u;
Y.prototype.A=function(a,b,c){return q(c)?a in this.adj&&b in this.adj[a]&&c in this.adj[a][b]:a in this.adj&&b in this.adj[a]};Y.prototype.has_edge=Y.prototype.A;Y.prototype.p=function(a,b,c){return La(this.d(a,b,c))};Y.prototype.edges=Y.prototype.p;
Y.prototype.d=function(a,b,c){t(a)&&(t(b)&&(c=b),b=a,a=k);var d={},e,f,a=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return b?P(a,function(a){e=a[0];var b=new y,c=S(a[1]);b.next=function(){try{return c.next()}catch(a){a===x&&(d[e]=1);h(a)}};return b},function(a){f=a[0];if(!(f in d))return S(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):P(a,function(a){e=a[0];var b=new y,c=S(a[1]);b.next=function(){try{return c.next()}catch(a){a===x&&(d[e]=1);h(a)}};return b},function(a){f=
a[0];if(!(f in d))return S(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Y.prototype.edges_iter=Y.prototype.d;Y.prototype.L=function(a,b,c,d){p(d)||(d=k);return a in this.adj&&b in this.adj[a]?q(c)?F(this.adj[a][b],c,d):this.adj[a][b]:d};Y.prototype.get_edge_data=Y.prototype.L;
Y.prototype.n=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return q(b)?A(c,function(a){var c=a[0],a=a[1],f=0;B(a,function(a){B(a,function(a){f+=F(a,b,1)})});c in a&&B(a[c],function(a){f+=F(a,b,1)});return[c,f]}):A(c,function(a){var b=a[0],a=a[1],c=0;B(a,function(a){c+=C(a)});return[b,c+ +(b in a&&C(a[b]))]})};Y.prototype.degree_iter=Y.prototype.n;Y.prototype.i=da(i);Y.prototype.is_multigraph=Y.prototype.i;Y.prototype.c=da(m);Y.prototype.is_directed=Y.prototype.c;
Y.prototype.C=function(){var a=new Z;a.h(this);a.a(function(){var a,c;return P(this.t(),function(c){a=c[0];return S(c[1])},function(a){c=a[0];return S(a[1])},function(d){return[a,c,d[0],Q(d[1])]})}.call(this));a.graph=Q(this.graph);a.node=Q(this.node);return a};Y.prototype.to_directed=Y.prototype.C;
Y.prototype.U=function(a,b){var c=[];a?b?B(this.adj,function(a,b){b in a&&B(a[b],function(a,d){c.push([b,b,d,a])})}):B(this.adj,function(a,b){b in a&&B(a[b],function(a){c.push([b,b,a])})}):b?B(this.adj,function(a,b){b in a&&B(a[b],function(a,d){c.push([b,b,d])})}):B(this.adj,function(a,b){b in a&&B(a[b],function(){c.push([b,b])})});return c};Y.prototype.selfloop_edges=Y.prototype.U;Y.prototype.I=function(a,b){return!q(a)?this.size():a in this.adj&&b in this.adj[a]?C(this.adj[a][b]):0};
Y.prototype.number_of_edges=Y.prototype.I;Y.prototype.v=function(a){var a=this.b(a),b=new this.constructor,c=b.adj,d=this.adj;z(a,function(a){var b={};c[a]=b;B(d[a],function(d,j){if(j in c){var l=G(d);b[j]=l;c[j][a]=l}})});B(this.node,function(a,c){b.node[c]=a});b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.v;function Z(a,b){if(!(this instanceof Z))return new Z(a,b);W.call(this,a,b)}na(Z,W);var Fb=Z.prototype,Gb=Y.prototype,Hb;for(Hb in Gb)Gb.hasOwnProperty(Hb)&&"constructor"!==Hb&&(Fb[Hb]=Gb[Hb]);u("jsnx.classes.MultiDiGraph",Z);u("jsnx.MultiDiGraph",Z);Z.__name__="MultiDiGraph";
Z.prototype.g=function(a,b,c,d){var e,f;q(c)&&(!s(c)&&!ia(c))&&(d=c,c=k);d=d||{};"object"!==o(d)&&h(new J("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});if(b in this.succ[a]){f=this.adj[a][b];if(!q(c))for(c=C(f);c in f;)c+=1;e=F(f,c,{});H(e,d);f[c]=e}else q(c)||(c=0),e={},H(e,d),f=Ua(c,e),this.succ[a][b]=f,this.pred[b][a]=f};Z.prototype.add_edge=Z.prototype.g;
Z.prototype.q=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new J("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];q(c)?(c in d||h(new J("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),E(d,c)):E(d,Qa(d));0===C(d)&&(E(this.succ[a],b),E(this.pred[b],a))};Z.prototype.remove_edge=Z.prototype.q;
Z.prototype.d=function(a,b,c){t(a)&&(t(b)&&(c=b),b=a,a=k);var d,e,a=q(a)?L(this.b(a),function(a){return[a,this.adj[a]]},this):xb(this.adj);return b?P(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):P(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};Z.prototype.edges_iter=Z.prototype.d;Z.prototype.Y=Z.prototype.d;Z.prototype.out_edges_iter=Z.prototype.Y;
Z.prototype.ca=function(a,b,c){return La(this.Y(a,b,c))};Z.prototype.out_edges=Z.prototype.ca;Z.prototype.B=function(a,b,c){t(a)&&(b=a,a=k);var d,e,a=q?L(this.b(a),function(a){return[a,this.pred[a]]},this):xb(this.pred);return b?P(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):P(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};Z.prototype.in_edges_iter=Z.prototype.B;
Z.prototype.N=function(a,b,c){return La(this.B(a,b,c))};Z.prototype.in_edges=Z.prototype.N;
Z.prototype.n=function(a,b){var c;c=q(a)?sb(A(this.b(a),function(a){return[a,this.succ[a]]},this),A(this.b(a),function(a){return[a,this.pred[a]]},this)):sb(S(this.succ),S(this.pred));return q(b)?L(c,function(a){var c=a[0][1],f=0;B(a[1][1],function(a){B(a,function(a){f+=+F(a,b,1)})});B(c,function(a){B(a,function(a){f+=+F(a,b,1)})});return[a[0][0],f]}):L(c,function(a){var b=0,c=0;B(a[1][1],function(a){b+=qb(a)});B(a[0][1],function(a){c+=qb(a)});return[a[0][0],b+c]})};Z.prototype.degree_iter=Z.prototype.n;
Z.prototype.M=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.pred[a]]},this):S(this.pred);return q(b)?L(c,function(a){var c=0;B(a[1],function(a){B(a,function(a){c+=+F(a,b,1)})});return[a[0][0],c]}):L(c,function(a){var b=0;B(a[1],function(a){b+=C(a)});return[a[0],b]})};Z.prototype.in_degree_iter=Z.prototype.M;
Z.prototype.S=function(a,b){var c;c=q(a)?L(this.b(a),function(a){return[a,this.succ[a]]},this):S(this.succ);return q(b)?L(c,function(a){var c=0;B(a[1],function(a){B(a,function(a){c+=+F(a,b,1)})});return[a[0][0],c]}):L(c,function(a){var b=0;B(a[1],function(a){b+=C(a)});return[a[0],b]})};Z.prototype.out_degree_iter=Z.prototype.S;Z.prototype.i=da(i);Z.prototype.is_multigraph=Z.prototype.i;Z.prototype.c=da(i);Z.prototype.is_directed=Z.prototype.c;Z.prototype.C=function(){return yb(this)};
Z.prototype.to_directed=Z.prototype.C;Z.prototype.V=function(a){var b=new Y;b.name(this.name());b.h(this);var c=this,d,e;a?b.a(P(this.t(),function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){if(c.A(e,d,a[0]))return[d,e,a[0],Q(a[1])]})):b.a(P(this.t(),function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return[d,e,a[0],Q(a[1])]}));b.graph=Q(this.graph);b.node=Q(this.node);return b};Z.prototype.to_undirected=Z.prototype.V;
Z.prototype.v=function(a){var a=this.b(a),b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;z(a,function(a){c[a]={};d[a]={}});K(c,function(a){var b=c[a];B(e[a],function(e,l){if(l in c){var O=G(e);b[l]=O;d[l][a]=O}})});K(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.v;
Z.prototype.reverse=function(a){(a=!p(a)||a)?(a=new this.constructor(k,{name:"Reverse of ("+this.name()+")"}),a.h(this),a.a(A(this.d(i,i),function(a){return[a[1],a[0],a[2],Q(a[3])]})),a.graph=Q(this.graph),a.node=Q(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Z.prototype.reverse=Z.prototype.reverse;u("jsnx.nodes",function(a){return a.nodes()});u("jsnx.nodes_iter",function(a){return a.H()});u("jsnx.edges",function(a,b){return a.p(b)});u("jsnx.edges_iter",function(a,b){return a.d(b)});u("jsnx.degree",function(a,b,c){return a.F(b,c)});u("jsnx.neighbors",function(a,b){return a.Q(b)});u("jsnx.number_of_nodes",function(a){return a.R()});u("jsnx.number_of_edges",function(a){return a.I()});u("jsnx.density",function(a){var b=a.R(),c=a.I();return 0===c?0:a.c()?c/(b*(b-1)):2*c/(b*(b-1))});
u("jsnx.degree_histogram",function(a){var a=Ra(a.F()),b=Math.max.apply(Math,a)+1,c=Ea(b);ra(a,function(a){c[a]+=1});return c});u("jsnx.is_directed",function(a){return a.c()});u("jsnx.freeze",function(a){function b(){h(new J("Frozen graph can't be modified"))}a.D=b;a.h=b;a.J=b;a.T=b;a.g=b;a.a=b;a.q=b;a.u=b;a.clear=b;a.va=i;return a});u("jsnx.is_frozen",function(a){return!!a.va});u("jsnx.subgraph",function(a,b){return a.v(b)});
u("jsnx.create_empty_copy",function(a,b){p(b)||(b=i);var c=new a.constructor;b&&c.h(a);return c});
u("jsnx.info",function(a,b){var c="";if(q(b))a.l(b)||h(new J("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.F(b)+"\n"),c+="Neighbors: "+a.Q(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.R()+"\n"),c=c+("Number of edges: "+a.I()+"\n"),d=a.R();if(0<d)if(a.c())c+="Average in degree: "+(T.o.apply(k,Ra(a.ga()))/d).toFixed(4)+"\n",c+="Average out degree: "+(T.o.apply(k,Ra(a.ja()))/d).toFixed(4);
else var e=T.o.apply(k,Ra(a.F())),c=c+("Average degree: "+(e/d).toFixed(4))}return c});u("jsnx.set_node_attributes",function(a,b,c){B(c,function(c,e){a.ba[e][b]=c})});function Ib(a,b){var c={};B(a.ba,function(a,e){b in a&&(c[e]=a[b])});return c}u("jsnx.get_node_attributes",Ib);u("jsnx.set_edge_attributes",function(a,b,c){B(c,function(b,c){c=c.split(",");a.m(c[0])[c[1]]=b})});Ib=function(a,b){var c={};B(a.p(i),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};
u("jsnx.get_edge_attributes",{}.Oa);var Jb={};function Lb(a,b){if("eg"===b)return Mb(a);if(!q(b)||"hh"===b)return Pb(a);h(new gb("`opt_method` must be 'eg' or 'hh'"))}u("jsnx.is_valid_degree_sequence",Lb);function Pb(a){if(0===a.length)return i;if(!Oa(a)||0>Math.min.apply(k,a)||0!==T.o.apply(k,a)%2)return m;for(a=ya(a);0<a.length;){v.sort.call(a,Aa);if(0>a[0])break;var b=a.pop();if(0===b)return i;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return m}u("jsnx.is_valid_degree_sequence_havel_hakimi",Pb);
function Mb(a){if(0===a.length)return i;if(!Oa(a)||0>Math.min.apply(k,a)||0!==T.o.apply(k,a)%2)return m;var b=a.length,c=ya(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=T.o.apply(k,c.slice(0,d[e])),g=d[e]*(d[e]-1)+T.o.apply(k,La(A(N(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return m;return i}u("jsnx.is_valid_degree_sequence_erdos_gallai",Mb);u("jsnx.triangles",function(a,b){a.c()&&h(new J("triangles() is not defined for directed graphs."));if(a.l(b))return Math.floor(Qb(a,b).next()[2]/2);var c={};z(Qb(a,b),function(a){c[a[0]]=Math.floor(a[2]/2)});return c});
function Qb(a,b){a.i()&&h(new J("Not defined for multigraphs."));var c;c=q(b)?P(a.b(b),function(b){return[b,a.m(b)]}):S(a.adj);return A(c,function(b){var c=new I(D(b[1])),f=0;c.remove(b[0]);z(c,function(b){var d=new I(D(a.m(b)));d.remove(b);f+=$a(c,d).z()});return[b[0],c.z(),f]})}
function Rb(a,b,c){a.i()&&h(new J("Not defined for multigraphs."));p(c)||(c="weight");var d;d=0===a.p().length?1:tb(a.p(i),function(a){return F(a[2],c,1)});b=q(b)?P(a.b(b),function(b){return[b,a.m(b)]}):S(a.adj);return A(b,function(b){var f=b[0],g=new I(D(b[1]));g.remove(f);var j=0,l=new I;z(g,function(b){var e=F(a.m(f)[b],c,1)/d;l.add(b);var ga=ab(new I(D(a.m(b))),l);z($a(g,ga),function(g){var l=F(a.m(b)[g],c,1)/d,g=F(a.m(f)[g],c,1)/d;j+=Math.pow(e*l*g,1/3)})});return[f,g.z(),2*j]})}
u("jsnx.average_clustering",function(a,b,c,d){2===arguments.length?s(b)?(c=b,b=k):t(b)&&(d=b,b=k):3===arguments.length&&t(c)&&(d=c,c=k);q(c)||(c=k);q(d)||(d=i);var e=Ra(Sb(a,b,c));d||(e=sa(e,function(a){return a>0}));return T.o.apply(T,e)/e.length});function Sb(a,b,c){a.c()&&h(new J("Clustering algorithms are not defined for directed graphs."));var c=q(c)?Rb(a,b,c):Qb(a,b),d={};z(c,function(a){d[a[0]]=0===a[2]?0:a[2]/(a[1]*(a[1]-1))});return a.l(b)?Ra(d)[0]:d}u("jsnx.clustering",Sb);
u("jsnx.transitivity",function(a){var b=0,c=0;z(Qb(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c});u("jsnx.square_clustering",function(a,b){var c=!q(b)?a:a.b(b),d={};z(c,function(b){var c=d[b]=0;z(ub(D(a.m(b))),function(g){var j=g[0],g=g[1],l=$a(new I(D(a.m(j))),D(a.m(g)));l.remove(b);l=l.z();d[b]+=l;var O=l+1,R=a.m(j);g in R&&(O+=1);c+=(C(a.m(j))-O)*(C(a.m(g))-O)+l});0<c&&(d[b]/=c)});return a.l(b)?Ra(d)[0]:d});var Tb,Ub=k,Vb="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
u("jsnx.draw",function(a,b,c){function d(){pa.e.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",aa,")"].join("")});mb()}t(b)&&(c=b,b=k);var b=b||Ub||{},e=b.d3||window.d3,f={};wb(f,Wb,b);Ub=b;e||h(Error("D3 requried for draw()"));!q(f.element)&&!q(Tb)&&h(Error("Output element required for draw()"));Tb=F(f,"element",Tb);e.select(Tb).select("svg.jsnx").remove();var g=e.select(Tb),j=g.append("svg").classed("jsnx",i).attr("pointer-events","all"),l=j.append("g"),b=l.append("g").classed("edges",
i).selectAll("g.edge"),O=l.append("g").classed("nodes",i).selectAll("g.node"),R=e.layout.force(),ga=f.width||parseInt(g.style("width"),10),$=f.height||parseInt(g.style("height"),10),Kb=f.layout_attr,g=f.nodelist||k,V,ba,X,Nb=a.c(),qa=f.weighted,pa={e:O,f:b};if(f.with_labels){var ta=f.labels;V="object"===o(ta)?function(a){return F(ta,a.node,"")}:ja(ta)?ta:s(ta)?function(a){return a.data[ta]}:function(a){return a.node}}f.labels=V;if(qa){var Ba=f.weights;X="object"===o(Ba)?function(a){return F(Ba,a.node,
1)}:ja(Ba)?Ba:s(Ba)?function(a){return F(a.data,Ba,1)}:da(1)}if(f.with_edge_labels){var Ca=f.edge_labels;ba=qa&&!p(Ca)?X:"object"===o(Ca)?function(a){return F(ta,a.node,"")}:ja(Ca)?Ca:s(Ca)?function(a){return a.data[Ca]}:function(a){return a.edge};f.edge_labels=ba}if(qa&&f.weighted_stroke){var qa=Ja(a.d(i),function(a,b){b=X({data:b[2]});return a>b?a:b},0),lc=e.scale.linear().range([1,f.edge_style["stroke-width"]]).domain([0,qa]);f.edge_style["stroke-width"]=function(a){return lc(X.call(this,a))}}j.select("svg.jsnx").remove();
j.attr("width",ga+"px").attr("height",$+"px").style("opacity",1.0E-6).transition().duration(1E3).style("opacity",1);var mc={size:i,nodes:i,links:i,start:i};K(Kb,function(a){if(!(a in mc))R[a](Kb[a])});R.nodes([]).links([]).size([ga,$]);var Ga=1,aa=1;if(f.pan_zoom.enabled){var Ob=f.pan_zoom.scale,Da=f.edge_style["stroke-width"];ja(Da)?f.edge_style["stroke-width"]=function(){var a=Da.apply(this,arguments);return aa*(+a||parseInt(a,10))}:(Da=+Da||parseInt(Da,10),f.edge_style["stroke-width"]=function(){return aa*
Da});(function(){var a=m,b=1,c=Ga;j.call(e.behavior.zoom().on("zoom",function(){var g=e.event.sourceEvent.shiftKey;if((g=Ob&&g||!(Ob||g))&&!a){b=e.event.scale;c=Ga;a=i}else!g&&a&&(a=m);Ga=g?c*(e.event.scale/b):Ga;aa=!g?Ga/e.event.scale:aa;g=e.event.translate;l.attr("transform","translate("+g[0]+","+g[1]+")scale("+e.event.scale+")");l.selectAll("g.edge > .line").style("stroke-width",f.edge_style["stroke-width"]);d()}))})()}var mb=fa;if(Nb){j.append("defs").append("marker").attr("id","Triangle").attr("markerUnits",
"strokeWidth").attr("refX","7").attr("refY","5").attr("viewBox","0 0 10 10").attr("orient","auto").append("path").attr("d","M 0 0 L 10 5 L 0 10 z");f.edge_attr["marker-end"]="url(#Triangle)";f.edge_style.fill="none";var Xa=f.layout_attr.linkDistance,Ha=f.edge_offset;ja(Xa)||(Xa=function(){return f.layout_attr.linkDistance});ha(Ha)&&(Ha=function(){return f.edge_offset});ia(Ha)&&(Ha=function(){return[f.edge_offset,f.edge_offset]});mb=function(){pa.f.each(function(a){if(a.source!==a.target){var b=e.select(this),
c=a.source.x,d=a.source.y,f=a.target.x,g=a.target.y,j=T.ea(c,d,f,g),f=Math.sqrt(Math.pow(f-c,2)+Math.pow(g-d,2)),g=Ha(a),g=[g[0]*aa,g[1]*aa];b.attr("transform",["translate(",c,",",d,")rotate(",j,")"].join(""));if(c=a.G.A(a.target.node,a.source.node)){var d=Xa(a)/3,j=-d/(f/2),l=j*f;b.select(".line").attr("d",["M",g[0],j*g[0],"Q",f/2,-d,f-g[1],-j*(f-g[1])+l].join(" "))}else b.select(".line").attr("d",["M",g[0],"0 L",f-g[1],0].join(" "));g=1/aa;b.select("text").attr("x",f*g/2).attr("y",c?g*(-Xa(a)/4):
0).attr("transform","scale("+aa+")")}})}}else mb=function(){pa.f.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,j=a.target.y,a=T.ea(c,d,g,j),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(j-d,2)),j=g/2;b.attr("transform",["translate(",c,",",d,")rotate(",a,")"].join(""));b.select(".line").attr("d",["M 0 0 L",g,"0"].join(" "));f.with_edge_labels&&b.select("text").attr("x",j*(1/aa)).attr("y",0).attr("transform","scale("+aa+")"+(a>90&&a<279?"rotate(180,"+j*
(1/aa)+",0)":""))}})};R.on("tick",d);ga=a.H();$=a.d();g&&(c=m,ga=a.b(g),$=a.d(g));pa.e=Xb(a,ga,R,O,f.node_shape,V);pa.f=Yb(a,$,R,b,ba);Zb(pa.e,{attr:f.node_attr,style:f.node_style,P:f.label_style,O:f.label_attr},f.with_labels);$b(pa.f,{attr:f.edge_attr,style:f.edge_style,P:f.edge_label_style,O:f.edge_label_attr},f.with_edge_labels,k,Nb);c?ac(a,R,f,pa):a.bound?bc(a):cc(a);R.start();return R});
function Xb(a,b,c,d,e,f){var g=c.nodes();K(b,function(b){var c=a.node[b],b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,dc);b=d.enter().append("g").classed("node",i).call(c.drag);b.append(e).classed("node-shape",i);f&&b.append("text").text(f);return d}
function Yb(a,b,c,d,e){var f=c.links();K(b,function(b){var c=b[0],d=b[1],b=b[2]||a.L(c,d),c={edge:[c,d],redge:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,ec);b=d.enter().append("g").classed("edge",i);b.append("path").classed("line",i);e&&b.append("text").text(e);return d}
function Zb(a,b,c,d){if(q(d)){var e={};K(d,function(a){e[r(a)?a[0]:a]=i});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");B(b.attr,function(a,b){f.attr(b,a)});B(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");B(b.O,function(a,b){g.attr(b,a)});B(b.P,function(a,b){g.style(b,a)})}}
function $b(a,b,c,d,e){if(q(d)){var f={};K(d,function(a){f[[a[0],a[1]]]=i});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");B(b.attr,function(a,b){g.attr(b,a)});B(b.style,function(a,b){g.style(b,a)});if(c){var j=a.selectAll("text");B(b.O,function(a,b){j.attr(b,a)});B(b.P,function(a,b){j.style(b,a)})}}function dc(a){return a.node}function ec(a){return a.edge}
function fc(a,b,c,d){var e=c.nodes();K(a.b(b),function(b){wa(e,a.node[b].__d3datum__)});d=d.data(e,dc);d.exit().remove();return d}function gc(a,b,c,d){var e=c.links();K(b,function(b){wa(e,F(a.L(b[0],b[1],{}),"__d3datum__",k))});d=d.data(e,ec);d.exit().remove();return d}
function ac(a,b,c,d){bc(a,m);var e=a.constructor.prototype,f=c.node_shape,g={attr:c.node_attr,style:c.node_style,O:c.label_attr,P:c.label_style},j={attr:c.edge_attr,style:c.edge_style,O:c.edge_label_attr,P:c.edge_label_style},l=c.labels,O=c.edge_labels,R=c.with_labels,ga=c.with_edge_labels,$=a.c();a.add_node=a.D=function(a){var c=!this.l(a);e.add_node.apply(this,arguments);c&&(d.e=Xb(this,[a],b,d.e,f,l));Zb(d.e,g,R,[a]);b.start()};a.add_nodes_from=a.h=function(a){var c=sa(M(a),function(a){return!this.l(r(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.e=Xb(this,c,b,d.e,f,l));Zb(d.e,g,R,a);b.start()};a.add_edge=a.g=function(c,V){var ba=!this.A(c,V),X=[];ba&&(X=sa(c==V?[c]:[c,V],function(a){return!this.l(a)},this));e.add_edge.apply(a,arguments);0<X.length&&(d.e=Xb(this,X,b,d.e,f,l),Zb(d.e,g,R,X));ba&&(d.f=Yb(this,[[c,V]],b,d.f,O));$b(d.f,j,ga,[[c,V]],$);b.start()};a.add_edges_from=a.a=function(c){var V=[],ba=[],X={},$={},qa=this.c();K(c,function(a){var b=a[0],a=a[1];if(!this.A(b,
a)&&!([b,a]in X)&&(qa||!([a,b]in X)))if(V.push([b,a]),X[[b,a]]=i,!this.l(b)&&!(b in $)&&(ba.push(b),$[b]=i),!this.l(a)&&!(a in $))ba.push(a),$[a]=i},this);e.add_edges_from.apply(a,arguments);0<ba.length&&(d.e=Xb(this,ba,b,d.e,f,l),Zb(d.e,g,R,ba));0<V.length&&(d.f=Yb(this,V,b,d.f,O));$b(d.f,j,ga,V,qa);b.start()};a.remove_node=a.J=function(c){try{if(this.l(c)){d.e=fc(this,[c],b,d.e);var f=this.d([c]);this.c()&&(f=Ka(f,this.B([c])));d.f=gc(this,f,b,d.f);b.resume()}}catch(g){}e.remove_node.apply(a,arguments)};
a.remove_nodes_from=a.T=function(c){try{d.e=fc(this,c,b,d.e);var f=this.d(c);this.c()&&(f=Ka(f,this.B(c)));d.f=gc(this,f,b,d.f);b.resume()}catch(g){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.q=function(c,f){try{d.f=gc(this,[[c,f]],b,d.f),b.resume()}catch(g){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.u=function(c){try{d.f=gc(this,c,b,d.f),b.resume()}catch(f){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.e=d.e.data([],dc);d.e.exit().remove();d.f=d.f.data([],
ec);d.f.exit().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=i}u("jsnx.is_bound",function(a){return a.bound});function bc(a,b){if(a.bound){var c=a.constructor.prototype;ra(Vb,function(b){a[b]=c[b]});delete a.bound;(!p(b)||b)&&cc(a)}}u("jsnx.unbind",bc);function cc(a){K(a.H(i),function(a){E(a[1],"__d3datum__")});K(a.d(i),function(a){E(a[2],"__d3datum__")})}
var Wb={layout_attr:{charge:-120,linkDistance:40},node_shape:"circle",node_attr:{r:10},node_style:{stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{stroke:"#000","stroke-width":2},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","dominant-baseline":"central","text-anchor":"middle","-webkit-user-select":"none"},with_labels:m,with_edge_labels:m,
edge_offset:10,weighted:m,weights:"weight",weighted_stroke:i,pan_zoom:{enabled:i,scale:i}};function hc(a,b){var c=ic(a,b);c.name("complete_graph("+a+")");1<a&&c.a(c.c()?vb(N(a)):ub(N(a)));return c}u("jsnx.complete_graph",hc);u("jsnx.cycle_graph",function(a,b){var c=jc(a,b);c.name("cycle_graph("+a+")");1<a&&c.g(a-1,0);return c});function ic(a,b){a instanceof U&&(b=a,a=k);q(a)||(a=0);var c;q(b)?(c=b,c.clear()):c=new U;c.h(N(a));c.name("empty_graph("+a+")");return c}u("jsnx.empty_graph",ic);u("jsnx.null_graph",function(a){a=ic(0,a);a.name("null_graph()");return a});
function jc(a,b){var c=ic(a,b);c.name("path_graph("+a+")");c.a(A(N(a-1),function(a){return[a,a+1]}));return c}u("jsnx.path_graph",jc);u("jsnx.trivial_graph",function(a){a=ic(1,a);a.name("null_graph()");return a});u("jsnx.fast_gnp_random_graph",function(a,b,c){q(c)||(c=m);var d=ic(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return kc(a,b,c);var e=1,f=-1,b=Math.log(1-b);if(c)for(d=W(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.g(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.g(e,f)}return d});
function kc(a,b,c){var d;d=c?W():U();d.h(N(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return hc(a,d);a=d.c()?vb(N(a)):ub(N(a));z(a,function(a){Math.random()<b&&d.g(a[0],a[1])});return d}u("jsnx.gnp_random_graph",kc);u("jsnx.binomial_graph",kc);u("jsnx.erdos_renyi_graph",kc);u("jsnx.havel_hakimi_graph",function(a,b){Lb(a)||h(new J("Invalid degree sequence"));q(b)&&(b.c()&&h(new J("Directed Graph not supported")),b.i()&&h(new J("Havel-Hakimi requires simple graph")));var c=a.length,d=ic(c,b);if(0===c||0===Math.max.apply(k,a))return d;for(c=La(A(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return m;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return m;for(var f=c.length,g=f-e[0];g<f;g++)d.g(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.ia()+" nodes "+d.size()+" edges");return d});function nc(a,b,c){var d=b;ja(b)&&(d={},z(a.H(),function(a){d[a]=b(a)}));return!p(c)||c?oc(a,d):pc(a,d)}u("jsnx.relabel_nodes",nc);
function pc(a,b){var c=new I(D(b)),d;if(0<$a(c,b).z()){c=W(xb(b));c.u(c.U());try{d=Jb.Na.Za(c)}catch(e){e instanceof jb&&h(new jb("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True."))}d.reverse()}else d=c;var f=a.i(),g=a.c(),j;z(d,function(c){var d;c in b&&(d=b[c],a.l(c)||h(new J("Node "+c+" is not in the graph.")),a.D(d,a.node[c]),f?(j=w(a.p(c,i,i),function(a){return[d,a[1],a[2],a[3]]}),g&&(j=xa(j,w(a.N(c,i,i),function(a){return[a[0],d,a[2],a[3]]})))):(j=
w(a.p(c,i),function(a){return[d,a[1],a[2]]}),g&&(j=xa(j,w(a.N(c,i),function(a){return[a[0],d,a[2]]})))),a.J(c),a.a(j))});return a}function oc(a,b){var c=new a.constructor;c.name("("+a.name()+")");a.i()?c.a(A(a.d(i,i),function(a){return[F(b,a[0],a[0]),F(b,a[1],a[1]),a[2],G(a[3])]})):c.a(A(a.d(i),function(a){return[F(b,a[0],a[0]),F(b,a[1],a[1]),G(a[2])]}));c.h(A(a,function(a){return F(b,a,a)}));var d={},e;for(e in a.node)d[F(b,e,e)]=G(a.node[e]);H(c.node,d);H(c.graph,G(a.graph));return c}
u("jsnx.convert_node_labels_to_integers",function(a,b,c,d){3===arguments.length&&t(c)?(d=c,c=k):2===arguments.length&&(t(b)?(d=b,b=k):s(b)&&(c=b,b=k));q(b)||(b=0);q(c)||(c="default");q(d)||(d=i);var e={},f,g,j,l;if("default"===c){f=a.nodes();g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g]]=j}else if("sorted"===c){f=a.nodes();f.sort();g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g]]=j}else if("increasing degree"===c){f=La(a.n());f.sort(function(a,b){return a[1]-b[1]});g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g][0]]=
j}else if("decreasing degree"===c){f=La(a.n());f.sort(function(a,b){return b[1]-a[1]});g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g][0]]=j}else h(new J("Unkown node ordering: "+c));g=nc(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g});}());
