(function(){function g(a){throw a;}var h=void 0,j=!0,k=null,l=!1;function m(a){return function(){return a}}var n,aa=this;function ba(){}
function o(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){return a!==h}function q(a){return a!=k}function s(a){return"array"==o(a)}function t(a){var b=o(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function v(a){return"boolean"==typeof a}function ca(a){return"function"==o(a)}function ga(a){var b=typeof a;return"object"==b&&a!=k||"function"==b}
var ha="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ia=0;function w(a,b){var c=a.split("."),d=aa;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function x(a,b){function c(){}c.prototype=b.prototype;a.Ba=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ja={};var y=Array.prototype,la=y.indexOf?function(a,b,c){return y.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ma=y.forEach?function(a,b,c){y.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},na=y.filter?function(a,b,c){return y.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,i=u(a)?
a.split(""):a,r=0;r<d;r++)if(r in i){var A=i[r];b.call(c,A,r,a)&&(e[f++]=A)}return e},oa=y.map?function(a,b,c){return y.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,i=0;i<d;i++)i in f&&(e[i]=b.call(c,f[i],i,a));return e};function ra(a,b){if(a.reduce)return a.reduce(b,0);var c=0;ma(a,function(d,e){c=b.call(h,c,d,e,a)});return c}
function sa(a,b){var c;a:{c=a.length;for(var d=u(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(h,d[e],e,a)){c=e;break a}c=-1}return 0>c?k:u(a)?a.charAt(c):a[c]}function ta(a){return y.concat.apply(y,arguments)}function ua(a){if(s(a))return ta(a);for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}function va(a,b,c){return 2>=arguments.length?y.slice.call(a,b):y.slice.call(a,b,c)}function wa(a){for(var b=[],c=0;c<a;c++)b[c]=0;return b}
function xa(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var z="StopIteration"in aa?aa.StopIteration:Error("StopIteration");function B(){}B.prototype.next=function(){g(z)};B.prototype.p=function(){return this};function ya(a){if(a instanceof B)return a;if("function"==typeof a.p)return a.p(l);if(t(a)){var b=0,c=new B;c.next=function(){for(;;){b>=a.length&&g(z);if(b in a)return a[b++];b++}};return c}g(Error("Not implemented"))}
function Aa(a,b,c){if(t(a))try{ma(a,b,c)}catch(d){d!==z&&g(d)}else{a=ya(a);try{for(;;)b.call(c,a.next(),h,a)}catch(e){e!==z&&g(e)}}}function Ba(a,b,c){var a=ya(a),d=new B;d.next=function(){for(;;){var d=a.next();return b.call(c,d,h,a)}};return d}function Ca(a,b,c){var d=c;Aa(a,function(a){d=b.call(h,d,a)});return d}function Da(a){var b=arguments,c=b.length,d=0,e=new B;e.next=function(){try{return d>=c&&g(z),ya(b[d]).next()}catch(a){return(a!==z||d>=c)&&g(a),d++,this.next()}};return e}
function Ea(a){if(t(a))return s(a)?ta(a):ua(a);var a=ya(a),b=[];Aa(a,function(a){b.push(a)});return b};function C(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Fa(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function D(a){var b=0,c;for(c in a)b++;return b}function Ga(a){for(var b in a)return b}function Ha(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function E(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Ia(a){for(var b in a)delete a[b]}function G(a,b){b in a&&delete a[b]}function H(a,b,c){return b in a?a[b]:c}
function Ja(a){var b={},c;for(c in a)b[c]=a[c];return b}var Ka="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function I(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ka.length;f++)c=Ka[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function Na(a){var b=arguments.length;if(1==b&&s(arguments[0]))return Na.apply(k,arguments[0]);b%2&&g(Error("Uneven number of arguments"));for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function Oa(a){return Ca(J(a),function(a,c){a[c[0]]=c[1];return a},{})}function Pa(a){return a instanceof B||ca(a.p)}function Qa(a){if(u(a)||t(a)||"length"in a)return a.length;if(Ra(a))return D(a);g(new TypeError)}function L(a,b,c,d){v(c)&&(d=c,c=k);if(d)var e=b,b=function(a){e.apply(this,a)};Pa(a)?Aa(a,b,c):t(a)||u(a)?ma(a,b,c):ga(a)&&L(E(a),b,c)}w("jsnx.forEach",L);function M(a,b,c){if(t(a))return oa(a,b,c);if(Pa(a))return Ba(a,b,c);if(ga(a))return Fa(a,b,c);g(new TypeError)}
function Sa(){var a=arguments,b=a[0];if(t(b))return xa.apply(k,a);if(Pa(b)){var b=new B,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(ga(b))return xa.apply(k,oa(a,E));g(new TypeError)}
function Ta(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!p(a[c])||"object"!==o(a[c])?a[c]=O(d[c]):"object"===o(a[c])&&"object"===o(d)&&Ta(a[c],d[c]);for(var f=0;f<Ka.length;f++)c=Ka[f],Object.prototype.hasOwnProperty.call(d,c)&&(!p(a[c])||"object"!==o(a[c])?a[c]=O(d[c]):"object"===o(a[c])&&"object"===o(d)&&Ta(a[c],d[c]))}}function R(a){if(t(a))return s(a)?ta(a):ua(a);if(Pa(a))return Ea(a);if(ga(a))return E(a);g(new TypeError)}w("jsnx.toArray",R);
function Ua(a){var b=[];C(a,function(a,d){b.push([d,a])});return b}function S(a){var b=new B,c=ya(E(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function J(a){"object"===o(a)&&!t(a)&&!Pa(a)&&(a=E(a));return ya(a)}
function T(a){var b=new B,c=va(arguments,1);if(0===c.length)return a;try{a=ya(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&g(new TypeError)},b}var e=k;b.next=function(){var d,i;try{for(;!p(d);)d=e.next()}catch(r){for(;!p(i)||!p(d);)i=a.next(),d=c[0](i);if(Pa(d))return e=T.apply(k,ta([d],va(c,1))),b.next();e=k}return d};return b}w("jsnx.sentinelIterator",function(a,b){var c=new B;c.next=function(){var c;try{c=ya(a).next()}catch(e){e!=z&&g(e),c=b}return c};return c});
function Ra(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==o(a)||a.nodeType||a==a.window)return l;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return l}catch(c){return l}for(var d in a);return d===h||b.call(a,d)}
function O(a,b){var b=b||[],c=o(a);if("object"==c&&Ra(a)||"array"==c){var d=sa(b,function(b){return a===b[0]});if(d!==k)return d[1];if(a.Y)return d=[a,a.Y()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var e in a)c[e]=O(a[e],b);return c}return a}function Va(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=O(c);a=new b;for(d in c)a[d]=c[d];return a};function Ya(a){a%=360;return 0>360*a?a+360:a}function Za(a){return ra(arguments,function(a,c){return a+c})};var $a,ab=k,bb="add_node,add_nodes_from,add_edge,add_edges_from,remove_node,remove_nodes_from,remove_edge,remove_edges_from,clear".split(",");
w("jsnx.draw",function(a,b,c){v(b)&&(c=b,b=k);var b=b||ab||{},d=b.d3||window.d3,e={};Ta(e,cb,b);ab=b;d||g(Error("D3 requried for draw()"));!q(e.element)&&!q($a)&&g(Error("Output element required for draw()"));$a=H(e,"element",$a);d.select($a).select("svg.jsnx").remove();var f=d.select($a),i=f.append("svg").classed("jsnx",j).attr("pointer-events","all"),r=i;e.with_zoom&&(r=i.call(d.behavior.zoom().on("zoom",function(){var a=d.event.translate;r.attr("transform","translate("+a[0]+","+a[1]+")scale("+
d.event.scale+")")})).append("g"));var b=r.append("g").classed("edges",j).selectAll(".edge"),A=r.append("g").classed("edge_labels",j).selectAll("text"),da=r.append("g").classed("nodes",j).selectAll("g.node"),P=d.layout.force(),ea=e.width||parseInt(f.style("width"),10),La=e.height||parseInt(f.style("height"),10),rb=e.layout_attr,N=e.nodelist||k,F,Q,Z,f=a.g(),fa=e.weighted,K={c:da,e:b,d:A};if(e.with_labels){var ka=e.labels;F="object"===o(ka)?function(a){return H(ka,a.node,"")}:ca(ka)?ka:u(ka)?function(a){return a.data[ka]}:
function(a){return a.node}}e.labels=F;if(fa){var pa=e.weights;Z="object"===o(pa)?function(a){return H(pa,a.node,1)}:ca(pa)?pa:u(pa)?function(a){return H(a.data,pa,1)}:m(1)}if(e.with_edge_labels){var qa=e.edge_labels;Q=fa&&!p(qa)?Z:"object"===o(qa)?function(a){return H(ka,a.node,"")}:ca(qa)?qa:u(qa)?function(a){return a.data[qa]}:function(a){return a.edge};e.edge_labels=Q}if(fa&&e.weighted_stroke){var fa=Ca(a.f(j),function(a,b){b=Z({data:b[2]});return a>b?a:b},0),Hb=d.scale.linear().range([1,e.edge_style["stroke-width"]]).domain([0,
fa]);e.edge_style["stroke-width"]=function(a){return Hb(Z.call(this,a))}}i.select("svg.jsnx").remove();i.attr("width",ea+"px").attr("height",La+"px").style("opacity",1.0E-6).transition().duration(1E3).style("opacity",1);var Ib={size:j,nodes:j,links:j,start:j};L(rb,function(a){if(!(a in Ib))P[a](rb[a])});P.nodes([]).links([]).size([ea,La]);var Wa=ba,Xa=ba;if(f){i.append("defs").append("marker").attr("id","Triangle").attr("markerUnits","strokeWidth").attr("refX","7").attr("refY","5").attr("viewBox",
"0 0 10 10").attr("orient","auto").append("path").attr("d","M 0 0 L 10 5 L 0 10 z");e.edge_attr["marker-end"]="url(#Triangle)";e.edge_style.fill="none";var Ma=e.layout_attr.linkDistance,za=e.edge_offset;ca(Ma)||(Ma=function(){return e.layout_attr.linkDistance});s(za)&&(za=function(){return e.edge_offset});"number"==typeof za&&(za=function(){return[e.edge_offset,e.edge_offset]});Wa=function(){K.e.attr("d",function(b){if(b.source!==b.target){var c=Math.sqrt(Math.pow(b.target.x-b.source.x,2)+Math.pow(b.target.y-
b.source.y,2)),d=za(b);if(a.s(b.target.node,b.source.node)){var b=Ma(b)/3,e=-b/(c/2);return["M",d[0],e*d[0],"Q",c/2,-b,c-d[1],-e*(c-d[1])+e*c].join(" ")}return["M",d[0],"0 L",c-d[1],0].join(" ")}}).attr("transform",function(a){if(a.source!==a.target){var b=a.source.x,c=a.source.y;return["translate(",b,",",c,")rotate(",Ya(Math.atan2(a.target.y-c,a.target.x-b)*180/Math.PI),")"].join("")}})};e.with_edge_labels&&(Xa=function(){K.d.attr("x",function(a){return Math.sqrt(Math.pow(a.target.x-a.source.x,2)+
Math.pow(a.target.y-a.source.y,2))/2}).attr("y",function(b){return a.s(b.target.node,b.source.node)?-Ma(b)/3:-2}).attr("transform",function(a){var b=a.source.x,c=a.source.y;return["translate(",b,",",c,")rotate(",Ya(Math.atan2(a.target.y-c,a.target.x-b)*180/Math.PI),")"].join("")})})}else Wa=function(){K.e.attr("d",function(a){var b=[(a.source.x+a.target.x)/2,(a.source.y+a.target.y)/2];return["M",a.source.x,a.source.y,"L",b[0],b[1],"L",a.target.x,a.target.y].join(" ")})},e.with_edge_labels&&(Xa=function(){K.d.attr("x",
function(a){return(a.source.x+a.target.x)/2}).attr("y",function(a){return-2+(a.source.y+a.target.y)/2}).attr("transform",function(a){var b=[(a.source.x+a.target.x)/2,(a.source.y+a.target.y)/2],a=Ya(Math.atan2(a.target.y-a.source.y,a.target.x-a.source.x)*180/Math.PI);a>90&&a<279&&(a=a+180);return["rotate(",a,",",b[0],",",b[1],")"].join("")})});P.on("tick",function(){K.c.attr("transform",function(a){return["translate(",a.x,",",a.y,")"].join("")});Wa();Xa()});i=a.M();ea=a.f();N&&(c=l,i=a.b(N),ea=a.f(N));
K.c=db(a,i,P,da,e.node_shape,F);F=eb(a,ea,P,b,A,Q);K.e=F[0];K.d=F[1];fb(K.c,{attr:e.node_attr,style:e.node_style,K:e.label_style,J:e.label_attr},e.with_labels);gb(K.e,K.d,{attr:e.edge_attr,style:e.edge_style,K:e.edge_label_style,J:e.edge_label_attr},e.with_edge_labels,k,f);c?hb(a,P,e,K):a.bound?ib(a):jb(a);P.start()});
function db(a,b,c,d,e,f){var i=c.nodes();L(b,function(b){var c=a.node[b],b={node:b,data:c,G:a};i.push(b);c.__d3datum__=b});d=d.data(i,kb);b=d.enter().append("g").classed("node",j).call(c.drag);b.append(e).classed("node",j);f&&b.append("text").text(f);return d}
function eb(a,b,c,d,e,f){var i=c.links();L(b,function(b){var c=b[0],d=b[1],b=b[2]||a.H(c,d),c={edge:[c,d],fa:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b,G:a};i.push(c);b.__d3datum__=c});d=d.data(i,lb);d.enter().append("path").classed("edge",j);f&&(e=e.data(i,lb),e.enter().append("text").text(f));return[d,e]}
function fb(a,b,c,d){if(q(d)){var e={};L(d,function(a){e[t(a)?a[0]:a]=j});a=a.filter(function(a){return a.T in e})}var f=a.selectAll(".node");C(b.attr,function(a,b){f.attr(b,a)});C(b.style,function(a,b){f.style(b,a)});if(c){var i=a.selectAll("text");C(b.J,function(a,b){i.attr(b,a)});C(b.K,function(a,b){i.style(b,a)})}}
function gb(a,b,c,d,e,f){if(q(e)){var i={};L(e,function(a){i[[a[0],a[1]]]=j});a=a.filter(function(a){return a.Z in i||f||a.fa in i});b=b.filter(function(a){return a.Z in i||f||a.fa in i})}C(c.attr,function(b,c){a.attr(c,b)});C(c.style,function(b,c){a.style(c,b)});d&&(C(c.J,function(a,c){b.attr(c,a)}),C(c.K,function(a,c){b.style(c,a)}))}function kb(a){return a.node}function lb(a){return a.edge}
function mb(a,b,c,d){var e=c.nodes();L(a.b(b),function(b){b=la(e,a.node[b].__d3datum__);0<=b&&y.splice.call(e,b,1)});d=d.data(e,kb);d.exit().remove();return d}function nb(a,b,c,d,e){var f=c.links();L(b,function(b){b=la(f,H(a.H(b[0],b[1],{}),"__d3datum__",k));0<=b&&y.splice.call(f,b,1)});d=d.data(f,lb);d.exit().remove();q(e)&&(e=e.data(f,lb),e.exit().remove());return[d,e]}
function hb(a,b,c,d){ib(a,l);var e=a.constructor.prototype,f=c.node_shape,i={attr:c.node_attr,style:c.node_style,J:c.label_attr,K:c.label_style},r={attr:c.edge_attr,style:c.edge_style,J:c.edge_label_attr,K:c.edge_label_style},A=c.labels,da=c.edge_labels,P=c.with_labels,ea=c.with_edge_labels,La=a.g();a.add_node=a.D=function(a){var c=!this.l(a);e.add_node.apply(this,arguments);c&&(d.c=db(this,[a],b,d.c,f,A));fb(d.c,i,P,[a]);b.start()};a.add_nodes_from=a.j=function(a){var c=na(R(a),function(a){return!this.l(t(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.c=db(this,c,b,d.c,f,A));fb(d.c,i,P,a);b.start()};a.add_edge=a.k=function(c,N){var F=!this.s(c,N),Q=[];F&&(Q=na(c==N?[c]:[c,N],function(a){return!this.l(a)},this));e.add_edge.apply(a,arguments);0<Q.length&&(d.c=db(this,Q,b,d.c,f,A),fb(d.c,i,P,Q));F&&(F=eb(this,[[c,N]],b,d.e,d.d,da),d.e=F[0],d.d=F[1]);gb(d.e,d.d,r,ea,[[c,N]],La);b.start()};a.add_edges_from=a.a=function(c){var N=[],F=[],Q={},Z={},fa=this.g();L(c,function(a){var b=a[0],
a=a[1];if(!this.s(b,a)&&!([b,a]in Q)&&(fa||!([a,b]in Q)))if(N.push([b,a]),Q[[b,a]]=j,!this.l(b)&&!(b in Z)&&(F.push(b),Z[b]=j),!this.l(a)&&!(a in Z))F.push(a),Z[a]=j},this);e.add_edges_from.apply(a,arguments);0<F.length&&(d.c=db(this,F,b,d.c,f,A),fb(d.c,i,P,F));if(0<N.length){var K=eb(this,N,b,d.e,d.d,da);d.e=K[0];d.d=K[1]}gb(d.e,d.d,r,ea,N,fa);b.start()};a.remove_node=a.P=function(c){try{if(this.l(c)){d.c=mb(this,[c],b,d.c);var f=this.f([c]);this.g()&&(f=Da(f,this.u([c])));var i=nb(this,f,b,d.e,
d.d);d.e=i[0];d.d=i[1];b.resume()}}catch(r){}e.remove_node.apply(a,arguments)};a.remove_nodes_from=a.Q=function(c){try{d.c=mb(this,c,b,d.c);var f=this.f(c);this.g()&&(f=Da(f,this.u(c)));var i=nb(this,f,b,d.e,d.d);d.e=i[0];d.d=i[1];b.resume()}catch(r){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.n=function(c,f){try{var i=nb(this,[[c,f]],b,d.e,d.d);d.e=i[0];d.d=i[1];b.resume()}catch(r){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.v=function(c){try{var f=nb(this,c,b,d.e,d.d);
d.e=f[0];d.d=f[1];b.resume()}catch(i){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.c=d.c.data([],kb);d.c.exit().remove();d.e=d.e.data([],lb);d.e.exit().remove();d.d=d.d.data([],lb);d.d.exit().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=j}w("jsnx.is_bound",function(a){return a.bound});function ib(a,b){if(a.bound){var c=a.constructor.prototype;ma(bb,function(b){a[b]=c[b]});delete a.bound;(!p(b)||b)&&jb(a)}}w("jsnx.unbind",ib);
function jb(a){L(a.M(j),function(a){G(a[1],"__d3datum__")});L(a.f(j),function(a){G(a[2],"__d3datum__")})}
var cb={layout_attr:{charge:-120,linkDistance:40},node_shape:"circle",node_attr:{r:10},node_style:{stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{stroke:"#000","stroke-width":2},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","text-anchor":"middle","-webkit-user-select":"none"},with_labels:l,with_edge_labels:l,edge_offset:10,weights:"weight",
weighted_stroke:j,with_zoom:j};function U(a){this.name="JSNetworkXException";this.message=a}U.prototype=Error();U.prototype.constructor=U;w("jsnx.JSNetworkXException",U);function V(a){U.call(this,a);this.name="JSNetworkXError"}x(V,U);w("jsnx.JSNetworkXError",V);function ob(a){U.call(this,a);this.name="JSNetworkXPointlessConcept"}x(ob,U);w("jsnx.JSNetworkXPointlessConcept",ob);function pb(a){U.call(this,a);this.name="JSNetworkXAlgorithmError"}x(pb,U);w("jsnx.JSNetworkXAlgorithmError",pb);
function qb(a){pb.call(this,a);this.name="JSNetworkXUnfeasible"}x(qb,pb);w("jsnx.JSNetworkXUnfeasible",qb);function sb(a){qb.call(this,a);this.name="JSNetworkXNoPath"}x(sb,qb);w("jsnx.JSNetworkXNoPath",sb);function tb(a){pb.call(this,a);this.name="JSNetworkXUnbounded"}x(tb,pb);w("jsnx.JSNetworkXUnbounded",tb);function ub(a){if("function"==typeof a.F)return a.F();if(u(a))return a.split("");if(t(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ha(a)};function vb(a,b){this.i={};this.h=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.X(a)}n=vb.prototype;n.z=0;n.S=0;n.F=function(){wb(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.i[this.h[b]]);return a};n.clear=function(){this.i={};this.S=this.z=this.h.length=0};
n.remove=function(a){return Object.prototype.hasOwnProperty.call(this.i,a)?(delete this.i[a],this.z--,this.S++,this.h.length>2*this.z&&wb(this),j):l};function wb(a){if(a.z!=a.h.length){for(var b=0,c=0;b<a.h.length;){var d=a.h[b];Object.prototype.hasOwnProperty.call(a.i,d)&&(a.h[c++]=d);b++}a.h.length=c}if(a.z!=a.h.length){for(var e={},c=b=0;b<a.h.length;)d=a.h[b],Object.prototype.hasOwnProperty.call(e,d)||(a.h[c++]=d,e[d]=1),b++;a.h.length=c}}
n.set=function(a,b){Object.prototype.hasOwnProperty.call(this.i,a)||(this.z++,this.h.push(a),this.S++);this.i[a]=b};n.X=function(a){var b;a instanceof vb?(wb(a),b=a.h.concat(),a=a.F()):(b=E(a),a=Ha(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};n.Y=function(){return new vb(this)};
n.p=function(a){wb(this);var b=0,c=this.h,d=this.i,e=this.S,f=this,i=new B;i.next=function(){for(;;){e!=f.S&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(z);var i=c[b++];return a?i:d[i]}};return i};function xb(a){this.i=new vb;a&&this.X(a)}function yb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ha]||(a[ha]=++ia)):b.substr(0,1)+a}n=xb.prototype;n.add=function(a){this.i.set(yb(a),a)};n.X=function(a){for(var a=ub(a),b=a.length,c=0;c<b;c++)this.add(a[c])};n.remove=function(a){return this.i.remove(yb(a))};n.clear=function(){this.i.clear()};n.contains=function(a){a=yb(a);return Object.prototype.hasOwnProperty.call(this.i.i,a)};n.F=function(){return this.i.F()};n.Y=function(){return new xb(this)};
n.p=function(){return this.i.p(l)};function zb(a){if(q(a))try{a.clear()}catch(b){g(Error("Input graph is not a jsnx graph type"))}else a=new ja.xa;return a}
function Ab(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=Bb(a.adj,b,a.m()),"graph"in a&&"object"===o(a.graph)&&(d.graph=Ja(a.graph)),"node"in a&&"object"===o(a.node)&&(d.node=Fa(a.node,function(a){return Ja(a)})),d}catch(e){g(Error("Input is not a correct jsnx graph"))}if("object"===o(a))try{return Bb(a,b,c)}catch(f){try{return Cb(a,b)}catch(i){g(Error("Input is not known type."))}}if(t(a))try{return Db(a,b)}catch(r){g(Error("Input is not valid edge list"))}}w("jsnx.to_networkx_graph",Ab);
w("jsnx.convert_to_undirected",ja.za);w("jsnx.convert_to_undirected",ja.ya);w("jsnx.to_dict_of_lists",ja.Ca);function Cb(a,b){var c=zb(b);c.j(a);if(c.m()&&!c.g()){var d={};C(a,function(a,b){ma(a,function(a){a in d||c.k(b,a)});d[b]=1})}else{var e=[];C(a,function(a,b){ma(a,function(a){e.push([b,a])})});c.a(e)}return c}
function Bb(a,b,c){var d=zb(b),e,f;d.j(a);c?d.g()?(d.m()?(e=[],C(a,function(a,b){t(a)&&g(Error());C(a,function(a,c){C(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],C(a,function(a,b){t(a)&&g(Error());C(a,function(a,c){C(a,function(a){e.push([b,c,a])})})})),d.a(e)):d.m()?(f=new xb,C(a,function(a,b){t(a)&&g(Error());C(a,function(a,c){f.contains([b,c].toString())||(e=[],C(a,function(a,d){e.push([b,c,d,a])}),d.a(e),f.add([c,b].toString()))})})):(f=new xb,C(a,function(a,b){t(a)&&g(Error());C(a,function(a,
c){f.contains([b,c].toString())||(e=[],C(a,function(a){e.push([b,c,a])}),d.a(e),f.add([c,b].toString()))})})):d.m()&&!d.g()?(f=new xb,C(a,function(a,b){t(a)&&g(Error());C(a,function(a,c){f.contains([b,c].toString())||(d.k(b,c,a),f.add([c,b].toString()))})})):(e=[],C(a,function(a,b){t(a)&&g(Error());C(a,function(a,c){e.push([b,c,a])})}),d.a(e));return d}function Db(a,b){var c=zb(b);c.a(a);return c};function Eb(){this.V=h}function Fb(a){var b=[];Gb(new Eb,a,b);return b.join("")}
function Gb(a,b,c){switch(typeof b){case "string":Jb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==k){c.push("null");break}if(s(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Gb(a,a.V?a.V.call(b,""+f,e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Jb(f,c),c.push(":"),
Gb(a,a.V?a.V.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var Kb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Lb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Jb(a,b){b.push('"',a.replace(Lb,function(a){if(a in Kb)return Kb[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Kb[a]=e+b.toString(16)}),'"')};function W(a,b){if(!(this instanceof W))return new W(a,b);this.graph={};this.node={};this.adj={};q(a)&&Ab(a,this);I(this.graph,b||{});this.edge=this.adj}w("jsnx.classes.Graph",W);w("jsnx.Graph",W);W.__name__="Graph";W.prototype.pa=k;W.prototype.graph=W.prototype.pa;W.prototype.T=k;W.prototype.node=W.prototype.T;W.prototype.ma=k;W.prototype.adj=W.prototype.ma;W.prototype.Z=k;W.prototype.edge=W.prototype.Z;
W.prototype.name=function(a){if(p(a))this.graph.name=a.toString();else return this.graph.name||""};W.prototype.name=W.prototype.name;W.prototype.toString=function(){return this.name()};W.prototype.toString=W.prototype.toString;W.prototype.p=function(){return J(this.adj)};W.prototype.__iterator__=W.prototype.p;W.prototype.ca=function(a){a in this.adj||g({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};W.prototype.get_node=W.prototype.ca;
W.prototype.D=function(a,b){q(b)||(b={});"object"!==o(b)&&g(new V("The attr_dict argument must be an object."));a in this.adj?I(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};W.prototype.add_node=W.prototype.D;W.prototype.j=function(a,b){var c,d,e,f,i,b=b||{};L(a,function(a){c=!(a in this.adj);s(a)?(d=a[0],e=a[1],d in this.adj?(i=this.node[d],I(i,b,e)):(this.adj[d]={},f=Ja(b),I(f,e),this.node[d]=f)):c?(this.adj[a]={},this.node[a]=Ja(b)):I(this.node[a],b)},this)};
W.prototype.add_nodes_from=W.prototype.j;W.prototype.P=function(a){var b=this.adj,c;a in this.node||g(new V("The node "+a+" is not in the graph"));c=E(b[a]);G(this.node,a);ma(c,function(c){G(b[c],a)});G(b,a)};W.prototype.remove_node=W.prototype.P;W.prototype.Q=function(a){var b=this.adj;L(a,function(a){try{G(this.node,a),C(b[a],function(d,f){G(b[f],a)}),G(b,a)}catch(d){}},this)};W.prototype.remove_nodes_from=W.prototype.Q;W.prototype.M=function(a){return a?S(this.node):J(E(this.adj))};
W.prototype.nodes_iter=W.prototype.M;W.prototype.nodes=function(a){return Ea(this.M(a))};W.prototype.nodes=W.prototype.nodes;W.prototype.N=function(){return D(this.adj)};W.prototype.number_of_nodes=W.prototype.N;W.prototype.ua=function(){return D(this.adj)};W.prototype.order=W.prototype.ua;W.prototype.l=function(a){return!s(a)&&a in this.adj};W.prototype.has_node=W.prototype.l;
W.prototype.k=function(a,b,c){c=c||{};"object"!==o(c)&&g(new V("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=H(this.adj[a],b,{});I(d,c);this.adj[a][b]=d;this.adj[b][a]=d};W.prototype.add_edge=W.prototype.k;
W.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&g(new V("The attr_dict argument must be an object."));L(a,function(a){var d=Qa(a),e,f,i;3===d?(e=a[0],f=a[1],i=a[2]):2===d?(e=a[0],f=a[1],i={}):g(new V("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});f in this.adj||(this.adj[f]={},this.node[f]={});a=H(this.adj[e],f,{});I(a,b,i);this.adj[e][f]=a;this.adj[f][e]=a},this)};W.prototype.add_edges_from=W.prototype.a;
W.prototype.la=function(a,b,c){c=c||{};u(b)||(c=b,b="weight");this.a(M(a,function(a){var c={};c[b]=a[2];p(c[b])||g(new TypeError("Values must consist of three elements: "+Fb(a)));return[a[0],a[1],c]}),c)};W.prototype.add_weighted_edges_from=W.prototype.la;W.prototype.n=function(a,b){try{G(this.adj[a],b),a!=b&&G(this.adj[b],a)}catch(c){c instanceof TypeError&&g(new V("The edge "+a+"-"+b+" is not in the graph")),g(c)}};W.prototype.remove_edge=W.prototype.n;
W.prototype.v=function(a){L(a,function(a){var c=a[0],a=a[1];c in this.adj&&a in this.adj[c]&&(G(this.adj[c],a),c!=a&&G(this.adj[a],c))},this)};W.prototype.remove_edges_from=W.prototype.v;W.prototype.s=function(a,b){return a in this.adj&&b in this.adj[a]};W.prototype.has_edge=W.prototype.s;W.prototype.L=function(a){a in this.adj||g(new V("The node "+a+" is not in the graph."));return R(this.adj[a])};W.prototype.neighbors=W.prototype.L;
W.prototype.aa=function(a){a in this.adj||g(new V("The node "+a+" is not in the graph."));return J(this.adj[a])};W.prototype.neighbors_iter=W.prototype.aa;W.prototype.B=function(a,b){return R(this.f(a,b))};W.prototype.edges=W.prototype.B;
W.prototype.f=function(a,b){v(a)&&(b=a,a=k);var c={},d,e;d=q(a)?M(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return b?T(d,function(a){e=a[0];var b=new B,d=S(a[1]);b.next=function(){try{return d.next()}catch(a){a===z&&(c[e]=1);g(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):T(d,function(a){e=a[0];var b=new B,d=J(a[1]);b.next=function(){try{return d.next()}catch(a){a===z&&(c[e]=1);g(a)}};return b},function(a){if(!(a in c))return[e,a]})};W.prototype.edges_iter=W.prototype.f;
W.prototype.H=function(a,b,c){p(c)||(c=k);return a in this.adj?H(this.adj[a],b,c):c};W.prototype.get_edge_data=W.prototype.H;W.prototype.na=function(){return R(M(this.q(),function(a){return E(a[1])}))};W.prototype.adjacency_list=W.prototype.na;W.prototype.q=function(){return S(this.adj)};W.prototype.adjacency_iter=W.prototype.q;W.prototype.A=function(a,b){return this.l(a)?this.o(a,b).next()[1]:Oa(Ea(this.o(a,b)))};W.prototype.degree=W.prototype.A;
W.prototype.o=function(a,b){var c;c=q(a)?M(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return b?M(c,function(a){var c=a[0],a=a[1],f=0,i;for(i in a)f+=+H(a[i],b,1);f+=+(c in a&&H(a[c],b,1));return[c,f]}):M(c,function(a){return[a[0],D(a[1])+ +(a[0]in a[1])]})};W.prototype.degree_iter=W.prototype.o;W.prototype.clear=function(){this.name("");Ia(this.adj);Ia(this.node);Ia(this.graph)};W.prototype.clear=W.prototype.clear;W.prototype.copy=function(){return Va(this)};W.prototype.copy=W.prototype.copy;
W.prototype.m=m(l);W.prototype.is_multigraph=W.prototype.m;W.prototype.g=m(l);W.prototype.is_directed=W.prototype.g;W.prototype.w=function(){var a=new X;a.name(this.name());a.j(this);a.a(function(){var a;return T(this.q(),function(c){a=c[0];return S(c[1])},function(c){return[a,c[0],O(c[1])]})}.call(this));a.graph=O(this.graph);a.node=O(this.node);return a};W.prototype.to_directed=W.prototype.w;W.prototype.R=function(){return Va(this)};W.prototype.to_undirected=W.prototype.R;
W.prototype.t=function(a){var a=this.b(a),b=new this.constructor,c=b.adj,d=this.adj;L(a,function(a){var b={};c[a]=b;C(d[a],function(d,r){r in c&&(b[r]=d,c[r][a]=d)})});L(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};W.prototype.subgraph=W.prototype.t;W.prototype.sa=function(){return oa(na(Ua(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};W.prototype.nodes_with_selfloops=W.prototype.sa;
W.prototype.W=function(a){return a?oa(na(Ua(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):oa(na(Ua(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};W.prototype.selfloop_edges=W.prototype.W;W.prototype.ta=function(){return this.W().length};W.prototype.number_of_selfloops=W.prototype.ta;W.prototype.size=function(a){var b=Za.apply(k,Ha(this.A(k,a)))/2;return q(a)?b:Math.floor(b)};W.prototype.size=W.prototype.size;
W.prototype.C=function(a,b){return!q(a)?Math.floor(this.size()):b in this.adj[a]?1:0};W.prototype.number_of_edges=W.prototype.C;W.prototype.ka=function(a,b){var c=R(a),d=c[0];this.a(M(va(c,1),function(a){return[d,a]}),b)};W.prototype.add_star=W.prototype.ka;W.prototype.ja=function(a,b){var c=R(a);this.a(xa(va(c,0,c.length-1),va(c,1)),b)};W.prototype.add_path=W.prototype.ja;W.prototype.ia=function(a,b){var c=R(a);this.a(xa(c,ta(va(c,1),[c[0]])),b)};W.prototype.add_cycle=W.prototype.ia;
W.prototype.b=function(a){return q(a)?this.l(a)?J([a.toString()]):function(a,c){var d=new B,e=T(a,function(a){if(a in c)return a.toString()});d.next=function(){try{return e.next()}catch(a){a instanceof TypeError&&g(new V("nbunch is not a node or a sequence of nodes")),g(a)}};return d}(a,this.adj):J(this.adj)};W.prototype.nbunch_iter=W.prototype.b;function X(a,b){if(!(this instanceof X))return new X(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;q(a)&&Ab(a,this);I(this.graph,b||{});this.edge=this.adj}w("jsnx.classes.DiGraph",X);w("jsnx.DiGraph",X);x(X,W);X.__name__="DiGraph";X.prototype.D=function(a,b){q(b)||(b={});"object"!==o(b)&&g(new V("The attr_dict argument must be an object."));a in this.succ?I(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};X.prototype.add_node=X.prototype.D;
X.prototype.j=function(a,b){var c,d,e,f,i,b=b||{};L(J(a),function(a){c=!(a in this.succ);s(a)?(d=a[0],e=a[1],d in this.succ?(i=this.node[d],I(i,b,e)):(this.succ[d]={},this.pred[d]={},f=Ja(b),I(f,e),this.node[d]=f)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=Ja(b)):I(this.node[a],b)},this)};X.prototype.add_nodes_from=X.prototype.j;
X.prototype.P=function(a){a in this.node||g(new V("The node "+a+" is not in the graph"));var b=this.succ[a];G(this.node,a);C(b,function(b,d){G(this.pred[d],a)},this);G(this.succ,a);C(this.pred[a],function(b,d){G(this.succ[d],a)},this);G(this.pred,a)};X.prototype.remove_node=X.prototype.P;
X.prototype.Q=function(a){var b;L(a,function(a){a in this.succ&&(b=this.succ[a],G(this.node,a),C(b,function(b,e){G(this.pred[e],a)},this),G(this.succ,a),C(this.pred[a],function(b,e){G(this.succ[e],a)},this),G(this.pred,a))},this)};X.prototype.remove_nodes_from=X.prototype.Q;
X.prototype.k=function(a,b,c){c=c||{};"object"!==o(c)&&g(new V("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=H(this.adj[a],b,{});I(d,c);this.succ[a][b]=d;this.pred[b][a]=d};X.prototype.add_edge=X.prototype.k;
X.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&g(new V("The attr_dict argument must be an object."));L(a,function(a){var d=Qa(a),e,f,i;3===d?(e=a[0],f=a[1],i=a[2]):2===d?(e=a[0],f=a[1],i={}):g(new V("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});f in this.succ||(this.succ[f]={},this.pred[f]={},this.node[f]={});a=H(this.adj[e],f,{});I(a,b,i);this.succ[e][f]=a;this.pred[f][e]=a},this)};
X.prototype.add_edges_from=X.prototype.a;X.prototype.n=function(a,b){try{G(this.succ[a],b),G(this.pred[b],a)}catch(c){c instanceof TypeError&&g(new V("The edge "+a+"-"+b+" is not in the graph")),g(c)}};X.prototype.remove_edge=X.prototype.n;X.prototype.v=function(a){L(a,function(a){var c=a[0],a=a[1];c in this.succ&&a in this.succ[c]&&(G(this.succ[c],a),G(this.pred[a],c))},this)};X.prototype.remove_edges_from=X.prototype.v;X.prototype.ra=function(a,b){return a in this.succ&&b in this.succ[a]};
X.prototype.has_successor=X.prototype.ra;X.prototype.qa=function(a,b){return a in this.pred&&b in this.pred[a]};X.prototype.has_predecessor=X.prototype.qa;X.prototype.ha=function(a){a in this.succ||g(new V("The node "+a+" is not in the digraph."));return J(this.succ[a])};X.prototype.successors_iter=X.prototype.ha;X.prototype.wa=function(a){a in this.pred||g(new V("The node "+a+" is not in the digraph."));return J(this.pred[a])};X.prototype.predecessors_iter=X.prototype.wa;
X.prototype.ga=function(a){a in this.succ||g(new V("The node "+a+" is not in the digraph."));return R(this.succ[a])};X.prototype.successors=X.prototype.ga;X.prototype.va=function(a){a in this.succ||g(new V("The node "+a+" is not in the digraph."));return R(this.pred[a])};X.prototype.predecessors=X.prototype.va;X.prototype.L=X.prototype.ga;X.prototype.neighbors=X.prototype.L;X.prototype.aa=X.prototype.ha;X.prototype.neighbors_iter=X.prototype.aa;
X.prototype.f=function(a,b){v(a)&&(b=a,a=k);var c,d,e;c=q(a)?M(this.b(a),function(a){return[a,this.adj[a]]},this):Ua(this.adj);return b?T(c,function(a){d=a[0];e=a[1];return S(e)},function(a){return[d,a[0],a[1]]}):T(c,function(a){d=a[0];e=a[1];return S(e)},function(a){return[d,a[0]]})};X.prototype.edges_iter=X.prototype.f;X.prototype.U=X.prototype.f;X.prototype.out_edges_iter=X.prototype.U;X.prototype.ba=W.prototype.B;X.prototype.out_edges=X.prototype.ba;
X.prototype.u=function(a,b){v(a)&&(b=a,a=k);var c,d;c=q?M(this.b(a),function(a){return[a,this.pred[a]]},this):Ua(this.pred);return b?T(c,function(a){d=a[0];return S(a[0])},function(a){return[a[0],d,a[1]]}):T(c,function(a){d=a[0];return S(a[1])},function(a){return[a[0],d]})};X.prototype.in_edges_iter=X.prototype.u;X.prototype.$=function(a,b){return R(this.u(a,b))};X.prototype.in_edges=X.prototype.$;
X.prototype.o=function(a,b){var c;c=q(a)?Sa(M(this.b(a),function(a){return[a,this.succ[a]]},this),M(this.b(a),function(a){return[a,this.pred[a]]},this)):Sa(S(this.succ),S(this.pred));return b?M(c,function(a){var c=a[0][1],f=a[1][1],i=0,r;for(r in c)i+=+H(c[r],b,1);for(r in f)i+=+H(f[r],b,1);return[a[0][0],i]}):M(c,function(a){return[a[0][0],Qa(a[0][1])+Qa(a[1][1])]})};X.prototype.degree_iter=X.prototype.o;
X.prototype.I=function(a,b){var c;c=q(a)?M(this.b(a),function(a){return[a,this.pred[a]]},this):S(this.pred);return b?M(c,function(a){var c=0,f=a[1],i;for(i in f)c+=+H(f[i],b,1);return[a[0],c]}):M(c,function(a){return[a[0],D(a[1])]})};X.prototype.in_degree_iter=X.prototype.I;X.prototype.O=function(a,b){var c;c=q(a)?M(this.b(a),function(a){return[a,this.succ[a]]},this):S(this.succ);return b?M(c,function(a){var c=0,f=a[1],i;for(i in f)c+=+H(f[i],b,1);return[a[0],c]}):M(c,function(a){return[a[0],D(a[1])]})};
X.prototype.out_degree_iter=X.prototype.O;X.prototype.da=function(a,b){return this.l(a)?this.I(a,b).next()[1]:Oa(this.I(a,b))};X.prototype.in_degree=X.prototype.da;X.prototype.ea=function(a,b){return this.l(a)?this.O(a,b).next()[1]:Oa(this.O(a,b))};X.prototype.out_degree=X.prototype.ea;X.prototype.clear=function(){Ia(this.succ);Ia(this.pred);Ia(this.node);Ia(this.graph)};X.prototype.clear=X.prototype.clear;X.prototype.m=m(l);X.prototype.is_multigraph=X.prototype.m;X.prototype.g=m(j);
X.prototype.is_directed=X.prototype.g;X.prototype.w=function(){return Va(this)};X.prototype.to_directed=X.prototype.w;X.prototype.R=function(a){var b=new W;b.name(this.name());b.j(this);var c=this.pred,d;a?b.a(T(this.q(),function(a){d=a[0];return S(a[1])},function(a){if(a[0]in c[d])return[d,a[0],O(a[1])]})):b.a(T(this.q(),function(a){d=a[0];return S(a[1])},function(a){return[d,a[0],O(a[1])]}));b.graph=O(this.graph);b.node=O(this.node);return b};X.prototype.to_undirected=X.prototype.R;
X.prototype.reverse=function(a){(a=!p(a)||a)?(a=new this.constructor(k,{name:"Reverse of ("+this.name()+")"}),a.j(this),a.a(M(this.f(j),function(a){return[a[1],a[0],O(a[2])]})),a.graph=O(this.graph),a.node=O(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};X.prototype.reverse=X.prototype.reverse;
X.prototype.t=function(a){var a=this.b(a),b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;L(a,function(a){c[a]={};d[a]={}});L(c,function(a){var b=c[a];C(e[a],function(e,A){A in c&&(b[A]=e,d[A][a]=e)})});L(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};X.prototype.subgraph=X.prototype.t;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);W.call(this,a,b)}x(Y,W);w("jsnx.classes.MultiGraph",Y);w("jsnx.MultiGraph",Y);Y.__name__="MultiGraph";
Y.prototype.k=function(a,b,c,d){var e,f;q(c)&&!u(c)&&"number"!=typeof c&&(d=c,c=k);d=d||{};"object"!==o(d)&&g(new V("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});if(b in this.adj[a]){f=this.adj[a][b];if(!q(c))for(c=D(f);c in f;)c+=1;e=H(f,c,{});I(e,d);f[c]=e}else q(c)||(c=0),e={},I(e,d),f=Na(c,e),this.adj[a][b]=f,this.adj[b][a]=f};Y.prototype.add_edge=Y.prototype.k;
Y.prototype.a=function(a,b){b=b||{};"object"!==o(b)&&g(new V("The attr_dict argument must be an object."));L(a,function(a){var d=Qa(a),e,f,i=k,r={};4===d?(e=a[0],f=a[1],i=a[2],r=a[3]):3===d?(e=a[0],f=a[1],r=a[2]):2===d?(e=a[0],f=a[1]):g(new V("Edge tuple "+Fb(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=e in this.adj?H(this.adj[e],f,{}):{};if(!q(i))for(i=D(a);i in a;)i+=1;a=H(a,i,{});I(a,b,r);this.k(e,f,i,a)},this)};Y.prototype.add_edges_from=Y.prototype.a;
Y.prototype.n=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&g(new V("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];q(c)?(c in d||g(new V("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),G(d,c)):G(d,Ga(d));0===D(d)&&(G(this.adj[a],b),a!=b&&G(this.adj[b],a))};Y.prototype.remove_edge=Y.prototype.n;Y.prototype.v=function(a){L(a,function(a){try{this.n(a[0],a[1],a[2])}catch(c){c instanceof V||g(c)}},this)};Y.prototype.remove_edges_from=Y.prototype.v;
Y.prototype.s=function(a,b,c){return q(c)?a in this.adj&&b in this.adj[a]&&c in this.adj[a][b]:a in this.adj&&b in this.adj[a]};Y.prototype.has_edge=Y.prototype.s;Y.prototype.B=function(a,b,c){return Ea(this.f(a,b,c))};Y.prototype.edges=Y.prototype.B;
Y.prototype.f=function(a,b,c){v(a)&&(v(b)&&(c=b),b=a,a=k);var d={},e,f,a=q(a)?M(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return b?T(a,function(a){e=a[0];var b=new B,c=S(a[1]);b.next=function(){try{return c.next()}catch(a){a===z&&(d[e]=1);g(a)}};return b},function(a){f=a[0];if(!(f in d))return S(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):T(a,function(a){e=a[0];var b=new B,c=S(a[1]);b.next=function(){try{return c.next()}catch(a){a===z&&(d[e]=1);g(a)}};return b},function(a){f=
a[0];if(!(f in d))return S(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Y.prototype.edges_iter=Y.prototype.f;Y.prototype.H=function(a,b,c,d){p(d)||(d=k);return a in this.adj&&b in this.adj[a]?q(c)?H(this.adj[a][b],c,d):this.adj[a][b]:d};Y.prototype.get_edge_data=Y.prototype.H;
Y.prototype.o=function(a,b){var c;c=q(a)?M(this.b(a),function(a){return[a,this.adj[a]]},this):S(this.adj);return q(b)?Ba(c,function(a){var c=a[0],a=a[1],f=0;C(a,function(a){C(a,function(a){f+=H(a,b,1)})});c in a&&C(a[c],function(a){f+=H(a,b,1)});return[c,f]}):Ba(c,function(a){var b=a[0],a=a[1],c=0;C(a,function(a){c+=D(a)});return[b,c+ +(b in a&&D(a[b]))]})};Y.prototype.degree_iter=Y.prototype.o;Y.prototype.m=m(j);Y.prototype.is_multigraph=Y.prototype.m;Y.prototype.g=m(l);Y.prototype.is_directed=Y.prototype.g;
Y.prototype.w=function(){var a=new $;a.j(this);a.a(function(){var a,c;return T(this.q(),function(c){a=c[0];return S(c[1])},function(a){c=a[0];return S(a[1])},function(d){return[a,c,d[0],O(d[1])]})}.call(this));a.graph=O(this.graph);a.node=O(this.node);return a};Y.prototype.to_directed=Y.prototype.w;
Y.prototype.W=function(a,b){var c=[];a?b?C(this.adj,function(a,b){b in a&&C(a[b],function(a,d){c.push([b,b,d,a])})}):C(this.adj,function(a,b){b in a&&C(a[b],function(a){c.push([b,b,a])})}):b?C(this.adj,function(a,b){b in a&&C(a[b],function(a,d){c.push([b,b,d])})}):C(this.adj,function(a,b){b in a&&C(a[b],function(){c.push([b,b])})});return c};Y.prototype.selfloop_edges=Y.prototype.W;Y.prototype.C=function(a,b){return!q(a)?this.size():a in this.adj&&b in this.adj[a]?D(this.adj[a][b]):0};
Y.prototype.number_of_edges=Y.prototype.C;Y.prototype.t=function(a){var a=this.b(a),b=new this.constructor,c=b.adj,d=this.adj;Aa(a,function(a){var b={};c[a]=b;C(d[a],function(d,r){if(r in c){var A=Ja(d);b[r]=A;c[r][a]=A}})});C(this.node,function(a,c){b.node[c]=a});b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.t;function $(a,b){if(!(this instanceof $))return new $(a,b);X.call(this,a,b)}x($,X);var Mb=$.prototype,Nb=Y.prototype,Ob;for(Ob in Nb)Nb.hasOwnProperty(Ob)&&"constructor"!==Ob&&(Mb[Ob]=Nb[Ob]);w("jsnx.classes.MultiDiGraph",$);w("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";
$.prototype.k=function(a,b,c,d){var e,f;q(c)&&!u(c)&&"number"!=typeof c&&(d=c,c=k);d=d||{};"object"!==o(d)&&g(new V("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});if(b in this.succ[a]){f=this.adj[a][b];if(!q(c))for(c=D(f);c in f;)c+=1;e=H(f,c,{});I(e,d);f[c]=e}else q(c)||(c=0),e={},I(e,d),f=Na(c,e),this.succ[a][b]=f,this.pred[b][a]=f};$.prototype.add_edge=$.prototype.k;
$.prototype.n=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&g(new V("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];q(c)?(c in d||g(new V("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),G(d,c)):G(d,Ga(d));0===D(d)&&(G(this.succ[a],b),G(this.pred[b],a))};$.prototype.remove_edge=$.prototype.n;
$.prototype.f=function(a,b,c){v(a)&&(v(b)&&(c=b),b=a,a=k);var d,e,a=q(a)?M(this.b(a),function(a){return[a,this.adj[a]]},this):Ua(this.adj);return b?T(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):T(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};$.prototype.edges_iter=$.prototype.f;$.prototype.U=$.prototype.f;$.prototype.out_edges_iter=$.prototype.U;
$.prototype.ba=function(a,b,c){return Ea(this.U(a,b,c))};$.prototype.out_edges=$.prototype.ba;$.prototype.u=function(a,b,c){v(a)&&(b=a,a=k);var d,e,a=q?M(this.b(a),function(a){return[a,this.pred[a]]},this):Ua(this.pred);return b?T(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):T(a,function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};$.prototype.in_edges_iter=$.prototype.u;
$.prototype.$=function(a,b,c){return Ea(this.u(a,b,c))};$.prototype.in_edges=$.prototype.$;
$.prototype.o=function(a,b){var c;c=q(a)?Sa(Ba(this.b(a),function(a){return[a,this.succ[a]]},this),Ba(this.b(a),function(a){return[a,this.pred[a]]},this)):Sa(S(this.succ),S(this.pred));return q(b)?M(c,function(a){var c=a[0][1],f=0;C(a[1][1],function(a){C(a,function(a){f+=+H(a,b,1)})});C(c,function(a){C(a,function(a){f+=+H(a,b,1)})});return[a[0][0],f]}):M(c,function(a){var b=0,c=0;C(a[1][1],function(a){b+=Qa(a)});C(a[0][1],function(a){c+=Qa(a)});return[a[0][0],b+c]})};$.prototype.degree_iter=$.prototype.o;
$.prototype.I=function(a,b){var c;c=q(a)?M(this.b(a),function(a){return[a,this.pred[a]]},this):S(this.pred);return q(b)?M(c,function(a){var c=0;C(a[1],function(a){C(a,function(a){c+=+H(a,b,1)})});return[a[0][0],c]}):M(c,function(a){var b=0;C(a[1],function(a){b+=D(a)});return[a[0],b]})};$.prototype.in_degree_iter=$.prototype.I;
$.prototype.O=function(a,b){var c;c=q(a)?M(this.b(a),function(a){return[a,this.succ[a]]},this):S(this.succ);return q(b)?M(c,function(a){var c=0;C(a[1],function(a){C(a,function(a){c+=+H(a,b,1)})});return[a[0][0],c]}):M(c,function(a){var b=0;C(a[1],function(a){b+=D(a)});return[a[0],b]})};$.prototype.out_degree_iter=$.prototype.O;$.prototype.m=m(j);$.prototype.is_multigraph=$.prototype.m;$.prototype.g=m(j);$.prototype.is_directed=$.prototype.g;$.prototype.w=function(){return Va(this)};
$.prototype.to_directed=$.prototype.w;$.prototype.R=function(a){var b=new Y;b.name(this.name());b.j(this);var c=this,d,e;a?b.a(T(this.q(),function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){if(c.s(e,d,a[0]))return[d,e,a[0],O(a[1])]})):b.a(T(this.q(),function(a){d=a[0];return S(a[1])},function(a){e=a[0];return S(a[1])},function(a){return[d,e,a[0],O(a[1])]}));b.graph=O(this.graph);b.node=O(this.node);return b};$.prototype.to_undirected=$.prototype.R;
$.prototype.t=function(a){var a=this.b(a),b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;Aa(a,function(a){c[a]={};d[a]={}});L(c,function(a){var b=c[a];C(e[a],function(e,A){if(A in c){var da=Ja(e);b[A]=da;d[A][a]=da}})});L(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};$.prototype.subgraph=$.prototype.t;
$.prototype.reverse=function(a){(a=!p(a)||a)?(a=new this.constructor(k,{name:"Reverse of ("+this.name()+")"}),a.j(this),a.a(Ba(this.f(j,j),function(a){return[a[1],a[0],a[2],O(a[3])]})),a.graph=O(this.graph),a.node=O(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};$.prototype.reverse=$.prototype.reverse;w("jsnx.nodes",function(a){return a.nodes()});w("jsnx.nodes_iter",function(a){return a.M()});w("jsnx.edges",function(a,b){return a.B(b)});w("jsnx.edges_iter",function(a,b){return a.f(b)});w("jsnx.degree",function(a,b,c){return a.A(b,c)});w("jsnx.neighbors",function(a,b){return a.L(b)});w("jsnx.number_of_nodes",function(a){return a.N()});w("jsnx.number_of_edges",function(a){return a.C()});w("jsnx.density",function(a){var b=a.N(),c=a.C();return 0===c?0:a.g()?c/(b*(b-1)):2*c/(b*(b-1))});
w("jsnx.degree_histogram",function(a){var a=Ha(a.A()),b=Math.max.apply(Math,a)+1,c=wa(b);ma(a,function(a){c[a]+=1});return c});w("jsnx.is_directed",function(a){return a.g()});w("jsnx.freeze",function(a){function b(){g(new V("Frozen graph can't be modified"))}a.D=b;a.j=b;a.P=b;a.Q=b;a.k=b;a.a=b;a.n=b;a.v=b;a.clear=b;a.oa=j;return a});w("jsnx.is_frozen",function(a){return!!a.oa});w("jsnx.subgraph",function(a,b){return a.t(b)});
w("jsnx.create_empty_copy",function(a,b){p(b)||(b=j);var c=new a.constructor;b&&c.j(a);return c});
w("jsnx.info",function(a,b){var c="";if(q(b))a.l(b)||g(new V("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.A(b)+"\n"),c+="Neighbors: "+a.L(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.N()+"\n"),c=c+("Number of edges: "+a.C()+"\n"),d=a.N();if(0<d)if(a.g())c+="Average in degree: "+(Za.apply(k,Ha(a.da()))/d).toFixed(4)+"\n",c+="Average out degree: "+(Za.apply(k,Ha(a.ea()))/d).toFixed(4);
else var e=Za.apply(k,Ha(a.A())),c=c+("Average degree: "+(e/d).toFixed())}return c});w("jsnx.set_node_attributes",function(a,b,c){C(c,function(c,e){a.T[e][b]=c})});function Pb(a,b){var c={};C(a.T,function(a,e){b in a&&(c[e]=a[b])});return c}w("jsnx.get_node_attributes",Pb);w("jsnx.set_edge_attributes",function(a,b,c){C(c,function(b,c){c=c.split(",");a.ca(c[0])[c[1]]=b})});Pb=function(a,b){var c={};C(a.B(j),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};w("jsnx.get_edge_attributes",{}.Aa);}());
