(function(global, factory) { function extractNS(){ var g = {}; return factory.call(g, global),g.jsnx;} if(typeof define === 'function' && define.amd){ /*AMD*/ define(extractNS); } else if (typeof module !== 'undefined' && module.exports){ /*node*/ module.exports = extractNS(); } else { factory.call(global, global); } }(this, function(window) {function h(a){throw a;}var aa=void 0,k=!0,m=null,n=!1;function da(a){return function(){return a}}var q,ea=this;function fa(){}
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==aa}function ha(a){return"array"==r(a)}function t(a){var b=r(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function ia(a){return"boolean"==typeof a}function ja(a){return"number"==typeof a}function ka(a){return"function"==r(a)}function la(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}var ma="closure_uid_"+(1E9*Math.random()>>>0),na=0;
function oa(a,b,c){return a.call.apply(a.bind,arguments)}function pa(a,b,c){a||h(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function qa(a,b,c){qa=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?oa:pa;return qa.apply(m,arguments)}
function v(a,b){var c=a.split("."),d=ea;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&s(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function ra(a,b){function c(){}c.prototype=b.prototype;a.Wa=b.prototype;a.prototype=new c;a.prototype.constructor=a};var w=Array.prototype,sa=w.indexOf?function(a,b,c){return w.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},z=w.forEach?function(a,b,c){w.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ta=w.filter?function(a,b,c){return w.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=u(a)?a.split(""):
a,l=0;l<d;l++)if(l in g){var p=g[l];b.call(c,p,l,a)&&(e[f++]=p)}return e},ua=w.map?function(a,b,c){return w.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function va(a,b){if(a.reduce)return a.reduce(b,0);var c=0;z(a,function(d,e){c=b.call(aa,c,d,e,a)});return c}
function ya(a,b){var c;a:{c=a.length;for(var d=u(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(aa,d[e],e,a)){c=e;break a}c=-1}return 0>c?m:u(a)?a.charAt(c):a[c]}function za(a,b){var c=sa(a,b);0<=c&&w.splice.call(a,c,1)}function Aa(a){return w.concat.apply(w,arguments)}function Ba(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Fa(a,b,c,d){w.splice.apply(a,Ga(arguments,1))}
function Ga(a,b,c){return 2>=arguments.length?w.slice.call(a,b):w.slice.call(a,b,c)}function Ha(a,b,c){if(!t(a)||!t(b)||a.length!=b.length)return n;var d=a.length;c=c||La;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return n;return k}function Ma(a,b){return a>b?1:a<b?-1:0}function La(a,b){return a===b}function Na(a){for(var b=[],c=0;c<a;c++)b[c]=0;return b}
function Oa(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var A="StopIteration"in ea?ea.StopIteration:Error("StopIteration");function B(){}B.prototype.next=function(){h(A)};B.prototype.I=function(){return this};function Qa(a){if(a instanceof B)return a;if("function"==typeof a.I)return a.I(n);if(t(a)){var b=0,c=new B;c.next=function(){for(;;){b>=a.length&&h(A);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}
function C(a,b,c){if(t(a))try{z(a,b,c)}catch(d){d!==A&&h(d)}else{a=Qa(a);try{for(;;)b.call(c,a.next(),aa,a)}catch(e){e!==A&&h(e)}}}function Ra(a,b,c){var d=Qa(a);a=new B;a.next=function(){for(;;){var a=d.next();return b.call(c,a,aa,d)}};return a}function Sa(a,b,c){var d=c;C(a,function(a){d=b.call(aa,d,a)});return d}function Ta(a){var b=arguments,c=b.length,d=0,e=new B;e.next=function(){try{return d>=c&&h(A),Qa(b[d]).next()}catch(a){return(a!==A||d>=c)&&h(a),d++,this.next()}};return e}
function Ua(a){if(t(a))return Ba(a);a=Qa(a);var b=[];C(a,function(a){b.push(a)});return b}function Va(a,b){try{return Qa(a).next()}catch(c){return c!=A&&h(c),b}};function D(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Wa(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function E(a){var b=0,c;for(c in a)b++;return b}function Xa(a){for(var b in a)return b}function Ya(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function F(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Za(a){for(var b in a)return n;return k}function $a(a){for(var b in a)delete a[b]}function G(a,b){b in a&&delete a[b]}function H(a,b,c){return b in a?a[b]:c}
function db(a){var b={},c;for(c in a)b[c]=a[c];return b}var eb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function I(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<eb.length;f++)c=eb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function fb(a){var b=arguments.length;if(1==b&&ha(arguments[0]))return fb.apply(m,arguments[0]);b%2&&h(Error("Uneven number of arguments"));for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};var J={Ra:function(a){return Math.floor(Math.random()*a)},Xa:function(a,b){return a+Math.random()*(b-a)},La:function(a,b,c){return Math.min(Math.max(a,b),c)},Ca:function(a,b){var c=a%b;return 0>c*b?c+b:c},Oa:function(a,b,c){return a+c*(b-a)},Qa:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},ea:function(a){return J.Ca(a,360)},oa:function(a){return a*Math.PI/180},Ha:function(a){return 180*a/Math.PI},Ja:function(a,b){return b*Math.cos(J.oa(a))},Ka:function(a,b){return b*Math.sin(J.oa(a))},ga:function(a,
b,c,d){return J.ea(J.Ha(Math.atan2(d-b,c-a)))},Ia:function(a,b){var c=J.ea(b)-J.ea(a);180<c?c-=360:-180>=c&&(c=360+c);return c},Ua:function(a){return 0==a?0:0>a?-1:1},Pa:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],l=0;l<e+1;l++)g[l]=[],g[l][0]=0;for(var p=0;p<f+1;p++)g[0][p]=0;for(l=1;l<=e;l++)for(p=1;p<=e;p++)c(a[l-1],b[p-1])?g[l][p]=g[l-1][p-1]+1:g[l][p]=Math.max(g[l-1][p],g[l][p-1]);for(var y=[],l=e,p=f;0<l&&0<p;)c(a[l-1],b[p-
1])?(y.unshift(d(l-1,p-1)),l--,p--):g[l-1][p]>g[l][p-1]?l--:p--;return y},q:function(a){return va(arguments,function(a,c){return a+c})},va:function(a){return J.q.apply(m,arguments)/arguments.length},Va:function(a){var b=arguments.length;if(2>b)return 0;var c=J.va.apply(m,arguments),b=J.q.apply(m,ua(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},Na:function(a){return isFinite(a)&&0==a%1},Ma:function(a){return isFinite(a)&&!isNaN(a)},Ta:function(a,b){return Math.floor(a+
(b||2E-15))},Sa:function(a,b){return Math.ceil(a-(b||2E-15))}};function gb(a){return Sa(K(a),function(a,c){a[c[0]]=c[1];return a},{})}function hb(a){return a instanceof B||ka(a.I)}function ib(a){if(a instanceof M)return a.M();if(u(a)||t(a))return a.length;if(jb(a))return E(a);h(new TypeError)}function N(a,b,c,d){ia(c)&&(d=c,c=m);if(d){var e=b;b=function(a){e.apply(this,a)}}a instanceof M?C(K(a),b,c):hb(a)?C(a,b,c):t(a)||u(a)?z(a,b,c):la(a)&&N(F(a),b,c)}v("jsnx.forEach",N);
function O(a,b,c){if(a instanceof M)return O(K(a),b,c);if(t(a))return ua(a,b,c);if(hb(a))return Ra(a,b,c);if(la(a))return Wa(a,b,c);h(new TypeError)}function kb(a){var b=arguments,c=b[0];if(t(c))return Oa.apply(m,b);if(hb(c)){var c=new B,d=b.length;c.next=function(){for(var a=[],c=0;c<d;c++)a.push(b[c].next());return a};return c}if(la(c))return Oa.apply(m,ua(b,F));h(new TypeError)}function lb(a,b){a=ka(b)?P(O(a,function(){return b.apply(m,arguments)})):P(a);return Math.max.apply(m,a)}
function Q(a,b,c){if(0===arguments.length)return Qa([]);1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new B,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(A);g=f;f+=c;return g};return d}
function mb(a){var b=P(a),c=b.length;if(2>c)return new B;var d=P(Q(2));a=new B;a.next=function(){var a=ua(d,function(a){return b[a]});this.next=function(){var a=n,e;for(e=2;e--;)if(d[e]!=e+c-2){a=k;break}a||h(A);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return ua(d,function(a){return b[a]})};return a};return a}
function nb(a){var b=P(a),c=b.length,d=ja(2)?2:c;if(d>c)return new B;var e=P(Q(c)),f=P(Q(c,c-d,-1));a=new B;var g=new B,l,p=k;a.next=function(){this.next=l.next;return ua(e.slice(0,d),function(a){return b[a]})};g.next=function(){return p};l=R(g,function(a){a||h(A);p=n;return Q(d-1,-1,-1)},function(a){if(!p)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var g=f[a],l=e[a];e[a]=e[e.length-g];e[e.length-g]=l;p=k;return K([ua(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function ob(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!s(a[c])||"object"!==r(a[c])?a[c]=S(d[c]):"object"===r(a[c])&&"object"===r(d)&&ob(a[c],d[c]);for(var f=0;f<eb.length;f++)c=eb[f],Object.prototype.hasOwnProperty.call(d,c)&&(!s(a[c])||"object"!==r(a[c])?a[c]=S(d[c]):"object"===r(a[c])&&"object"===r(d)&&ob(a[c],d[c]))}}
function P(a){if(a instanceof M)return P(K(a));if(t(a))return Ba(a);if(hb(a))return Ua(a);if(la(a))return F(a);h(new TypeError)}v("jsnx.toArray",P);function pb(a){var b=[];D(a,function(a,d){b.push([d,a])});return b}function T(a){var b=new B,c=Qa(F(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function K(a){if(a instanceof M)return K(a.adj);"object"===r(a)&&(!t(a)&&!hb(a))&&(a=F(a));return Qa(a)}
function R(a,b){var c=new B,d=Ga(arguments,1);if(0===d.length)return a;try{a=Qa(a)}catch(e){return c.next=function(){"Not implemented"===e.message&&h(new TypeError)},c}var f=m;c.next=function(){var b,e;try{for(;!s(b);)b=f.next()}catch(p){for(;!s(e)||!s(b);)e=a.next(),b=d[0](e);if(hb(b))return f=R.apply(m,Aa([b],Ga(d,1))),c.next();f=m}return b};return c}v("jsnx.sentinelIterator",function(a,b){var c=new B;c.next=function(){return Va(a,b)};return c});
function jb(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==r(a)||a.nodeType||a==a.window)return n;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return n}catch(c){return n}for(var d in a);return d===aa||b.call(a,d)}
function S(a,b){b=b||[];var c=r(a);if("object"==c&&jb(a)||"array"==c){var d=ya(b,function(b){return a===b[0]});if(d!==m)return d[1];if(a.$)return d=[a,a.$()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var e in a)c[e]=S(a[e],b);return c}return a}function qb(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=S(c);a=new b;for(d in c)a[d]=c[d];return a}var sb=function rb(b,c){return 0===c?b:rb(c,b%c)};var tb,ub=m,vb="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
v("jsnx.draw",function(a,b,c){function d(){wa.f.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",ga,")"].join("")});Tb()}ia(b)&&(c=b,b=m);b=b||ub||{};var e=b.d3||window.d3,f={};ob(f,wb,b);ub=b;e||h(Error("D3 requried for draw()"));f.element==m&&tb==m&&h(Error("Output element required for draw()"));tb=H(f,"element",tb);e.select(tb).select("svg.jsnx").remove();var g=e.select(tb),l=g.append("svg").classed("jsnx",k).attr("pointer-events","all"),p=l.append("g");b=p.append("g").classed("edges",
k).selectAll("g.edge");var y=p.append("g").classed("nodes",k).selectAll("g.node"),x=e.layout.force(),L=f.width||parseInt(g.style("width"),10),V=f.height||parseInt(g.style("height"),10),Ia=f.layout_attr,g=f.nodelist||m,ba,ca,W,Ca=a.c(),xa=f.weighted,wa={f:y,g:b};if(f.with_labels){var Da=f.labels;ba="object"===r(Da)?function(a){return H(Da,a.node,"")}:ka(Da)?Da:u(Da)?function(a){return a.data[Da]}:function(a){return a.node}}f.labels=ba;if(xa){var Ja=f.weights;W="object"===r(Ja)?function(a){return H(Ja,
a.node,1)}:ka(Ja)?Ja:u(Ja)?function(a){return H(a.data,Ja,1)}:da(1)}if(f.with_edge_labels){var Ka=f.edge_labels;ca=xa&&!s(Ka)?W:"object"===r(Ka)?function(a){return H(Da,a.node,"")}:ka(Ka)?Ka:u(Ka)?function(a){return a.data[Ka]}:function(a){return a.edge};f.edge_labels=ca}if(xa&&f.weighted_stroke){var xa=Sa(a.e(m,k),function(a,b){b=W({data:b[2]});return a>b?a:b},0),Qc=e.scale.linear().range([2,f.edge_style["stroke-width"]]).domain([0,xa]);f.edge_style["stroke-width"]=function(a){return Qc(W.call(this,
a))}}l.select("svg.jsnx").remove();l.attr("width",L+"px").attr("height",V+"px").style("opacity",1E-6).transition().duration(1E3).style("opacity",1);var Rc={size:k,nodes:k,links:k,start:k};N(Ia,function(a){if(!(a in Rc))x[a](Ia[a])});x.nodes([]).links([]).size([L,V]);var Pa=1,ga=1;if(f.pan_zoom.enabled){var Ub=f.pan_zoom.scale;(function(){var a=n,b=1,c=Pa;l.call(e.behavior.zoom().on("zoom",function(){var f=e.event.sourceEvent.shiftKey;(f=Ub&&f||!(Ub||f))&&!a?(b=e.event.scale,c=Pa,a=k):!f&&a&&(a=n);
Pa=f?c*(e.event.scale/b):Pa;ga=!f?Pa/e.event.scale:ga;f=e.event.translate;p.attr("transform","translate("+f[0]+","+f[1]+")scale("+e.event.scale+")");d()}))})()}var Tb=fa,Ea=f.edge_offset,ab=f.node_attr.r,bb=f.node_style["stroke-width"];"circle"===f.node_shape?(ka(ab)||(ab=function(){return f.node_attr.r}),ka(bb)||(bb=function(){return f.node_style["stroke-width"]}),Ea=function(a){return[ab(a.source)+bb(a.source),ab(a.target)+bb(a.target)]}):(ha(Ea)&&(Ea=function(){return f.edge_offset}),ja(Ea)&&(Ea=
function(){return[f.edge_offset,f.edge_offset]}));var cb=f.edge_style["stroke-width"];ka(cb)||(cb=function(){return f.edge_style["stroke-width"]});Tb=Ca?function(){wa.g.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,f=a.target.x,g=a.target.y,l=J.ga(c,d,f,g),f=Math.sqrt(Math.pow(f-c,2)+Math.pow(g-d,2)),g=Ea(a),g=[g[0]*ga,g[1]*ga];b.attr("transform",["translate(",c,",",d,")rotate(",l,")"].join(""));a=cb(a)*ga;b.select(".line").attr("d",["M",g[0],0,"L",g[0],-a/
2,"L",f-g[1]-2*a,-a/2,"L",f-g[1]-2*a,-a,"L",f-g[1],0,"z"].join(" "));c=1/ga;b.select("text").attr("x",f*c/2).attr("y",-a/2*c).attr("transform","scale("+ga+")")}})}:function(){wa.g.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,l=a.target.y,p=J.ga(c,d,g,l),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(l-d,2)),l=g/2,y=Ea(a),y=[y[0]*ga,y[1]*ga];a=cb(a)*ga;b.attr("transform",["translate(",c,",",d,")rotate(",p,")"].join(""));b.select(".line").attr("d",["M",
y[0],a/4,"L",y[0],-a/4,"L",g-y[1],-a/4,"L",g-y[1],a/4,"z"].join(" "));f.with_edge_labels&&b.select("text").attr("x",l*(1/ga)).attr("y",0).attr("transform","scale("+ga+")"+(90<p&&279>p?"rotate(180,"+l*(1/ga)+",0)":""))}})};x.on("tick",d);L=a.v();V=a.e();g&&(c=n,L=a.d(g),V=a.e(g));wa.f=xb(a,L,x,y,f.node_shape,ba);wa.g=yb(a,V,x,b,ca);zb(wa.f,{attr:f.node_attr,style:f.node_style,U:f.label_style,T:f.label_attr},f.with_labels);Ab(wa.g,{attr:f.edge_attr,style:f.edge_style,U:f.edge_label_style,T:f.edge_label_attr},
f.with_edge_labels,m,Ca);c?Bb(a,x,f,wa):a.bound?Cb(a):Db(a);x.start();return x});function xb(a,b,c,d,e,f){var g=c.nodes();N(b,function(b){var c=a.node[b];b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,Eb);b=d.enter().append("g").classed("node",k).call(c.drag);b.append(e).classed("node-shape",k);f&&b.append("text").text(f);return d}
function yb(a,b,c,d,e){var f=c.links();N(b,function(b){var c=b[0],d=b[1];b=b[2]||a.P(c,d);c={edge:[c,d],redge:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,Fb);b=d.enter().append("g").classed("edge",k);b.append("path").classed("line",k);e&&b.append("text").text(e);return d}
function zb(a,b,c,d){if(d!=m){var e={};N(d,function(a){e[t(a)?a[0]:a]=k});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");D(b.attr,function(a,b){f.attr(b,a)});D(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");D(b.T,function(a,b){g.attr(b,a)});D(b.U,function(a,b){g.style(b,a)})}}
function Ab(a,b,c,d,e){if(d!=m){var f={};N(d,function(a){f[[a[0],a[1]]]=k});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");D(b.attr,function(a,b){g.attr(b,a)});D(b.style,function(a,b){"stroke-width"!=b&&g.style(b,a)});g.style("stroke-width",0);if(c){var l=a.selectAll("text");D(b.T,function(a,b){l.attr(b,a)});D(b.U,function(a,b){l.style(b,a)})}}function Eb(a){return a.node}function Fb(a){return a.edge}
function Gb(a,b,c,d){var e=c.nodes();N(a.d(b),function(b){za(e,a.node[b].__d3datum__)});d=d.data(e,Eb);d.exit().remove();return d}function Hb(a,b,c,d){var e=c.links();N(b,function(b){za(e,H(a.P(b[0],b[1],{}),"__d3datum__",m))});d=d.data(e,Fb);d.exit().remove();return d}
function Bb(a,b,c,d){Cb(a,n);var e=a.constructor.prototype,f=c.node_shape,g={attr:c.node_attr,style:c.node_style,T:c.label_attr,U:c.label_style},l={attr:c.edge_attr,style:c.edge_style,T:c.edge_label_attr,U:c.edge_label_style},p=c.labels,y=c.edge_labels,x=c.with_labels,L=c.with_edge_labels,V=a.c();a.add_node=a.D=function(a){var c=!this.l(a);e.add_node.apply(this,arguments);c&&(d.f=xb(this,[a],b,d.f,f,p));zb(d.f,g,x,[a]);b.start()};a.add_nodes_from=a.j=function(a){var c=ta(P(a),function(a){return!this.l(t(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.f=xb(this,c,b,d.f,f,p));zb(d.f,g,x,a);b.start()};a.add_edge=a.a=function(c,ba){var ca=!this.J(c,ba),W=[];ca&&(W=ta(c==ba?[c]:[c,ba],function(a){return!this.l(a)},this));e.add_edge.apply(a,arguments);0<W.length&&(d.f=xb(this,W,b,d.f,f,p),zb(d.f,g,x,W));ca&&(d.g=yb(this,[[c,ba]],b,d.g,y));Ab(d.g,l,L,[[c,ba]],V);b.start()};a.add_edges_from=a.b=function(c){var V=[],ca=[],W={},Ca={},xa=this.c();N(c,function(a){var b=a[0];a=a[1];if(!this.J(b,
a)&&!([b,a]in W)&&(xa||!([a,b]in W)))V.push([b,a]),W[[b,a]]=k,!this.l(b)&&!(b in Ca)&&(ca.push(b),Ca[b]=k),!this.l(a)&&!(a in Ca)&&(ca.push(a),Ca[a]=k)},this);e.add_edges_from.apply(a,arguments);0<ca.length&&(d.f=xb(this,ca,b,d.f,f,p),zb(d.f,g,x,ca));0<V.length&&(d.g=yb(this,V,b,d.g,y));Ab(d.g,l,L,V,xa);b.start()};a.remove_node=a.N=function(c){try{if(this.l(c)){d.f=Gb(this,[c],b,d.f);var f=this.e([c]);this.c()&&(f=Ta(f,this.H([c])));d.g=Hb(this,f,b,d.g);b.resume()}}catch(g){}e.remove_node.apply(a,
arguments)};a.remove_nodes_from=a.X=function(c){try{d.f=Gb(this,c,b,d.f);var f=this.e(c);this.c()&&(f=Ta(f,this.H(c)));d.g=Hb(this,f,b,d.g);b.resume()}catch(g){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.u=function(c,f){try{d.g=Hb(this,[[c,f]],b,d.g),b.resume()}catch(g){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.B=function(c){try{d.g=Hb(this,c,b,d.g),b.resume()}catch(f){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.f=d.f.data([],Eb);d.f.exit().remove();
d.g=d.g.data([],Fb);d.g.exit().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=k}v("jsnx.is_bound",function(a){return a.bound});function Cb(a,b){if(a.bound){var c=a.constructor.prototype;z(vb,function(b){a[b]=c[b]});delete a.bound;(!s(b)||b)&&Db(a)}}v("jsnx.unbind",Cb);function Db(a){N(a.v(k),function(a){G(a[1],"__d3datum__")});N(a.e(m,k),function(a){G(a[2],"__d3datum__")})}
var wb={layout_attr:{charge:-120,linkDistance:60},node_shape:"circle",node_attr:{r:10},node_style:{"stroke-width":2,stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{fill:"#000","stroke-width":3},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","dominant-baseline":"central","text-anchor":"middle","-webkit-user-select":"none"},with_labels:n,
with_edge_labels:n,edge_offset:10,weighted:n,weights:"weight",weighted_stroke:k,pan_zoom:{enabled:k,scale:k}};function Ib(a){if("function"==typeof a.F)return a.F();if(u(a))return a.split("");if(t(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ya(a)};function Jb(a,b){this.k={};this.n=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.ca(a)}q=Jb.prototype;q.z=0;q.Z=0;q.h=function(){return this.z};q.F=function(){Kb(this);for(var a=[],b=0;b<this.n.length;b++)a.push(this.k[this.n[b]]);return a};q.S=function(){return 0==this.z};q.clear=function(){this.k={};this.Z=this.z=this.n.length=0};
q.remove=function(a){return Object.prototype.hasOwnProperty.call(this.k,a)?(delete this.k[a],this.z--,this.Z++,this.n.length>2*this.z&&Kb(this),k):n};function Kb(a){if(a.z!=a.n.length){for(var b=0,c=0;b<a.n.length;){var d=a.n[b];Object.prototype.hasOwnProperty.call(a.k,d)&&(a.n[c++]=d);b++}a.n.length=c}if(a.z!=a.n.length){for(var e={},c=b=0;b<a.n.length;)d=a.n[b],Object.prototype.hasOwnProperty.call(e,d)||(a.n[c++]=d,e[d]=1),b++;a.n.length=c}}
q.set=function(a,b){Object.prototype.hasOwnProperty.call(this.k,a)||(this.z++,this.n.push(a),this.Z++);this.k[a]=b};q.ca=function(a){var b;a instanceof Jb?(Kb(a),b=a.n.concat(),a=a.F()):(b=F(a),a=Ya(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};q.$=function(){return new Jb(this)};
q.I=function(a){Kb(this);var b=0,c=this.n,d=this.k,e=this.Z,f=this,g=new B;g.next=function(){for(;;){e!=f.Z&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(A);var g=c[b++];return a?g:d[g]}};return g};function U(a){this.k=new Jb;a&&this.ca(a)}function Lb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ma]||(a[ma]=++na)):b.substr(0,1)+a}q=U.prototype;q.h=function(){return this.k.h()};q.add=function(a){this.k.set(Lb(a),a)};q.ca=function(a){a=Ib(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};q.remove=function(a){return this.k.remove(Lb(a))};q.clear=function(){this.k.clear()};q.S=function(){return this.k.S()};
q.contains=function(a){a=Lb(a);return Object.prototype.hasOwnProperty.call(this.k.k,a)};function Mb(a,b){for(var c=new U,d=Ib(b),e=0;e<d.length;e++){var f=d[e];a.contains(f)&&c.add(f)}return c}function Nb(a,b){for(var c=a.$(),d=Ib(b),e=d.length,f=0;f<e;f++)c.remove(d[f]);return c}q.F=function(){return this.k.F()};q.$=function(){return new U(this)};q.I=function(){return this.k.I(n)};function Ob(a){if(a!=m)try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new M;return a}
function Pb(a,b,c){var d=m;if(a.hasOwnProperty("adj"))try{return d=Qb(a.adj,b,a.m()),"graph"in a&&"object"===r(a.graph)&&(d.graph=db(a.graph)),"node"in a&&"object"===r(a.node)&&(d.node=Wa(a.node,function(a){return db(a)})),d}catch(e){h(Error("Input is not a correct jsnx graph"))}if("object"===r(a))try{return Qb(a,b,c)}catch(f){try{return Rb(a,b)}catch(g){h(Error("Input is not known type."))}}if(t(a))try{return Sb(a,b)}catch(l){h(Error("Input is not valid edge list"))}return d}
v("jsnx.to_networkx_graph",Pb);v("jsnx.convert_to_undirected",function(a){return a.O()});v("jsnx.convert_to_undirected",function(a){return a.C()});v("jsnx.to_dict_of_lists",function(a,b){function c(a){return 0<=sa(b,a)}var d={};b!=m?b=P(b):(b=a,c=function(a){return b.l(a)});N(b,function(b){d[b]=ta(a.K(b),c)});return d});
function Rb(a,b){var c=Ob(b);c.j(a);if(c.m()&&!c.c()){var d={};D(a,function(a,b){z(a,function(a){a in d||c.a(b,a)});d[b]=1})}else{var e=[];D(a,function(a,b){z(a,function(a){e.push([b,a])})});c.b(e)}return c}
function Qb(a,b,c){var d=Ob(b),e,f;d.j(a);c?d.c()?(d.m()?(e=[],D(a,function(a,b){t(a)&&h(Error());D(a,function(a,c){D(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],D(a,function(a,b){t(a)&&h(Error());D(a,function(a,c){D(a,function(a){e.push([b,c,a])})})})),d.b(e)):d.m()?(f=new U,D(a,function(a,b){t(a)&&h(Error());D(a,function(a,c){f.contains([b,c].toString())||(e=[],D(a,function(a,d){e.push([b,c,d,a])}),d.b(e),f.add([c,b].toString()))})})):(f=new U,D(a,function(a,b){t(a)&&h(Error());D(a,function(a,
c){f.contains([b,c].toString())||(e=[],D(a,function(a){e.push([b,c,a])}),d.b(e),f.add([c,b].toString()))})})):d.m()&&!d.c()?(f=new U,D(a,function(a,b){t(a)&&h(Error());D(a,function(a,c){f.contains([b,c].toString())||(d.a(b,c,a),f.add([c,b].toString()))})})):(e=[],D(a,function(a,b){t(a)&&h(Error());D(a,function(a,c){e.push([b,c,a])})}),d.b(e));return d}function Sb(a,b){var c=Ob(b);c.b(a);return c};function Vb(a){this.name="JSNetworkXException";this.message=a}Vb.prototype=Error();Vb.prototype.constructor=Vb;v("jsnx.JSNetworkXException",Vb);function X(a){Vb.call(this,a);this.name="JSNetworkXError"}ra(X,Vb);v("jsnx.JSNetworkXError",X);function Wb(a){Vb.call(this,a);this.name="JSNetworkXPointlessConcept"}ra(Wb,Vb);v("jsnx.JSNetworkXPointlessConcept",Wb);function Xb(a){Vb.call(this,a);this.name="JSNetworkXAlgorithmError"}ra(Xb,Vb);v("jsnx.JSNetworkXAlgorithmError",Xb);
function Yb(a){Xb.call(this,a);this.name="JSNetworkXUnfeasible"}ra(Yb,Xb);v("jsnx.JSNetworkXUnfeasible",Yb);function Zb(a){Yb.call(this,a);this.name="JSNetworkXNoPath"}ra(Zb,Yb);v("jsnx.JSNetworkXNoPath",Zb);function $b(a){Xb.call(this,a);this.name="JSNetworkXUnbounded"}ra($b,Xb);v("jsnx.JSNetworkXUnbounded",$b);function ac(a){var b=[];bc(new cc,a,b);return b.join("")}function cc(){this.ba=aa}
function bc(a,b,c){switch(typeof b){case "string":dc(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if(ha(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],bc(a,a.ba?a.ba.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),dc(f,c),c.push(":"),
bc(a,a.ba?a.ba.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var ec={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},fc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function dc(a,b){b.push('"',a.replace(fc,function(a){if(a in ec)return ec[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ec[a]=e+b.toString(16)}),'"')};function M(a,b){if(!(this instanceof M))return new M(a,b);this.graph={};this.node={};this.adj={};a!=m&&Pb(a,this);I(this.graph,b||{});this.edge=this.adj}v("jsnx.classes.Graph",M);v("jsnx.Graph",M);M.__name__="Graph";M.prototype.za=m;M.prototype.graph=M.prototype.za;M.prototype.ka=m;M.prototype.node=M.prototype.ka;M.prototype.ta=m;M.prototype.adj=M.prototype.ta;M.prototype.xa=m;M.prototype.edge=M.prototype.xa;
M.prototype.name=function(a){if(s(a))this.graph.name=a.toString();else return this.graph.name||""};M.prototype.name=M.prototype.name;M.prototype.toString=function(){return this.name()};M.prototype.toString=M.prototype.toString;M.prototype.i=function(a){a in this.adj||h({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};M.prototype.get_node=M.prototype.i;
M.prototype.D=function(a,b){b!=m||(b={});"object"!==r(b)&&h(new X("The attr_dict argument must be an object."));a in this.adj?I(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};M.prototype.add_node=M.prototype.D;M.prototype.j=function(a,b){var c,d,e,f,g;b!=m||(b={});N(a,function(a){c=!(a in this.adj);ha(a)?(d=a[0],e=a[1],d in this.adj?(g=this.node[d],I(g,b,e)):(this.adj[d]={},f=db(b),I(f,e),this.node[d]=f)):c?(this.adj[a]={},this.node[a]=db(b)):I(this.node[a],b)},this)};
M.prototype.add_nodes_from=M.prototype.j;M.prototype.N=function(a){var b=this.adj,c;a in this.node||h(new X("The node "+a+" is not in the graph"));c=F(b[a]);G(this.node,a);z(c,function(c){G(b[c],a)});G(b,a)};M.prototype.remove_node=M.prototype.N;M.prototype.X=function(a){var b=this.adj;N(a,function(a){try{G(this.node,a),D(b[a],function(d,f){G(b[f],a)}),G(b,a)}catch(d){}},this)};M.prototype.remove_nodes_from=M.prototype.X;M.prototype.v=function(a){return a?T(this.node):K(F(this.adj))};
M.prototype.nodes_iter=M.prototype.v;M.prototype.nodes=function(a){return Ua(this.v(a))};M.prototype.nodes=M.prototype.nodes;M.prototype.M=function(){return E(this.adj)};M.prototype.number_of_nodes=M.prototype.M;M.prototype.A=function(){return E(this.adj)};M.prototype.order=M.prototype.A;M.prototype.l=function(a){return!ha(a)&&a in this.adj};M.prototype.has_node=M.prototype.l;
M.prototype.a=function(a,b,c){c=c||{};"object"!==r(c)&&h(new X("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=H(this.adj[a],b+"",{});I(d,c);this.adj[a][b]=d;this.adj[b][a]=d};M.prototype.add_edge=M.prototype.a;
M.prototype.b=function(a,b){b=b||{};"object"!==r(b)&&h(new X("The attr_dict argument must be an object."));N(a,function(a){var d=ib(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new X("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});f in this.adj||(this.adj[f]={},this.node[f]={});a=H(this.adj[e],f,{});I(a,b,g);this.adj[e][f]=a;this.adj[f][e]=a},this)};M.prototype.add_edges_from=M.prototype.b;
M.prototype.sa=function(a,b,c){c=c||{};u(b)||(c=b,b="weight");this.b(O(a,function(a){var c={};c[b]=a[2];s(c[b])||h(new TypeError("Values must consist of three elements: "+ac(a)));return[a[0],a[1],c]}),c)};M.prototype.add_weighted_edges_from=M.prototype.sa;M.prototype.u=function(a,b){try{G(this.adj[a],b),a!=b&&G(this.adj[b],a)}catch(c){c instanceof TypeError&&h(new X("The edge "+a+"-"+b+" is not in the graph")),h(c)}};M.prototype.remove_edge=M.prototype.u;
M.prototype.B=function(a){N(a,function(a){var c=a[0];a=a[1];c in this.adj&&a in this.adj[c]&&(G(this.adj[c],a),c!=a&&G(this.adj[a],c))},this)};M.prototype.remove_edges_from=M.prototype.B;M.prototype.J=function(a,b){return a in this.adj&&b in this.adj[a]};M.prototype.has_edge=M.prototype.J;M.prototype.K=function(a){a in this.adj||h(new X("The node "+a+" is not in the graph."));return P(this.adj[a])};M.prototype.neighbors=M.prototype.K;
M.prototype.V=function(a){a in this.adj||h(new X("The node "+a+" is not in the graph."));return K(this.adj[a])};M.prototype.neighbors_iter=M.prototype.V;M.prototype.t=function(a,b){return Ua(this.e(a,b))};M.prototype.edges=M.prototype.t;
M.prototype.e=function(a,b){ia(a)&&(b=a,a=m);var c={},d,e;d=a!=m?O(this.d(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b?R(d,function(a){e=a[0];var b=new B,d=T(a[1]);b.next=function(){try{return d.next()}catch(a){a===A&&(c[e]=1),h(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):R(d,function(a){e=a[0];var b=new B,d=K(a[1]);b.next=function(){try{return d.next()}catch(a){a===A&&(c[e]=1),h(a)}};return b},function(a){if(!(a in c))return[e,a]})};
M.prototype.edges_iter=M.prototype.e;M.prototype.P=function(a,b,c){s(c)||(c=m);return a in this.adj?H(this.adj[a],b.toString(),c):c};M.prototype.get_edge_data=M.prototype.P;M.prototype.ua=function(){return P(O(this.s(),function(a){return F(a[1])}))};M.prototype.adjacency_list=M.prototype.ua;M.prototype.s=function(){return T(this.adj)};M.prototype.adjacency_iter=M.prototype.s;M.prototype.o=function(a,b){return a!=m&&this.l(a)?this.p(a,b).next()[1]:gb(Ua(this.p(a,b)))};M.prototype.degree=M.prototype.o;
M.prototype.p=function(a,b){var c;c=a!=m?O(this.d(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b?O(c,function(a){var c=a[0];a=a[1];var f=0,g;for(g in a)f+=+H(a[g],b,1);f+=+(c in a&&H(a[c],b,1));return[c,f]}):O(c,function(a){return[a[0],E(a[1])+ +(a[0]in a[1])]})};M.prototype.degree_iter=M.prototype.p;M.prototype.clear=function(){this.name("");$a(this.adj);$a(this.node);$a(this.graph)};M.prototype.clear=M.prototype.clear;M.prototype.copy=function(){return qb(this)};
M.prototype.copy=M.prototype.copy;M.prototype.m=da(n);M.prototype.is_multigraph=M.prototype.m;M.prototype.c=da(n);M.prototype.is_directed=M.prototype.c;M.prototype.C=function(){var a=new Y;a.name(this.name());a.j(this);a.b(function(){var a;return R(this.s(),function(c){a=c[0];return T(c[1])},function(c){return[a,c[0],S(c[1])]})}.call(this));a.graph=S(this.graph);a.node=S(this.node);return a};M.prototype.to_directed=M.prototype.C;M.prototype.O=function(){return qb(this)};
M.prototype.to_undirected=M.prototype.O;M.prototype.w=function(a){a=this.d(a);var b=new this.constructor,c=b.adj,d=this.adj;N(a,function(a){var b={};c[a]=b;D(d[a],function(d,l){l in c&&(b[l]=d,c[l][a]=d)})});N(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};M.prototype.subgraph=M.prototype.w;M.prototype.Ea=function(){return ua(ta(pb(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};M.prototype.nodes_with_selfloops=M.prototype.Ea;
M.prototype.Y=function(a){return a?ua(ta(pb(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):ua(ta(pb(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};M.prototype.selfloop_edges=M.prototype.Y;M.prototype.Fa=function(){return this.Y().length};M.prototype.number_of_selfloops=M.prototype.Fa;M.prototype.size=function(a){var b=J.q.apply(m,Ya(this.o(m,a)))/2;return a!=m?b:Math.floor(b)};M.prototype.size=M.prototype.size;
M.prototype.L=function(a,b){return a==m?Math.floor(this.size()):b in this.adj[a]?1:0};M.prototype.number_of_edges=M.prototype.L;M.prototype.ra=function(a,b){var c=P(a),d=c[0],c=O(Ga(c,1),function(a){return[d,a]});this.b(c,b)};M.prototype.add_star=M.prototype.ra;M.prototype.qa=function(a,b){var c=P(a),c=Oa(Ga(c,0,c.length-1),Ga(c,1));this.b(c,b)};M.prototype.add_path=M.prototype.qa;M.prototype.pa=function(a,b){var c=P(a),c=Oa(c,Aa(Ga(c,1),[c[0]]));this.b(c,b)};M.prototype.add_cycle=M.prototype.pa;
M.prototype.d=function(a){return a!=m?this.l(a)?K([a.toString()]):function(a,c){var d=new B,e=R(a,function(a){if(a in c)return a.toString()});d.next=function(){try{return e.next()}catch(a){a instanceof TypeError&&h(new X("nbunch is not a node or a sequence of nodes")),h(a)}};return d}(a,this.adj):K(this.adj)};M.prototype.nbunch_iter=M.prototype.d;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;a!=m&&Pb(a,this);I(this.graph,b||{});this.edge=this.adj}v("jsnx.classes.DiGraph",Y);v("jsnx.DiGraph",Y);ra(Y,M);Y.__name__="DiGraph";Y.prototype.D=function(a,b){b!=m||(b={});"object"!==r(b)&&h(new X("The attr_dict argument must be an object."));a in this.succ?I(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};Y.prototype.add_node=Y.prototype.D;
Y.prototype.j=function(a,b){var c,d,e,f,g;b!=m||(b={});N(K(a),function(a){c=!(a in this.succ);ha(a)?(d=a[0],e=a[1],d in this.succ?(g=this.node[d],I(g,b,e)):(this.succ[d]={},this.pred[d]={},f=db(b),I(f,e),this.node[d]=f)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=db(b)):I(this.node[a],b)},this)};Y.prototype.add_nodes_from=Y.prototype.j;
Y.prototype.N=function(a){a in this.node||h(new X("The node "+a+" is not in the graph"));var b=this.succ[a];G(this.node,a);D(b,function(b,d){G(this.pred[d],a)},this);G(this.succ,a);D(this.pred[a],function(b,d){G(this.succ[d],a)},this);G(this.pred,a)};Y.prototype.remove_node=Y.prototype.N;
Y.prototype.X=function(a){var b;N(a,function(a){a in this.succ&&(b=this.succ[a],G(this.node,a),D(b,function(b,e){G(this.pred[e],a)},this),G(this.succ,a),D(this.pred[a],function(b,e){G(this.succ[e],a)},this),G(this.pred,a))},this)};Y.prototype.remove_nodes_from=Y.prototype.X;
Y.prototype.a=function(a,b,c){c=c||{};"object"!==r(c)&&h(new X("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=H(this.adj[a],""+b,{});I(d,c);this.succ[a][b]=d;this.pred[b][a]=d};Y.prototype.add_edge=Y.prototype.a;
Y.prototype.b=function(a,b){b=b||{};"object"!==r(b)&&h(new X("The attr_dict argument must be an object."));N(a,function(a){var d=ib(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new X("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});f in this.succ||(this.succ[f]={},this.pred[f]={},this.node[f]={});a=H(this.adj[e],f,{});I(a,b,g);this.succ[e][f]=a;this.pred[f][e]=a},this)};
Y.prototype.add_edges_from=Y.prototype.b;Y.prototype.u=function(a,b){try{G(this.succ[a],b),G(this.pred[b],a)}catch(c){c instanceof TypeError&&h(new X("The edge "+a+"-"+b+" is not in the graph")),h(c)}};Y.prototype.remove_edge=Y.prototype.u;Y.prototype.B=function(a){N(a,function(a){var c=a[0];a=a[1];c in this.succ&&a in this.succ[c]&&(G(this.succ[c],a),G(this.pred[a],c))},this)};Y.prototype.remove_edges_from=Y.prototype.B;Y.prototype.Ba=function(a,b){return a in this.succ&&b in this.succ[a]};
Y.prototype.has_successor=Y.prototype.Ba;Y.prototype.Aa=function(a,b){return a in this.pred&&b in this.pred[a]};Y.prototype.has_predecessor=Y.prototype.Aa;Y.prototype.fa=function(a){a in this.succ||h(new X("The node "+a+" is not in the digraph."));return K(this.succ[a])};Y.prototype.successors_iter=Y.prototype.fa;Y.prototype.ma=function(a){a in this.pred||h(new X("The node "+a+" is not in the digraph."));return K(this.pred[a])};Y.prototype.predecessors_iter=Y.prototype.ma;
Y.prototype.na=function(a){a in this.succ||h(new X("The node "+a+" is not in the digraph."));return P(this.succ[a])};Y.prototype.successors=Y.prototype.na;Y.prototype.Ga=function(a){a in this.succ||h(new X("The node "+a+" is not in the digraph."));return P(this.pred[a])};Y.prototype.predecessors=Y.prototype.Ga;Y.prototype.K=Y.prototype.na;Y.prototype.neighbors=Y.prototype.K;Y.prototype.V=Y.prototype.fa;Y.prototype.neighbors_iter=Y.prototype.V;
Y.prototype.e=function(a,b){ia(a)&&(b=a,a=m);var c,d,e;c=a!=m?O(this.d(a),function(a){return[a,this.adj[a]]},this):pb(this.adj);return b?R(c,function(a){d=a[0];e=a[1];return T(e)},function(a){return[d,a[0],a[1]]}):R(c,function(a){d=a[0];e=a[1];return T(e)},function(a){return[d,a[0]]})};Y.prototype.edges_iter=Y.prototype.e;Y.prototype.aa=Y.prototype.e;Y.prototype.out_edges_iter=Y.prototype.aa;Y.prototype.da=M.prototype.t;Y.prototype.out_edges=Y.prototype.da;
Y.prototype.H=function(a,b){ia(a)&&(b=a,a=m);var c,d;c=a!=m?O(this.d(a),function(a){return[a,this.pred[a]]},this):pb(this.pred);return b?R(c,function(a){d=a[0];return T(a[1])},function(a){return[a[0],d,a[1]]}):R(c,function(a){d=a[0];return T(a[1])},function(a){return[a[0],d]})};Y.prototype.in_edges_iter=Y.prototype.H;Y.prototype.R=function(a,b){return P(this.H(a,b))};Y.prototype.in_edges=Y.prototype.R;
Y.prototype.p=function(a,b){var c;c=a!=m?kb(O(this.d(a),function(a){return[a,this.succ[a]]},this),O(this.d(a),function(a){return[a,this.pred[a]]},this)):kb(T(this.succ),T(this.pred));return u(b)?O(c,function(a){var c=a[0][1],f=a[1][1],g=0,l;for(l in c)g+=+H(c[l],b,1);for(l in f)g+=+H(f[l],b,1);return[a[0][0],g]}):O(c,function(a){return[a[0][0],ib(a[0][1])+ib(a[1][1])]})};Y.prototype.degree_iter=Y.prototype.p;
Y.prototype.Q=function(a,b){var c;c=a!=m?O(this.d(a),function(a){return[a,this.pred[a]]},this):T(this.pred);return b!=m?O(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+H(f[g],b,1);return[a[0],c]}):O(c,function(a){return[a[0],E(a[1])]})};Y.prototype.in_degree_iter=Y.prototype.Q;
Y.prototype.W=function(a,b){var c;c=a!=m?O(this.d(a),function(a){return[a,this.succ[a]]},this):T(this.succ);return b!=m?O(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+H(f[g],b,1);return[a[0],c]}):O(c,function(a){return[a[0],E(a[1])]})};Y.prototype.out_degree_iter=Y.prototype.W;Y.prototype.ia=function(a,b){return a!=m&&this.l(a)?this.Q(a,b).next()[1]:gb(this.Q(a,b))};Y.prototype.in_degree=Y.prototype.ia;Y.prototype.la=function(a,b){return a!=m&&this.l(a)?this.W(a,b).next()[1]:gb(this.W(a,b))};
Y.prototype.out_degree=Y.prototype.la;Y.prototype.clear=function(){$a(this.succ);$a(this.pred);$a(this.node);$a(this.graph)};Y.prototype.clear=Y.prototype.clear;Y.prototype.m=da(n);Y.prototype.is_multigraph=Y.prototype.m;Y.prototype.c=da(k);Y.prototype.is_directed=Y.prototype.c;Y.prototype.C=function(){return qb(this)};Y.prototype.to_directed=Y.prototype.C;
Y.prototype.O=function(a){var b=new M;b.name(this.name());b.j(this);var c=this.pred,d;a?b.b(R(this.s(),function(a){d=a[0];return T(a[1])},function(a){if(a[0]in c[d])return[d,a[0],S(a[1])]})):b.b(R(this.s(),function(a){d=a[0];return T(a[1])},function(a){return[d,a[0],S(a[1])]}));b.graph=S(this.graph);b.node=S(this.node);return b};Y.prototype.to_undirected=Y.prototype.O;
Y.prototype.reverse=function(a){(a=!s(a)||a)?(a=new this.constructor(m,{name:"Reverse of ("+this.name()+")"}),a.j(this),a.b(O(this.e(m,k),function(a){return[a[1],a[0],S(a[2])]})),a.graph=S(this.graph),a.node=S(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Y.prototype.reverse=Y.prototype.reverse;
Y.prototype.w=function(a){a=this.d(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;N(a,function(a){c[a]={};d[a]={}});N(c,function(a){var b=c[a];D(e[a],function(e,p){p in c&&(b[p]=e,d[p][a]=e)})});N(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.w;function gc(a,b){var c=Q(a),d,e,f=new B;try{e=[c.next()]}catch(g){return g!==A&&h(g),f}f.next=function(){0===e.length&&h(A);return e.splice(0,1)[0]};return R(f,function(a){d=a;return Q(b)},function(){try{var a=c.next();e.push(a);return[d,a]}catch(b){b!==A&&h(b)}})}function hc(a,b,c){c=ic(b,c);c.b(gc(b,a));return c}v("jsnx.generators.classic.full_rary_tree",hc);v("jsnx.full_rary_tree",hc);function jc(a,b,c){b=1===a?2:Math.floor((1-Math.pow(a,b+1))/(1-a));c=ic(b,c);c.b(gc(b,a));return c}
v("jsnx.generators.classic.balanced_tree",jc);v("jsnx.balanced_tree",jc);function kc(a,b){var c=ic(a,b);c.name("complete_graph("+a+")");1<a&&c.b(c.c()?nb(Q(a)):mb(Q(a)));return c}v("jsnx.generators.classic.complete_graph",kc);v("jsnx.complete_graph",kc);function lc(a,b){var c=mc(a,b);c.name("cycle_graph("+a+")");1<a&&c.a(a-1,0);return c}v("jsnx.generators.classic.cycle_graph",lc);v("jsnx.cycle_graph",lc);
function ic(a,b){a instanceof M&&(b=a,a=m);a!=m||(a=0);var c;b!=m?(c=b,c.clear()):c=new M;c.j(Q(a));c.name("empty_graph("+a+")");return c}v("jsnx.generators.classic.empty_graph",ic);v("jsnx.empty_graph",ic);
function nc(a,b,c,d){var e=ic(0,d);e.name("grid_2d_graph");d=Ua(Q(a));var f=Ua(Q(b));z(d,function(a){z(f,function(b){e.D([a,b].toString())})});C(Q(1,a),function(a){z(f,function(b){e.a([a,b].toString(),[a-1,b].toString())})});z(d,function(a){C(Q(1,b),function(b){e.a([a,b].toString(),[a,b-1].toString())})});e.c()&&(C(Q(0,a-1),function(a){z(f,function(b){e.a([a,b].toString(),[a+1,b].toString())})}),z(d,function(a){C(Q(0,b-1),function(b){e.a([a,b].toString(),[a,b+1].toString())})}));c&&(2<b&&(z(d,function(a){e.a([a,
0].toString(),[a,b-1].toString())}),e.c()&&z(d,function(a){e.a([a,b-1].toString(),[a,0].toString())})),2<a&&(z(f,function(b){e.a([0,b].toString(),[a-1,b].toString())}),e.c()&&z(f,function(b){e.a([a-1,b].toString(),[0,b].toString())})),e.name("periodic_grid_2d_graph("+a+","+b+")"));return e}v("jsnx.generators.classic.grid_2d_graph",nc);v("jsnx.grid_2d_graph",nc);function oc(a){a=ic(0,a);a.name("null_graph()");return a}v("jsnx.generators.classic.null_graph",oc);v("jsnx.null_graph",oc);
function mc(a,b){var c=ic(a,b);c.name("path_graph("+a+")");c.b(Ra(Q(a-1),function(a){return[a,a+1]}));return c}v("jsnx.generators.classic.path_graph",mc);v("jsnx.path_graph",mc);function pc(a){a=ic(1,a);a.name("null_graph()");return a}v("jsnx.generators.classic.trivial_graph",pc);v("jsnx.trivial_graph",pc);v("jsnx.fast_gnp_random_graph",function(a,b,c){c!=m||(c=n);var d=ic(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return qc(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=new Y(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.a(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.a(e,f)}return d});
function qc(a,b,c){var d;d=c?new Y:new M;d.j(Q(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return kc(a,d);a=d.c()?nb(Q(a)):mb(Q(a));C(a,function(a){Math.random()<b&&d.a(a[0],a[1])});return d}v("jsnx.gnp_random_graph",qc);v("jsnx.binomial_graph",qc);v("jsnx.erdos_renyi_graph",qc);v("jsnx.havel_hakimi_graph",function(a,b){rc(a)||h(new X("Invalid degree sequence"));b!=m&&(b.c()&&h(new X("Directed Graph not supported")),b.m()&&h(new X("Havel-Hakimi requires simple graph")));var c=a.length,d=ic(c,b);if(0===c||0===Math.max.apply(m,a))return d;for(c=Ua(O(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return n;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return n;for(var f=c.length,g=f-e[0];g<f;g++)d.a(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.A()+" nodes "+d.size()+" edges");return d});function sc(){var a=new M;a.j(Q(34));a.name("Zachary's Karate Club");var b=0;z("0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0;1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0;1 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0;1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1;0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1;0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 1 1 0 1;0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0".split(";"),
function(c){N(c.split(" "),function(c,e){"1"===c&&a.a(b,e)});b+=1});return a}v("jsnx.generators.social.karate_club_graph",sc);v("jsnx.karate_club_graph",sc);
function tc(){var a=new M;a.j("Evelyn Jefferson;Laura Mandeville;Theresa Anderson;Brenda Rogers;Charlotte McDowd;Frances Anderson;Eleanor Nye;Pearl Oglethorpe;Ruth DeSand;Verne Sanderson;Myra Liddel;Katherina Rogers;Sylvia Avondale;Nora Fayette;Helen Lloyd;Dorothy Murchison;Olivia Carleton;Flora Price".split(";"),{wa:0});a.j("E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14".split(" "),{wa:1});a.b([["Evelyn Jefferson","E1"],["Evelyn Jefferson","E2"],["Evelyn Jefferson","E3"],["Evelyn Jefferson","E4"],
["Evelyn Jefferson","E5"],["Evelyn Jefferson","E6"],["Evelyn Jefferson","E8"],["Evelyn Jefferson","E9"],["Laura Mandeville","E1"],["Laura Mandeville","E2"],["Laura Mandeville","E3"],["Laura Mandeville","E5"],["Laura Mandeville","E6"],["Laura Mandeville","E7"],["Laura Mandeville","E8"],["Theresa Anderson","E2"],["Theresa Anderson","E3"],["Theresa Anderson","E4"],["Theresa Anderson","E5"],["Theresa Anderson","E6"],["Theresa Anderson","E7"],["Theresa Anderson","E8"],["Theresa Anderson","E9"],["Brenda Rogers",
"E1"],["Brenda Rogers","E3"],["Brenda Rogers","E4"],["Brenda Rogers","E5"],["Brenda Rogers","E6"],["Brenda Rogers","E7"],["Brenda Rogers","E8"],["Charlotte McDowd","E3"],["Charlotte McDowd","E4"],["Charlotte McDowd","E5"],["Charlotte McDowd","E7"],["Frances Anderson","E3"],["Frances Anderson","E5"],["Frances Anderson","E6"],["Frances Anderson","E8"],["Eleanor Nye","E5"],["Eleanor Nye","E6"],["Eleanor Nye","E7"],["Eleanor Nye","E8"],["Pearl Oglethorpe","E6"],["Pearl Oglethorpe","E8"],["Pearl Oglethorpe",
"E9"],["Ruth DeSand","E5"],["Ruth DeSand","E7"],["Ruth DeSand","E8"],["Ruth DeSand","E9"],["Verne Sanderson","E7"],["Verne Sanderson","E8"],["Verne Sanderson","E9"],["Verne Sanderson","E12"],["Myra Liddel","E8"],["Myra Liddel","E9"],["Myra Liddel","E10"],["Myra Liddel","E12"],["Katherina Rogers","E8"],["Katherina Rogers","E9"],["Katherina Rogers","E10"],["Katherina Rogers","E12"],["Katherina Rogers","E13"],["Katherina Rogers","E14"],["Sylvia Avondale","E7"],["Sylvia Avondale","E8"],["Sylvia Avondale",
"E9"],["Sylvia Avondale","E10"],["Sylvia Avondale","E12"],["Sylvia Avondale","E13"],["Sylvia Avondale","E14"],["Nora Fayette","E6"],["Nora Fayette","E7"],["Nora Fayette","E9"],["Nora Fayette","E10"],["Nora Fayette","E11"],["Nora Fayette","E12"],["Nora Fayette","E13"],["Nora Fayette","E14"],["Helen Lloyd","E7"],["Helen Lloyd","E8"],["Helen Lloyd","E10"],["Helen Lloyd","E11"],["Helen Lloyd","E12"],["Dorothy Murchison","E8"],["Dorothy Murchison","E9"],["Olivia Carleton","E9"],["Olivia Carleton","E11"],
["Flora Price","E9"],["Flora Price","E11"]]);return a}v("jsnx.generators.social.davis_southern_women_graph",tc);v("jsnx.davis_southern_women_graph",tc);
function uc(){var a=new M;a.a("Acciaiuoli","Medici");a.a("Castellani","Peruzzi");a.a("Castellani","Strozzi");a.a("Castellani","Barbadori");a.a("Medici","Barbadori");a.a("Medici","Ridolfi");a.a("Medici","Tornabuoni");a.a("Medici","Albizzi");a.a("Medici","Salviati");a.a("Salviati","Pazzi");a.a("Peruzzi","Strozzi");a.a("Peruzzi","Bischeri");a.a("Strozzi","Ridolfi");a.a("Strozzi","Bischeri");a.a("Ridolfi","Tornabuoni");a.a("Tornabuoni","Guadagni");a.a("Albizzi","Ginori");a.a("Albizzi","Guadagni");a.a("Bischeri",
"Guadagni");a.a("Guadagni","Lamberteschi");return a}v("jsnx.generators.social.florentine_families_graph",uc);v("jsnx.florentine_families_graph",uc);function vc(a,b){a.c()&&h(new X("triangles() is not defined for directed graphs."));if(b!=m&&a.l(b))return Math.floor(wc(a,b).next()[2]/2);var c={};C(wc(a,b),function(a){c[a[0]]=Math.floor(a[2]/2)});return c}v("jsnx.triangles",vc);
function wc(a,b){a.m()&&h(new X("Not defined for multigraphs."));var c;c=b!=m?R(a.d(b),function(b){return[b,a.i(b)]}):T(a.adj);return Ra(c,function(b){var c=new U(F(b[1])),f=0;c.remove(b[0]);C(c,function(b){var d=new U(F(a.i(b)));d.remove(b);f+=Mb(c,d).h()});return[b[0],c.h(),f]})}
function xc(a,b,c){a.m()&&h(new X("Not defined for multigraphs."));u(c)||(c="weight");var d;d=0===a.t().length?1:lb(a.t(k),function(a){return H(a[2],c,1)});b=b!=m?R(a.d(b),function(b){return[b,a.i(b)]}):T(a.adj);return Ra(b,function(b){var f=b[0],g=new U(F(b[1]));g.remove(f);var l=0,p=new U;C(g,function(b){var e=H(a.i(f)[b],c,1)/d;p.add(b);var L=Nb(new U(F(a.i(b))),p);C(Mb(g,L),function(g){var p=H(a.i(b)[g],c,1)/d;g=H(a.i(f)[g],c,1)/d;l+=Math.pow(e*p*g,1/3)})});return[f,g.h(),2*l]})}
v("jsnx.average_clustering",function(a,b,c,d){2===arguments.length?u(b)?(c=b,b=m):ia(b)&&(d=b,b=m):3===arguments.length&&ia(c)&&(d=c,c=m);d!=m||(d=k);var e=Ya(yc(a,b,c));d||(e=ta(e,function(a){return 0<a}));return J.q.apply(J,e)/e.length});function yc(a,b,c){a.c()&&h(new X("Clustering algorithms are not defined for directed graphs."));c=c!=m?xc(a,b,c):wc(a,b);var d={};C(c,function(a){d[a[0]]=0===a[2]?0:a[2]/(a[1]*(a[1]-1))});return b!=m&&a.l(b)?Ya(d)[0]:d}v("jsnx.clustering",yc);
v("jsnx.transitivity",function(a){var b=0,c=0;C(wc(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c});v("jsnx.square_clustering",function(a,b){var c=b==m?K(a):a.d(b),d={};C(c,function(b){var c=d[b]=0;C(mb(F(a.i(b))),function(g){var l=g[0];g=g[1];var p=Mb(new U(F(a.i(l))),F(a.i(g)));p.remove(b);p=p.h();d[b]+=p;var y=p+1,x=a.i(l);g in x&&(y+=1);c+=(E(a.i(l))-y)*(E(a.i(g))-y)+p});0<c&&(d[b]/=c)});return b!=m&&a.l(b)?Ya(d)[0]:d});function zc(a){var b=-1,c={},d=new U;C(a.s(),function(a){var e=new U(F(a[1]));e.remove(a[0]);var f=e.h();f>b?(c[a[0]]=d=e,b=f):c[a[0]]=e});var e=new U(F(c)),f=Nb(e,d),g=new U,l=[],p=[];a=new B;a.next=function(){0===f.h()&&0===l.length&&h(A);var a,x;if(0<f.h())a=Qa(f).next(),f.remove(a);else{var L=l.pop();e=L[0];g=L[1];f=L[2];p.pop();return this.next()}p.push(a);e.remove(a);g.add(a);var V=c[a],L=Mb(e,V),V=Mb(g,V);if(0===L.h()&&(0===V.h()&&(x=Ba(p)),p.pop(),x))return x;if(0===V.h()&&1===L.h())return x=
Aa(p,L.F()),p.pop(),x;var Ia=L.h(),ba=-1,ca,W;for(x=Qa(V);(a=Va(x,m))!==m&&!(a=Mb(L,c[a]),W=a.h(),W>ba&&(ca=a,ba=W,ba===Ia)););if(ba===Ia)return p.pop(),this.next();b=-1;for(x=Qa(L);(a=Va(x,m))!==m&&!(a=Mb(L,c[a]),W=a.h(),W>b&&(d=a,b=W,b===Ia-1)););ba>b&&(d=ca);l.push([e,g,f]);e=L;g=V;f=Nb(e,d);return this.next()};return a}v("jsnx.find_cliques",zc);
v("jsnx.find_cliques_recursive",function(a){var b={};C(a.s(),function(a){var c=new U(F(a[1]));c.remove(a[0]);b[a[0]]=c});if(Za(b))return[];a=new U(F(b));var c=new U,d=[];Ac(b,a,c,[],d);return d});
function Ac(a,b,c,d,e){var f=-1,g=b.h(),l,p,y,x;for(p=Qa(c);(y=Va(p,m))!==m;)if(y=Mb(b,a[y]),x=y.h(),x>f&&(l=y,f=x,x===g))return;C(b,function(c){c=Mb(b,a[c]);var d=c.h();d>f&&(l=c,f=d)});g=Nb(b,l);C(g,function(f){b.remove(f);d.push(f);var g=a[f];f=Mb(b,g);g=Mb(c,g);f.S()&&g.S()?e.push(Ba(d)):g.S()&&1===f.h()?e.push(Aa(d,f.F())):Ac(a,f,g,d,e);c.add(d.pop())})}v("jsnx.graph_clique_number",function(a,b){b!=m||(b=zc(a));var c=0;N(b,function(a){c=a.length>c?a.length:c});return c});
v("jsnx.graph_number_of_cliques",function(a,b){b!=m||(b=zc(a));return P(b).length});function Bc(a,b,c){c=c!=m?Ua(c):Ua(zc(a));b!=m||(b=a.nodes());var d;if(ha(b))d={},z(b,function(a){d[a]=ta(c,function(b){return 0<=sa(b,a)||0<=sa(b,a+"")}).length});else{var e=b;d=ta(c,function(a){return 0<=sa(a,e)||0<=sa(a,e+"")}).length}return d}v("jsnx.number_of_cliques",Bc);function Cc(a,b){if(a.A()!=b.A())return n;var c,d=a.o(),e=vc(a),f=Bc(a),g=[];for(c in d)g.push([d[c],e[c],f[c]]);g.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var d=b.o(),e=vc(b),f=Bc(b),l=[];for(c in d)l.push([d[c],e[c],f[c]]);l.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return!Ha(g,l,function(a,b){return Ha(a,b)})?n:k}v("jsnx.algorithms.isomorphism.could_be_isomorphic",Cc);v("jsnx.could_be_isomorphic",Cc);
function Dc(a,b){if(a.A()!=b.A())return n;var c,d=a.o(),e=vc(a),f=[];for(c in d)f.push([d[c],e[c]]);f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var d=b.o(),e=vc(b),g=[];for(c in d)g.push([d[c],e[c]]);g.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return!Ha(f,g,function(a,b){return Ha(a,b)})?n:k}v("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",Dc);v("jsnx.fast_could_be_isomorphic",Dc);
function Ec(a,b){if(a.A()!=b.A())return n;var c=Ya(a.o());c.sort();var d=Ya(b.o());d.sort();return!Ha(c,d)?n:k}v("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",Ec);v("jsnx.faster_could_be_isomorphic",Ec);function Fc(){}Fc.ha=function(){return Fc.ja?Fc.ja:Fc.ja=new Fc};Fc.prototype.Da=0;Fc.ha();function Gc(a){if(!t(a))return n;for(var b=0,c=a.length;b<c;b++)if(window.isNaN(a[b]))return n;return k}v("jsnx.utils.is_list_of_ints",Gc);v("jsnx.utils.cumulative_sum",function(a){var b=0;return Ra(a,function(a){return b+=a})});v("jsnx.utils.generate_unique_node",function(){return":"+(Fc.ha().Da++).toString(36)});function rc(a,b){if("eg"===b)return Hc(a);if(b==m||"hh"===b)return Ic(a);h(new Vb("`opt_method` must be 'eg' or 'hh'"))}v("jsnx.is_valid_degree_sequence",rc);function Ic(a){if(0===a.length)return k;if(!Gc(a)||0>Math.min.apply(m,a)||0!==J.q.apply(m,a)%2)return n;for(a=Ba(a);0<a.length;){w.sort.call(a,Ma);if(0>a[0])break;var b=a.pop();if(0===b)return k;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return n}v("jsnx.is_valid_degree_sequence_havel_hakimi",Ic);
function Hc(a){if(0===a.length)return k;if(!Gc(a)||0>Math.min.apply(m,a)||0!==J.q.apply(m,a)%2)return n;var b=a.length,c=Ba(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=J.q.apply(m,c.slice(0,d[e])),g=d[e]*(d[e]-1)+J.q.apply(m,Ua(Ra(Q(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return n;return k}v("jsnx.is_valid_degree_sequence_erdos_gallai",Hc);function Jc(a){try{return Kc(a),k}catch(b){if(b instanceof Yb)return n;h(b)}}v("jsnx.algorithms.dag.is_directed_acyclic_graph",Jc);v("jsnx.is_directed_acyclic_graph",Jc);
function Kc(a,b){a.c()||h(new X("Topological sort not defined on undirected graphs."));var c={},d=[],e={};b!=m||(b=a.v());N(b,function(b){if(!(b in e))for(b=[b];0<b.length;){var g=b[b.length-1];if(g in e)b.pop();else{c[g]=k;var l=[];D(a.i(g),function(a,b){b in e||(b in c&&h(new Yb("Graph contains a cycle")),l.push(b))});0<l.length?b.push.apply(b,l):(e[g]=k,Fa(d,aa,0,g.toString()))}}});return d}v("jsnx.algorithms.dag.topological_sort",Kc);v("jsnx.topological_sort",Kc);
function Lc(a,b){function c(a,b,d,e){b.add(e);D(a.i(e),function(e,p){if(b.contains(p))b.contains(p)&&!(0<=sa(d,p))&&h(new Yb("Graph contains a cycle"));else if(!c(a,b,d,p))return n});Fa(d,aa,0,e.toString());return k}a.c()||h(new X("Topological sort not defined on undirected graphs."));var d=new U,e=[];b!=m||(b=a.v());N(b,function(b){!(0<=sa(e,b))&&!c(a,d,e,b)&&h(new Yb("Graph contains a cycle"))});return e}v("jsnx.algorithms.dag.topological_sort_recursive",Lc);
v("jsnx.topological_sort_recursive",Lc);var Nc=function Mc(b){b.c()||h(new X("is_aperiodic not defined for undirected graphs."));var c=b.v().next(),d={};d[c]=0;for(var c=[c],e=0,f=1;0<c.length;){var g=[];z(c,function(c){D(b.i(c),function(b,y){y in d?e=sb(e,d[c]-d[y]+1):(g.push(y),d[y]=f)})});c=g;f+=1}return ib(d)===ib(b)?1===e:1===e&&Mc(b.w(Nb(new U(b.nodes()),F(d))))};v("jsnx.algorithms.dag.is_aperiodic",Nc);v("jsnx.is_aperiodic",Nc);function Oc(a,b,c){var d={},e=0,f={};for(f[b]=1;0<E(f);){b=f;f={};D(b,function(b,c){c in d||(d[c]=e,I(f,a.i(c)))});if(ja(c)&&c<=e)break;e+=1}return d}v("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path_length",Oc);v("jsnx.single_source_shortest_path_length",Oc);function Pc(a,b){var c={};N(a,function(d){c[d]=Oc(a,d,b)});return c}v("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path_length",Pc);v("jsnx.all_pairs_shortest_path_length",Pc);
function Sc(a,b,c){b=b.toString();c=c.toString();c=Tc(a,b,c);a=c[0];b=c[1];c=c[2];for(var d=[];c!=m;)d.push(c),c=b[c];for(c=a[d[0]];c!=m;)d.unshift(c),c=a[c];return d}v("jsnx.algorithms.shortest_paths.unweighted.bidirectional_shortest_path",Sc);v("jsnx.bidirectional_shortest_path",Sc);
function Tc(a,b,c){(!s(b)||!s(c))&&h(new Vb("Bidirectional shortest path called without source or target"));var d={},e={};if(c===b)return d[c]=m,e[b]=m,[d,e,b];var f,g;a.c()?(f=a.ma,g=a.fa):g=f=a.V;d[b]=m;e[c]=m;for(var l=[b],p=[c],y,x;0<l.length&&0<p.length&&!x;)l.length<=p.length?(y=l,l=[],z(y,function(b){x||C(g.call(a,b),function(a){x||(a in d||(l.push(a),d[a]=b),a in e&&(x=[d,e,a]))})})):(y=p,p=[],z(y,function(b){x||C(f.call(a,b),function(a){x||(a in e||(e[a]=b,p.push(a)),a in d&&(x=[d,e,a]))})}));
if(x)return x;h(new Zb("No path between "+b+" and "+c+"."))}function Uc(a,b,c){b=b.toString();var d=0,e={};e[b]=1;var f={};f[b]=[b];if(0===c)return f;for(;0<E(e)&&!(b=e,e={},D(b,function(b,c){D(a.i(c),function(a,b){b in f||(f[b]=f[c].concat([b]),e[b]=1)})}),d+=1,s(c)&&c<=d););return f}v("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path",Uc);v("jsnx.single_source_shortest_path",Uc);function Vc(a,b){var c={};N(a,function(d){c[d]=Uc(a,d,b)});return c}
v("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path",Vc);v("jsnx.all_pairs_shortest_path",Vc);function Wc(a,b,c,d,e){b=b.toString();var f=0,g=[b],l={};l[b]=f;var p={};for(p[b]=[];0<g.length&&!(f+=1,b=g,g=[],z(b,function(b){D(a.i(b),function(a,c){c in l?l[c]===f&&p[c].push(b):(p[c]=[b],l[c]=f,g.push(c))})}),d!=m&&d<=f););return c!=m?(c=c.toString(),e?!(c in p)?[[],-1]:[p[c],l[c]]:!(c in p)?[]:p[c]):e?[p,l]:p}v("jsnx.algorithms.shortest_paths.unweighted.predecessor",Wc);
v("jsnx.predecessor",Wc);function Xc(a,b,c){var d=b;ka(b)&&(d={},C(a.v(),function(a){d[a]=b(a)}));return!s(c)||c?Yc(a,d):Zc(a,d)}v("jsnx.relabel_nodes",Xc);
function Zc(a,b){var c=new U(F(b)),d;if(0<Mb(c,b).h()){c=new Y(pb(b));c.B(c.Y());try{d=Kc(c)}catch(e){e instanceof Yb&&h(new Yb("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True."))}d.reverse()}else d=c;var f=a.m(),g=a.c(),l;C(d,function(c){var d;c in b&&(d=b[c],a.l(c)||h(new X("Node "+c+" is not in the graph.")),a.D(d,a.node[c]),f?(l=ua(a.t(c,k,k),function(a){return[d,a[1],a[2],a[3]]}),g&&(l=Aa(l,ua(a.R(c,k,k),function(a){return[a[0],d,a[2],a[3]]})))):(l=
ua(a.t(c,k),function(a){return[d,a[1],a[2]]}),g&&(l=Aa(l,ua(a.R(c,k),function(a){return[a[0],d,a[2]]})))),a.N(c),a.b(l))});return a}
function Yc(a,b){var c=new a.constructor;c.name("("+a.name()+")");a.m()?c.b(Ra(a.e(m,k,k),function(a){return[H(b,a[0],a[0]),H(b,a[1],a[1]),a[2],db(a[3])]})):c.b(Ra(a.e(m,k),function(a){return[H(b,a[0],a[0]),H(b,a[1],a[1]),db(a[2])]}));c.j(Ra(K(a),function(a){return H(b,a,a)}));var d={},e;for(e in a.node)d[H(b,e,e)]=db(a.node[e]);I(c.node,d);I(c.graph,db(a.graph));return c}
v("jsnx.convert_node_labels_to_integers",function(a,b,c,d){3===arguments.length&&ia(c)?(d=c,c=m):2===arguments.length&&(ia(b)?(d=b,b=m):u(b)&&(c=b,b=m));b!=m||(b=0);c!=m||(c="default");d!=m||(d=k);var e={},f,g,l,p;if("default"===c){f=a.nodes();g=0;l=b;for(p=f.length;g<p;g++,l++)e[f[g]]=l}else if("sorted"===c){f=a.nodes();f.sort();g=0;l=b;for(p=f.length;g<p;g++,l++)e[f[g]]=l}else if("increasing degree"===c){f=Ua(a.p());f.sort(function(a,b){return a[1]-b[1]});g=0;l=b;for(p=f.length;g<p;g++,l++)e[f[g][0]]=
l}else if("decreasing degree"===c){f=Ua(a.p());f.sort(function(a,b){return b[1]-a[1]});g=0;l=b;for(p=f.length;g<p;g++,l++)e[f[g][0]]=l}else h(new X("Unkown node ordering: "+c));g=Xc(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g});function Z(a,b){if(!(this instanceof Z))return new Z(a,b);M.call(this,a,b)}ra(Z,M);v("jsnx.classes.MultiGraph",Z);v("jsnx.MultiGraph",Z);Z.__name__="MultiGraph";
Z.prototype.a=function(a,b,c,d){var e,f;c!=m&&(!u(c)&&!ja(c))&&(d=c,c=m);d=d||{};"object"!==r(d)&&h(new X("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});if(b in this.adj[a]){f=this.adj[a][b];if(c==m)for(c=E(f);c in f;)c+=1;e=H(f,""+c,{});I(e,d);f[c]=e}else c!=m||(c=0),e={},I(e,d),f=fb(c,e),this.adj[a][b]=f,this.adj[b][a]=f};Z.prototype.add_edge=Z.prototype.a;
Z.prototype.b=function(a,b){b=b||{};"object"!==r(b)&&h(new X("The attr_dict argument must be an object."));N(a,function(a){var d=ib(a),e,f,g=m,l={};4===d?(e=a[0],f=a[1],g=a[2],l=a[3]):3===d?(e=a[0],f=a[1],l=a[2]):2===d?(e=a[0],f=a[1]):h(new X("Edge tuple "+ac(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=e in this.adj?H(this.adj[e],f,{}):{};if(g==m)for(g=E(a);g in a;)g+=1;a=H(a,g,{});I(a,b,l);this.a(e,f,g,a)},this)};Z.prototype.add_edges_from=Z.prototype.b;
Z.prototype.u=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new X("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=m?(c in d||h(new X("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),G(d,c)):G(d,Xa(d));0===E(d)&&(G(this.adj[a],b),a!=b&&G(this.adj[b],a))};Z.prototype.remove_edge=Z.prototype.u;Z.prototype.B=function(a){N(a,function(a){try{this.u(a[0],a[1],a[2])}catch(c){c instanceof X||h(c)}},this)};Z.prototype.remove_edges_from=Z.prototype.B;
Z.prototype.J=function(a,b,c){return c!=m?a in this.adj&&b in this.adj[a]&&c in this.adj[a][b]:a in this.adj&&b in this.adj[a]};Z.prototype.has_edge=Z.prototype.J;Z.prototype.t=function(a,b,c){return Ua(this.e(a,b,c))};Z.prototype.edges=Z.prototype.t;
Z.prototype.e=function(a,b,c){ia(a)&&(ia(b)&&(c=b),b=a,a=m);var d={},e,f;a=a!=m?O(this.d(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b?R(a,function(a){e=a[0];var b=new B,c=T(a[1]);b.next=function(){try{return c.next()}catch(a){a===A&&(d[e]=1),h(a)}};return b},function(a){f=a[0];if(!(f in d))return T(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):R(a,function(a){e=a[0];var b=new B,c=T(a[1]);b.next=function(){try{return c.next()}catch(a){a===A&&(d[e]=1),h(a)}};return b},
function(a){f=a[0];if(!(f in d))return T(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Z.prototype.edges_iter=Z.prototype.e;Z.prototype.P=function(a,b,c,d){s(d)||(d=m);return a in this.adj&&b in this.adj[a]?c!=m?H(this.adj[a][b],""+c,d):this.adj[a][b]:d};Z.prototype.get_edge_data=Z.prototype.P;
Z.prototype.p=function(a,b){var c;c=a!=m?O(this.d(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b!=m?Ra(c,function(a){var c=a[0];a=a[1];var f=0;D(a,function(a){D(a,function(a){f+=H(a,b,1)})});c in a&&D(a[c],function(a){f+=H(a,b,1)});return[c,f]}):Ra(c,function(a){var b=a[0];a=a[1];var c=0;D(a,function(a){c+=E(a)});return[b,c+ +(b in a&&E(a[b]))]})};Z.prototype.degree_iter=Z.prototype.p;Z.prototype.m=da(k);Z.prototype.is_multigraph=Z.prototype.m;Z.prototype.c=da(n);
Z.prototype.is_directed=Z.prototype.c;Z.prototype.C=function(){var a=new $;a.j(this);a.b(function(){var a,c;return R(this.s(),function(c){a=c[0];return T(c[1])},function(a){c=a[0];return T(a[1])},function(d){return[a,c,d[0],S(d[1])]})}.call(this));a.graph=S(this.graph);a.node=S(this.node);return a};Z.prototype.to_directed=Z.prototype.C;
Z.prototype.Y=function(a,b){var c=[];a?b?D(this.adj,function(a,b){b in a&&D(a[b],function(a,d){c.push([b,b,d,a])})}):D(this.adj,function(a,b){b in a&&D(a[b],function(a){c.push([b,b,a])})}):b?D(this.adj,function(a,b){b in a&&D(a[b],function(a,d){c.push([b,b,d])})}):D(this.adj,function(a,b){b in a&&D(a[b],function(){c.push([b,b])})});return c};Z.prototype.selfloop_edges=Z.prototype.Y;Z.prototype.L=function(a,b){return a==m?this.size():a in this.adj&&b in this.adj[a]?E(this.adj[a][b]):0};
Z.prototype.number_of_edges=Z.prototype.L;Z.prototype.w=function(a){a=this.d(a);var b=new this.constructor,c=b.adj,d=this.adj;C(a,function(a){var b={};c[a]=b;D(d[a],function(d,l){if(l in c){var p=db(d);b[l]=p;c[l][a]=p}})});D(this.node,function(a,c){b.node[c]=a});b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.w;function $(a,b){if(!(this instanceof $))return new $(a,b);Y.call(this,a,b)}ra($,Y);var $c=$.prototype,ad=Z.prototype,bd;for(bd in ad)ad.hasOwnProperty(bd)&&"constructor"!==bd&&($c[bd]=ad[bd]);v("jsnx.classes.MultiDiGraph",$);v("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";
$.prototype.a=function(a,b,c,d){var e,f;c!=m&&(!u(c)&&!ja(c))&&(d=c,c=m);d=d||{};"object"!==r(d)&&h(new X("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});if(b in this.succ[a]){f=this.adj[a][b];if(c==m)for(c=E(f);c in f;)c+=1;e=H(f,c.toString(),{});I(e,d);f[c]=e}else c!=m||(c=0),e={},I(e,d),f=fb(c,e),this.succ[a][b]=f,this.pred[b][a]=f};$.prototype.add_edge=$.prototype.a;
$.prototype.u=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new X("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=m?(c in d||h(new X("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),G(d,c)):G(d,Xa(d));0===E(d)&&(G(this.succ[a],b),G(this.pred[b],a))};$.prototype.remove_edge=$.prototype.u;
$.prototype.e=function(a,b,c){ia(a)&&(ia(b)&&(c=b),b=a,a=m);var d,e;a=a!=m?O(this.d(a),function(a){return[a,this.adj[a]]},this):pb(this.adj);return b?R(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):R(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};$.prototype.edges_iter=$.prototype.e;$.prototype.aa=$.prototype.e;$.prototype.out_edges_iter=$.prototype.aa;
$.prototype.da=function(a,b,c){return Ua(this.aa(a,b,c))};$.prototype.out_edges=$.prototype.da;$.prototype.H=function(a,b,c){ia(a)&&(b=a,a=m);var d,e;a=a!=m?O(this.d(a),function(a){return[a,this.pred[a]]},this):pb(this.pred);return b?R(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):R(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};$.prototype.in_edges_iter=$.prototype.H;
$.prototype.R=function(a,b,c){return Ua(this.H(a,b,c))};$.prototype.in_edges=$.prototype.R;
$.prototype.p=function(a,b){var c;c=a!=m?kb(Ra(this.d(a),function(a){return[a,this.succ[a]]},this),Ra(this.d(a),function(a){return[a,this.pred[a]]},this)):kb(T(this.succ),T(this.pred));return b!=m?O(c,function(a){var c=a[0][1],f=0;D(a[1][1],function(a){D(a,function(a){f+=+H(a,b,1)})});D(c,function(a){D(a,function(a){f+=+H(a,b,1)})});return[a[0][0],f]}):O(c,function(a){var b=0,c=0;D(a[1][1],function(a){b+=ib(a)});D(a[0][1],function(a){c+=ib(a)});return[a[0][0],b+c]})};$.prototype.degree_iter=$.prototype.p;
$.prototype.Q=function(a,b){var c;c=a!=m?O(this.d(a),function(a){return[a,this.pred[a]]},this):T(this.pred);return b!=m?O(c,function(a){var c=0;D(a[1],function(a){D(a,function(a){c+=+H(a,b,1)})});return[a[0][0],c]}):O(c,function(a){var b=0;D(a[1],function(a){b+=E(a)});return[a[0],b]})};$.prototype.in_degree_iter=$.prototype.Q;
$.prototype.W=function(a,b){var c;c=a!=m?O(this.d(a),function(a){return[a,this.succ[a]]},this):T(this.succ);return b!=m?O(c,function(a){var c=0;D(a[1],function(a){D(a,function(a){c+=+H(a,b,1)})});return[a[0][0],c]}):O(c,function(a){var b=0;D(a[1],function(a){b+=E(a)});return[a[0],b]})};$.prototype.out_degree_iter=$.prototype.W;$.prototype.m=da(k);$.prototype.is_multigraph=$.prototype.m;$.prototype.c=da(k);$.prototype.is_directed=$.prototype.c;$.prototype.C=function(){return qb(this)};
$.prototype.to_directed=$.prototype.C;$.prototype.O=function(a){var b=new Z;b.name(this.name());b.j(this);var c,d;a?b.b(R(this.s(),function(a){c=a[0];return T(a[1])},function(a){d=a[0];return T(a[1])},qa(function(a){if(this.J(d,c,a[0]))return[c,d,a[0],S(a[1])]},this))):b.b(R(this.s(),function(a){c=a[0];return T(a[1])},function(a){d=a[0];return T(a[1])},function(a){return[c,d,a[0],S(a[1])]}));b.graph=S(this.graph);b.node=S(this.node);return b};$.prototype.to_undirected=$.prototype.O;
$.prototype.w=function(a){a=this.d(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;C(a,function(a){c[a]={};d[a]={}});N(c,function(a){var b=c[a];D(e[a],function(e,p){if(p in c){var y=db(e);b[p]=y;d[p][a]=y}})});N(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};$.prototype.subgraph=$.prototype.w;
$.prototype.reverse=function(a){(a=!s(a)||a)?(a=new this.constructor(m,{name:"Reverse of ("+this.name()+")"}),a.j(this),a.b(Ra(this.e(m,k,k),function(a){return[a[1],a[0],a[2],S(a[3])]})),a.graph=S(this.graph),a.node=S(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};$.prototype.reverse=$.prototype.reverse;v("jsnx.nodes",function(a){return a.nodes()});v("jsnx.nodes_iter",function(a){return a.v()});v("jsnx.edges",function(a,b){return a.t(b)});v("jsnx.edges_iter",function(a,b){return a.e(b)});v("jsnx.degree",function(a,b,c){return a.o(b,c)});v("jsnx.neighbors",function(a,b){return a.K(b)});v("jsnx.number_of_nodes",function(a){return a.M()});v("jsnx.number_of_edges",function(a){return a.L()});v("jsnx.density",function(a){var b=a.M(),c=a.L();return 0===c?0:a.c()?c/(b*(b-1)):2*c/(b*(b-1))});
v("jsnx.degree_histogram",function(a){a=Ya(a.o());var b=Math.max.apply(Math,a)+1,c=Na(b);z(a,function(a){c[a]+=1});return c});v("jsnx.is_directed",function(a){return a.c()});v("jsnx.freeze",function(a){function b(){h(new X("Frozen graph can't be modified"))}a.D=b;a.j=b;a.N=b;a.X=b;a.a=b;a.b=b;a.u=b;a.B=b;a.clear=b;a.ya=k;return a});v("jsnx.is_frozen",function(a){return!!a.ya});v("jsnx.subgraph",function(a,b){return a.w(b)});
v("jsnx.create_empty_copy",function(a,b){s(b)||(b=k);var c=new a.constructor;b&&c.j(a);return c});
v("jsnx.info",function(a,b){var c="";if(b!=m)a.l(b)||h(new X("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.o(b)+"\n"),c+="Neighbors: "+a.K(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.M()+"\n"),c=c+("Number of edges: "+a.L()+"\n"),d=a.M();if(0<d)if(a.c())c+="Average in degree: "+(J.q.apply(m,Ya(a.ia()))/d).toFixed(4)+"\n",c+="Average out degree: "+(J.q.apply(m,Ya(a.la()))/d).toFixed(4);
else var e=J.q.apply(m,Ya(a.o())),c=c+("Average degree: "+(e/d).toFixed(4))}return c});v("jsnx.set_node_attributes",function(a,b,c){D(c,function(c,e){a.node[e][b]=c})});v("jsnx.get_node_attributes",function(a,b){var c={};D(a.ka,function(a,e){b in a&&(c[e]=a[b])});return c});v("jsnx.set_edge_attributes",function(a,b,c){D(c,function(b,c){c=c.split(",");a.i(c[0])[c[1]]=b})});v("jsnx.get_edge_attributes",function(a,b){var c={};D(a.t(m,k),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c});}));
