(function(){function f(a){throw a;}var h=void 0,j=!0,k=null,l=!1;function aa(a){return function(){return a}}var m,ba=this;function ca(){}
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function o(a){return a!==h}function p(a){return a!=k}function da(a){return"array"==n(a)}function q(a){var b=n(a);return"array"==b||"object"==b&&"number"==typeof a.length}function s(a){return"string"==typeof a}function ea(a){return"boolean"==typeof a}function ia(a){return"function"==n(a)}function ja(a){var b=typeof a;return"object"==b&&a!=k||"function"==b}
var ka="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),la=0;function t(a,b){var c=a.split("."),d=ba;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&o(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function u(a,b){function c(){}c.prototype=b.prototype;a.za=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ma={};var v=Array.prototype,na=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if(s(a))return!s(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=s(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},oa=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,i=s(a)?a.split(""):
a,r=0;r<d;r++)if(r in i){var G=i[r];b.call(c,G,r,a)&&(e[g++]=G)}return e},pa=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=s(a)?a.split(""):a,i=0;i<d;i++)i in g&&(e[i]=b.call(c,g[i],i,a));return e};function qa(a,b){if(a.reduce)return a.reduce(b,0);var c=0;w(a,function(d,e){c=b.call(h,c,d,e,a)});return c}
function sa(a,b){var c;a:{c=a.length;for(var d=s(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(h,d[e],e,a)){c=e;break a}c=-1}return 0>c?k:s(a)?a.charAt(c):a[c]}function ta(a){return v.concat.apply(v,arguments)}function ua(a){if(da(a))return ta(a);for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}function va(a,b,c){return 2>=arguments.length?v.slice.call(a,b):v.slice.call(a,b,c)}function wa(a){for(var b=[],c=0;c<a;c++)b[c]=0;return b}
function xa(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var g=arguments[e];if(c>=g.length)return b;d.push(g[c])}b.push(d)}};var x="StopIteration"in ba?ba.StopIteration:Error("StopIteration");function y(){}y.prototype.next=function(){f(x)};y.prototype.m=function(){return this};function A(a){if(a instanceof y)return a;if("function"==typeof a.m)return a.m(l);if(q(a)){var b=0,c=new y;c.next=function(){for(;;){b>=a.length&&f(x);if(b in a)return a[b++];b++}};return c}f(Error("Not implemented"))}function ya(a,b,c){if(q(a))try{w(a,b,c)}catch(d){d!==x&&f(d)}else{a=A(a);try{for(;;)b.call(c,a.next(),h,a)}catch(e){e!==x&&f(e)}}}
function za(a,b,c){var a=A(a),d=new y;d.next=function(){for(;;){var d=a.next();return b.call(c,d,h,a)}};return d}function Aa(a,b,c){var d=c;ya(a,function(a){d=b.call(h,d,a)});return d}function Ca(a){if(q(a))return da(a)?ta(a):ua(a);var a=A(a),b=[];ya(a,function(a){b.push(a)});return b};function D(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Da(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function Ea(a){var b=0,c;for(c in a)b++;return b}function E(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function F(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function H(a){for(var b in a)delete a[b]}function I(a,b){b in a&&delete a[b]}function K(a,b,c){return b in a?a[b]:c}function Fa(a){var b={},c;for(c in a)b[c]=a[c];return b}var Ga="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");
function L(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Ga.length;g++)c=Ga[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ha(a){return Aa(M(a),function(a,c){a[c[0]]=c[1];return a},{})}function Ia(a){return a instanceof y||ia(a.m)}function Ja(a){if(s(a)||q(a)||"length"in a)return a.length;if(Ka(a))return Ea(a);f(new TypeError)}function N(a,b,c,d){ea(c)&&(d=c,c=k);if(d)var e=b,b=function(a){e.apply(this,a)};Ia(a)?ya(a,b,c):q(a)||s(a)?w(a,b,c):ja(a)&&N(F(a),b,c)}t("jsnx.forEach",N);function R(a,b,c){if(q(a))return pa(a,b,c);if(Ia(a))return za(a,b,c);if(ja(a))return Da(a,b,c);f(new TypeError)}
function La(){var a=arguments,b=a[0];if(q(b))return xa.apply(k,a);if(Ia(b)){var b=new y,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(ja(b))return xa.apply(k,pa(a,F));f(new TypeError)}
function Qa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!o(a[c])||"object"!==n(a[c])?a[c]=S(d[c]):"object"===n(a[c])&&"object"===n(d)&&Qa(a[c],d[c]);for(var g=0;g<Ga.length;g++)c=Ga[g],Object.prototype.hasOwnProperty.call(d,c)&&(!o(a[c])||"object"!==n(a[c])?a[c]=S(d[c]):"object"===n(a[c])&&"object"===n(d)&&Qa(a[c],d[c]))}}function T(a){if(q(a))return da(a)?ta(a):ua(a);if(Ia(a))return Ca(a);if(ja(a))return F(a);f(new TypeError)}t("jsnx.toArray",T);
function Ra(a){var b=[];D(a,function(a,d){b.push([d,a])});return b}function U(a){var b=new y,c=A(F(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function M(a){"object"===n(a)&&!q(a)&&!Ia(a)&&(a=F(a));return A(a)}
function V(a){var b=new y,c=va(arguments,1);if(0===c.length)return a;try{a=A(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&f(new TypeError)},b}var e=k;b.next=function(){var d,i;try{for(;!o(d);)d=e.next()}catch(r){for(;!o(i)||!o(d);)i=a.next(),d=c[0](i);if(Ia(d))return e=V.apply(k,ta([d],va(c,1))),b.next();e=k}return d};return b}t("jsnx.sentinelIterator",function(a,b){var c=new y;c.next=function(){var c;try{c=A(a).next()}catch(e){e!=x&&f(e),c=b}return c};return c});
function Ka(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==n(a)||a.nodeType||a==a.window)return l;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return l}catch(c){return l}for(var d in a);return d===h||b.call(a,d)}
function S(a,b){var b=b||[],c=n(a);if("object"==c&&Ka(a)||"array"==c){var d=sa(b,function(b){return a===b[0]});if(d!==k)return d[1];if(a.O)return d=[a,a.O()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var e in a)c[e]=S(a[e],b);return c}return a}function Sa(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=S(c);a=new b;for(d in c)a[d]=c[d];return a};function Ta(a){a%=360;return 0>360*a?a+360:a}function Ua(a){return qa(arguments,function(a,c){return a+c})};var Va,Wa=k,Xa="add_node,add_nodes_from,add_edge,add_edges_from,remove_node,remove_nodes_from,remove_edge,remove_edges_from,clear".split(",");
t("jsnx.draw",function(a,b,c){ea(b)&&(c=b,b=k);var b=b||Wa||{},d=b.d3||window.d3,e={};Qa(e,Ya,b);Wa=b;d||f(Error("D3 requried for draw()"));!p(e.element)&&!p(Va)&&f(Error("Output element required for draw()"));Va=K(e,"element",Va);d.select(Va).select("svg.jsnx").remove();var g=d.select(Va),i=g.append("svg").classed("jsnx",j),b=i.append("g").classed("edges",j).selectAll(".edge"),r=i.append("g").classed("nodes",j).selectAll("g.node"),G=i.append("g").classed("edge_labels",j).selectAll("text"),O=d.layout.force(),
$=e.width||parseInt(g.style("width"),10),ra=e.height||parseInt(g.style("height"),10),Ba=e.layout_attr,Ma=e.nodelist||k,z,B,J,g=a.l(),P=e.weighted,C={a:r,c:b,b:G};if(e.with_labels){var Q=e.labels;z="object"===n(Q)?function(a){return K(Q,a.g,"")}:ia(Q)?Q:s(Q)?function(a){return a.data[Q]}:function(a){return a.g}}e.labels=z;if(P){var fa=e.weights;J="object"===n(fa)?function(a){return K(fa,a.g,1)}:ia(fa)?fa:s(fa)?function(a){return K(a.data,fa,1)}:aa(1)}if(e.with_edge_labels){var ga=e.edge_labels;B=P&&
!o(ga)?J:"object"===n(ga)?function(a){return K(Q,a.g,"")}:ia(ga)?ga:s(ga)?function(a){return a.data[ga]}:function(a){return a.q};e.edge_labels=B}if(P&&e.weighted_stroke){var P=Aa(a.h(j),function(a,b){b=J({data:b[2]});return a>b?a:b},0),vb=d.scale.linear().range([1,e.edge_style["stroke-width"]]).domain([1,P]);e.edge_style["stroke-width"]=function(a){return vb(J.call(this,a))}}i.select("svg.jsnx").remove();i.attr("width",$).attr("height",ra).style("opacity",1.0E-6).transition().duration(1E3).style("opacity",
1);var wb={size:j,nodes:j,links:j,start:j};N(Ba,function(a){if(!(a in wb))O[a](Ba[a])});O.nodes([]).links([]).size([$,ra]);var Na=ca,Oa=ca;if(g){i.append("defs").append("marker").attr("id","Triangle").attr("markerUnits","strokeWidth").attr("refX","7").attr("refY","5").attr("viewBox","0 0 10 10").attr("orient","auto").append("path").attr("d","M 0 0 L 10 5 L 0 10 z");e.edge_attr["marker-end"]="url(#Triangle)";e.edge_style.fill="none";var Pa=e.layout_attr.linkDistance/3,ha=e.edge_offset,Na=function(){C.c.attr("d",
function(b){if(b.source!==b.target){var c=Math.sqrt(Math.pow(b.target.x-b.source.x,2)+Math.pow(b.target.y-b.source.y,2));if(a.w(b.target.g,b.source.g)){b=-Pa/(c/2);return["M",ha,b*ha,"Q",c/2,-Pa,c-ha,-b*(c-ha)+b*c].join(" ")}return["M",ha,"0 L",c-ha,0].join(" ")}}).attr("transform",function(a){if(a.source!==a.target){var b=a.source.x,c=a.source.y;return["translate(",b,",",c,")rotate(",Ta(Math.atan2(a.target.y-c,a.target.x-b)*180/Math.PI),")"].join("")}})};e.with_edge_labels&&(Oa=function(){C.b.attr("x",
function(a){return Math.sqrt(Math.pow(a.target.x-a.source.x,2)+Math.pow(a.target.y-a.source.y,2))/2}).attr("y",function(b){return a.w(b.target.g,b.source.g)?-Pa:-2}).attr("transform",function(a){var b=a.source.x,c=a.source.y;return["translate(",b,",",c,")rotate(",Ta(Math.atan2(a.target.y-c,a.target.x-b)*180/Math.PI),")"].join("")})})}else Na=function(){C.c.attr("d",function(a){var b=[(a.source.x+a.target.x)/2,(a.source.y+a.target.y)/2];return["M",a.source.x,a.source.y,"L",b[0],b[1],"L",a.target.x,
a.target.y].join(" ")})},e.with_edge_labels&&(Oa=function(){C.b.attr("x",function(a){return(a.source.x+a.target.x)/2}).attr("y",function(a){return-2+(a.source.y+a.target.y)/2}).attr("transform",function(a){var b=[(a.source.x+a.target.x)/2,(a.source.y+a.target.y)/2],a=Ta(Math.atan2(a.target.y-a.source.y,a.target.x-a.source.x)*180/Math.PI);a>90&&a<279&&(a=a+180);return["rotate(",a,",",b[0],",",b[1],")"].join("")})});O.on("tick",function(){C.a.attr("transform",function(a){return["translate(",a.x,",",
a.y,")"].join("")});Na();Oa()});d=a.C();i=a.h();Ma&&(c=l,d=a.i(Ma),i=a.h(Ma));C.a=Za(a,d,O,r,e.node_shape,z);z=$a(a,i,O,b,G,B);C.c=z[0];C.b=z[1];ab(C.a,{attr:e.node_attr,style:e.node_style,A:e.label_style,z:e.label_attr},e.with_labels);bb(C.c,C.b,{attr:e.edge_attr,style:e.edge_style,A:e.edge_label_style,z:e.edge_label_attr},e.with_edge_labels,k,g);c?cb(a,O,e,C):a.bound?db(a):eb(a);O.start()});
function Za(a,b,c,d,e,g){var i=c.nodes();N(b,function(b){var c=a.node[b],b={g:b,data:c};i.push(b);c.__d3datum__=b});d=d.data(i,fb);b=d.enter().append("g").classed("node",j).call(c.drag);b.append(e).classed("node",j);g&&b.append("text").text(g);return d}
function $a(a,b,c,d,e,g){var i=c.links();N(b,function(b){var c=b[0],d=b[1],b=b[2]||a.P(c,d),c={q:[c,d],$:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b};i.push(c);b.__d3datum__=c});d=d.data(i,gb);d.enter().append("path");g&&(e=e.data(i,gb),e.enter().append("text").text(g));return[d,e]}
function ab(a,b,c,d){if(p(d)){var e={};N(d,function(a){e[q(a)?a[0]:a]=j});a=a.filter(function(a){return a.g in e})}var g=a.selectAll(".node");D(b.attr,function(a,b){g.attr(b,a)});D(b.style,function(a,b){g.style(b,a)});if(c){var i=a.selectAll("text");D(b.z,function(a,b){i.attr(b,a)});D(b.A,function(a,b){i.style(b,a)})}}
function bb(a,b,c,d,e,g){if(p(e)){var i={};N(e,function(a){i[[a[0],a[1]]]=j});a=a.filter(function(a){return a.q in i||g||a.$ in i});b=b.filter(function(a){return a.q in i||g||a.$ in i})}D(c.attr,function(b,c){a.attr(c,b)});D(c.style,function(b,c){a.style(c,b)});d&&(D(c.z,function(a,c){b.attr(c,a)}),D(c.A,function(a,c){b.style(c,a)}))}function fb(a){return a.g}function gb(a){return a.q}
function hb(a,b,c,d){var e=c.nodes();N(a.i(b),function(b){b=na(e,a.node[b].__d3datum__);0<=b&&v.splice.call(e,b,1)});d=d.data(e,fb);d.exit().remove();return d}function ib(a,b,c,d,e){var g=c.links();N(b,function(b){b=na(g,K(a.P(b[0],b[1],{}),"__d3datum__",k));0<=b&&v.splice.call(g,b,1)});d=d.data(g,gb);d.exit().remove();p(e)&&(e=e.data(g,gb),e.exit().remove());return[d,e]}
function cb(a,b,c,d){db(a,l);var e=a.constructor.prototype,g=c.node_shape,i={attr:c.node_attr,style:c.node_style,z:c.label_attr,A:c.label_style},r={attr:c.edge_attr,style:c.edge_style,z:c.edge_label_attr,A:c.edge_label_style},G=c.labels,O=c.edge_labels,$=c.with_labels,ra=c.with_edge_labels,Ba=a.l();a.add_node=a.t=function(a){var c=!this.k(a);e.add_node.apply(this,arguments);c&&(d.a=Za(this,[a],b,d.a,g,G));ab(d.a,i,$,[a]);b.start()};a.add_nodes_from=a.j=function(a){var c=oa(T(a),function(a){return!this.k(q(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.a=Za(this,c,b,d.a,g,G));ab(d.a,i,$,a);b.start()};a.add_edge=a.s=function(c,z){var B=!this.w(c,z),J=[];B&&(J=oa(c==z?[c]:[c,z],function(a){return!this.k(a)},this));e.add_edge.apply(a,arguments);0<J.length&&(d.a=Za(this,J,b,d.a,g,G),ab(d.a,i,$,J));B&&(B=$a(this,[[c,z]],b,d.c,d.b,O),d.c=B[0],d.b=B[1]);bb(d.c,d.b,r,ra,[[c,z]],Ba);b.start()};a.add_edges_from=a.d=function(c){var z=[],B=[],J={},P={},C=this.l();N(c,function(a){var b=a[0],
a=a[1];if(!this.w(b,a)&&!([b,a]in J)&&(C||!([a,b]in J)))if(z.push([b,a]),J[[b,a]]=j,!this.k(b)&&!(b in P)&&(B.push(b),P[b]=j),!this.k(a)&&!(a in P))B.push(a),P[a]=j},this);e.add_edges_from.apply(a,arguments);0<B.length&&(d.a=Za(this,B,b,d.a,g,G),ab(d.a,i,$,B));if(0<z.length){var Q=$a(this,z,b,d.c,d.b,O);d.c=Q[0];d.b=Q[1]}bb(d.c,d.b,r,ra,z,C);b.start()};a.remove_node=a.H=function(c){try{d.a=hb(this,[c],b,d.a);var g=ib(this,this.h(c),b,d.c,d.b);d.c=g[0];d.b=g[1];b.resume()}catch(i){}e.remove_node.apply(a,
arguments)};a.remove_nodes_from=a.I=function(c){try{d.a=hb(this,c,b,d.a);var g=ib(this,this.h(c),b,d.c,d.b);d.c=g[0];d.b=g[1];b.resume()}catch(i){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.F=function(c,g){try{var i=ib(this,[[c,g]],b,d.c,d.b);d.c=i[0];d.b=i[1];b.resume()}catch(r){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.G=function(c){try{var g=ib(this,c,b,d.c,d.b);d.c=g[0];d.b=g[1];b.resume()}catch(i){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.a=
d.a.data([],fb);d.a.exit().remove();d.c=d.c.data([],gb);d.c.exit().remove();d.b=d.b.data([],gb);d.b.exit().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=j}t("jsnx.is_bound",function(a){return a.bound});function db(a,b){if(a.bound){var c=a.constructor.prototype;w(Xa,function(b){a[b]=c[b]});delete a.bound;(!o(b)||b)&&eb(a)}}t("jsnx.unbind",db);function eb(a){N(a.C(j),function(a){I(a[1],"__d3datum__")});N(a.h(j),function(a){I(a[2],"__d3datum__")})}
var Ya={layout_attr:{charge:-120,linkDistance:40},node_shape:"circle",node_attr:{r:10},node_style:{stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{stroke:"#000","stroke-width":2},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","text-anchor":"middle","-webkit-user-select":"none"},with_labels:l,with_edge_labels:l,edge_offset:10,weights:"weight",
weighted_stroke:j};function W(a){this.name="JSNetworkXException";this.message=a}W.prototype=Error();W.prototype.constructor=W;t("jsnx.JSNetworkXException",W);function X(a){W.call(this,a);this.name="JSNetworkXError"}u(X,W);t("jsnx.JSNetworkXError",X);function jb(a){W.call(this,a);this.name="JSNetworkXPointlessConcept"}u(jb,W);t("jsnx.JSNetworkXPointlessConcept",jb);function kb(a){W.call(this,a);this.name="JSNetworkXAlgorithmError"}u(kb,W);t("jsnx.JSNetworkXAlgorithmError",kb);
function lb(a){kb.call(this,a);this.name="JSNetworkXUnfeasible"}u(lb,kb);t("jsnx.JSNetworkXUnfeasible",lb);function mb(a){lb.call(this,a);this.name="JSNetworkXNoPath"}u(mb,lb);t("jsnx.JSNetworkXNoPath",mb);function nb(a){kb.call(this,a);this.name="JSNetworkXUnbounded"}u(nb,kb);t("jsnx.JSNetworkXUnbounded",nb);function ob(a){if("function"==typeof a.v)return a.v();if(s(a))return a.split("");if(q(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return E(a)};function pb(a,b){this.f={};this.e=[];var c=arguments.length;if(1<c){c%2&&f(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.N(a)}m=pb.prototype;m.o=0;m.J=0;m.v=function(){qb(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.f[this.e[b]]);return a};m.clear=function(){this.f={};this.J=this.o=this.e.length=0};
m.remove=function(a){return Object.prototype.hasOwnProperty.call(this.f,a)?(delete this.f[a],this.o--,this.J++,this.e.length>2*this.o&&qb(this),j):l};function qb(a){if(a.o!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];Object.prototype.hasOwnProperty.call(a.f,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.o!=a.e.length){for(var e={},c=b=0;b<a.e.length;)d=a.e[b],Object.prototype.hasOwnProperty.call(e,d)||(a.e[c++]=d,e[d]=1),b++;a.e.length=c}}
m.set=function(a,b){Object.prototype.hasOwnProperty.call(this.f,a)||(this.o++,this.e.push(a),this.J++);this.f[a]=b};m.N=function(a){var b;a instanceof pb?(qb(a),b=a.e.concat(),a=a.v()):(b=F(a),a=E(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};m.O=function(){return new pb(this)};
m.m=function(a){qb(this);var b=0,c=this.e,d=this.f,e=this.J,g=this,i=new y;i.next=function(){for(;;){e!=g.J&&f(Error("The map has changed since the iterator was created"));b>=c.length&&f(x);var i=c[b++];return a?i:d[i]}};return i};function rb(a){this.f=new pb;a&&this.N(a)}function sb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ka]||(a[ka]=++la)):b.substr(0,1)+a}m=rb.prototype;m.add=function(a){this.f.set(sb(a),a)};m.N=function(a){for(var a=ob(a),b=a.length,c=0;c<b;c++)this.add(a[c])};m.remove=function(a){return this.f.remove(sb(a))};m.clear=function(){this.f.clear()};m.contains=function(a){a=sb(a);return Object.prototype.hasOwnProperty.call(this.f.f,a)};m.v=function(){return this.f.v()};m.O=function(){return new rb(this)};
m.m=function(){return this.f.m(l)};function tb(a){if(p(a))try{a.clear()}catch(b){f(Error("Input graph is not a jsnx graph type"))}else a=new ma.va;return a}
function ub(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=xb(a.adj,b,l),"graph"in a&&"object"===n(a.graph)&&(d.graph=Fa(a.graph)),"node"in a&&"object"===n(a.node)&&(d.node=Da(a.node,function(a){return Fa(a)})),d}catch(e){f(Error("Input is not a correct jsnx graph"))}if("object"===n(a))try{return xb(a,b,c)}catch(g){try{return yb(a,b)}catch(i){f(Error("Input is not known type."))}}if(q(a))try{return zb(a,b)}catch(r){f(Error("Input is not valid edge list"))}}t("jsnx.to_networkx_graph",ub);
t("jsnx.convert_to_undirected",ma.xa);t("jsnx.convert_to_undirected",ma.wa);t("jsnx.to_dict_of_lists",ma.Aa);function yb(a,b){var c=tb(b);c.j(a);var d=[];D(a,function(a,b){w(a,function(a){d.push([b,a])})});c.d(d);return c}
function xb(a,b,c){var d=tb(b),e,g;d.j(a);c?d.l()?(e=[],D(a,function(a,b){q(a)&&f(Error());D(a,function(a,c){D(a,function(a){e.push([b,c,a])})})}),d.d(e)):(g=new rb,D(a,function(a,b){q(a)&&f(Error());D(a,function(a,c){g.contains([b,c].toString())||(e=[],D(a,function(a){e.push([b,c,a])}),d.d(e),g.add([c,b].toString()))})})):(e=[],D(a,function(a,b){q(a)&&f(Error());D(a,function(a,c){e.push([b,c,a])})}),d.d(e));return d}function zb(a,b){var c=tb(b);c.d(a);return c};function Y(a,b){if(!(this instanceof Y))return new Y(a,b);this.graph={};this.node={};this.adj={};p(a)&&ub(a,this);L(this.graph,b||{});this.edge=this.adj}t("jsnx.classes.Graph",Y);t("jsnx.Graph",Y);Y.__name__="Graph";Y.prototype.ka=k;Y.prototype.graph=Y.prototype.ka;Y.prototype.g=k;Y.prototype.node=Y.prototype.g;Y.prototype.ha=k;Y.prototype.adj=Y.prototype.ha;Y.prototype.q=k;Y.prototype.edge=Y.prototype.q;
Y.prototype.name=function(a){if(o(a))this.graph.name=a.toString();else return this.graph.name||""};Y.prototype.name=Y.prototype.name;Y.prototype.toString=function(){return this.name()};Y.prototype.toString=Y.prototype.toString;Y.prototype.m=function(){return M(this.adj)};Y.prototype.__iterator__=Y.prototype.m;Y.prototype.W=function(a){a in this.adj||f({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};Y.prototype.get_node=Y.prototype.W;
Y.prototype.t=function(a,b){p(b)||(b={});"object"!==n(b)&&f(new X("The attr_dict argument must be an object."));a in this.adj?L(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};Y.prototype.add_node=Y.prototype.t;Y.prototype.j=function(a,b){var c,d,e,g,i,b=b||{};N(a,function(a){c=!(a in this.adj);da(a)?(d=a[0],e=a[1],d in this.adj?(i=this.node[d],L(i,b,e)):(this.adj[d]={},g=Fa(b),L(g,e),this.node[d]=g)):c?(this.adj[a]={},this.node[a]=Fa(b)):L(this.node[a],b)},this)};
Y.prototype.add_nodes_from=Y.prototype.j;Y.prototype.H=function(a){var b=this.adj,c;a in this.node||f(new X("The node "+a+" is not in the graph"));c=F(b[a]);I(this.node,a);w(c,function(c){I(b[c],a)});I(b,a)};Y.prototype.remove_node=Y.prototype.H;Y.prototype.I=function(a){var b=this.adj;N(a,function(a){try{I(this.node,a),D(b[a],function(d,g){I(b[g],a)}),I(b,a)}catch(d){}},this)};Y.prototype.remove_nodes_from=Y.prototype.I;Y.prototype.C=function(a){return a?U(this.node):M(F(this.adj))};
Y.prototype.nodes_iter=Y.prototype.C;Y.prototype.nodes=function(a){return Ca(this.C(a))};Y.prototype.nodes=Y.prototype.nodes;Y.prototype.D=function(){return Ea(this.adj)};Y.prototype.number_of_nodes=Y.prototype.D;Y.prototype.qa=function(){return Ea(this.adj)};Y.prototype.order=Y.prototype.qa;Y.prototype.k=function(a){return!da(a)&&a in this.adj};Y.prototype.has_node=Y.prototype.k;
Y.prototype.s=function(a,b,c){c=c||{};"object"!==n(c)&&f(new X("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=K(this.adj[a],b,{});L(d,c);this.adj[a][b]=d;this.adj[b][a]=d};Y.prototype.add_edge=Y.prototype.s;
Y.prototype.d=function(a,b){b=b||{};"object"!==n(b)&&f(new X("The attr_dict argument must be an object."));N(a,function(a){var d=Ja(a),e,g,i;3===d?(e=a[0],g=a[1],i=a[2]):2===d?(e=a[0],g=a[1],i={}):f(new X("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});g in this.adj||(this.adj[g]={},this.node[g]={});a=K(this.adj[e],g,{});L(a,b,i);this.adj[e][g]=a;this.adj[g][e]=a},this)};Y.prototype.add_edges_from=Y.prototype.d;
Y.prototype.ga=function(a,b,c){c=c||{};s(b)||(c=b,b="weight");this.d(R(a,function(a){var c={};c[b]=a[2];return[a[0],a[1],c]}),c)};Y.prototype.add_weighted_edges_from=Y.prototype.ga;Y.prototype.F=function(a,b){try{I(this.adj[a],b),a!=b&&I(this.adj[b],a)}catch(c){c instanceof TypeError&&f(new X("The edge "+a+"-"+b+" is not in the graph")),f(c)}};Y.prototype.remove_edge=Y.prototype.F;
Y.prototype.G=function(a){N(a,function(a){var c=a[0],a=a[1];c in this.adj&&a in this.adj[c]&&(I(this.adj[c],a),c!=a&&I(this.adj[a],c))},this)};Y.prototype.remove_edges_from=Y.prototype.G;Y.prototype.w=function(a,b){return a in this.adj&&b in this.adj[a]};Y.prototype.has_edge=Y.prototype.w;Y.prototype.B=function(a){a in this.adj||f(new X("The node "+a+" is not in the graph."));return T(this.adj[a])};Y.prototype.neighbors=Y.prototype.B;
Y.prototype.S=function(a){a in this.adj||f(new X("The node "+a+" is not in the graph."));return M(this.adj[a])};Y.prototype.neighbors_iter=Y.prototype.S;Y.prototype.K=function(a,b){return T(this.h(a,b))};Y.prototype.edges=Y.prototype.K;
Y.prototype.h=function(a,b){ea(a)&&(b=a,a=k);var c={},d,e;d=p(a)?R(this.i(a),function(a){return[a,this.adj[a]]},this):U(this.adj);return b?V(d,function(a){e=a[0];var b=new y,d=U(a[1]);b.next=function(){try{return d.next()}catch(a){a===x&&(c[e]=1);f(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):V(d,function(a){e=a[0];var b=new y,d=M(a[1]);b.next=function(){try{return d.next()}catch(a){a===x&&(c[e]=1);f(a)}};return b},function(a){if(!(a in c))return[e,a]})};
Y.prototype.edges_iter=Y.prototype.h;Y.prototype.P=function(a,b,c){o(c)||(c=k);return a in this.adj?K(this.adj[a],b,c):c};Y.prototype.get_edge_data=Y.prototype.P;Y.prototype.ia=function(){return T(R(this.n(),function(a){return F(a[1])}))};Y.prototype.adjacency_list=Y.prototype.ia;Y.prototype.n=function(){return U(this.adj)};Y.prototype.adjacency_iter=Y.prototype.n;Y.prototype.p=function(a,b){return this.k(a)?this.u(a,b).next()[1]:Ha(Ca(this.u(a,b)))};Y.prototype.degree=Y.prototype.p;
Y.prototype.u=function(a,b){var c;c=p(a)?R(this.i(a),function(a){return[a,this.adj[a]]},this):U(this.adj);return b?R(c,function(a){var c=a[0],a=a[1],g=0,i;for(i in a)g+=+K(a[i],b,1);g+=+(c in a&&K(a[c],b,1));return[c,g]}):R(c,function(a){return[a[0],Ea(a[1])+ +(a[0]in a[1])]})};Y.prototype.degree_iter=Y.prototype.u;Y.prototype.clear=function(){this.name("");H(this.adj);H(this.node);H(this.graph)};Y.prototype.clear=Y.prototype.clear;Y.prototype.copy=function(){return Sa(this)};Y.prototype.copy=Y.prototype.copy;
Y.prototype.R=aa(l);Y.prototype.is_multigraph=Y.prototype.R;Y.prototype.l=aa(l);Y.prototype.is_directed=Y.prototype.l;Y.prototype.U=function(){var a=new Z;a.name(this.name());a.j(this);a.d(function(){var a;return V(this.n(),function(c){a=c[0];return U(c[1])},function(c){return[a,c[0],S(c[1])]})}.call(this));a.graph=S(this.graph);a.node=S(this.node);return a};Y.prototype.to_directed=Y.prototype.U;
Y.prototype.V=function(){var a=new Y;a.name(this.name());a.j(this);a.d(function(){var a;return V(this.n(),function(c){a=c[0];return U(c[1])},function(c){return[a,c[0],S(c[1])]})}.call(this));a.graph=S(this.graph);a.node=S(this.node);return a};Y.prototype.to_undirected=Y.prototype.V;
Y.prototype.M=function(a){var a=this.i(a),b=new this.constructor,c=b.adj,d=this.adj;N(a,function(a){var b={};c[a]=b;D(d[a],function(d,r){r in c&&(b[r]=d,c[r][a]=d)})});N(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.M;Y.prototype.oa=function(){return pa(oa(Ra(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};Y.prototype.nodes_with_selfloops=Y.prototype.oa;
Y.prototype.aa=function(a){return a?pa(oa(Ra(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):pa(oa(Ra(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};Y.prototype.selfloop_edges=Y.prototype.aa;Y.prototype.pa=function(){return this.aa().length};Y.prototype.number_of_selfloops=Y.prototype.pa;Y.prototype.size=function(a){var b=Ua.apply(k,E(this.p(a)))/2;return p(a)?b:Math.floor(b)};Y.prototype.size=Y.prototype.size;
Y.prototype.L=function(a,b){return!p(a)?Math.floor(this.size()):b in this.adj[a]?1:0};Y.prototype.number_of_edges=Y.prototype.L;Y.prototype.fa=function(a,b){var c=T(a),d=c[0];this.d(R(va(c,1),function(a){return[d,a]}),b)};Y.prototype.add_star=Y.prototype.fa;Y.prototype.ea=function(a,b){var c=T(a);this.d(xa(va(c,0,c.length-1),va(c,1)),b)};Y.prototype.add_path=Y.prototype.ea;Y.prototype.da=function(a,b){var c=T(a);this.d(xa(c,ta(va(c,1),[c[0]])),b)};Y.prototype.add_cycle=Y.prototype.da;
Y.prototype.i=function(a){return p(a)?this.k(a)?M([a.toString()]):function(a,c){var d=new y,e=V(a,function(a){if(a in c)return a.toString()});d.next=function(){try{return e.next()}catch(a){a instanceof TypeError&&f(new X("nbunch is not a node or a sequence of nodes")),f(a)}};return d}(a,this.adj):M(this.adj)};Y.prototype.nbunch_iter=Y.prototype.i;t("jsnx.nodes",function(a){return a.nodes()});t("jsnx.nodes_iter",function(a){return a.C()});t("jsnx.edges",function(a,b){return a.K(b)});t("jsnx.edges_iter",function(a,b){return a.h(b)});t("jsnx.degree",function(a,b,c){return a.p(b,c)});t("jsnx.neighbors",function(a,b){return a.B(b)});t("jsnx.number_of_nodes",function(a){return a.D()});t("jsnx.number_of_edges",function(a){return a.L()});t("jsnx.density",function(a){var b=a.D(),c=a.L();return 0===c?0:a.l()?c/(b*(b-1)):2*c/(b*(b-1))});
t("jsnx.degree_histogram",function(a){var a=E(a.p()),b=Math.max.apply(Math,a)+1,c=wa(b);w(a,function(a){c[a]+=1});return c});t("jsnx.is_directed",function(a){return a.l()});t("jsnx.freeze",function(a){function b(){f(new X("Frozen graph can't be modified"))}a.t=b;a.j=b;a.H=b;a.I=b;a.s=b;a.d=b;a.F=b;a.G=b;a.clear=b;a.ja=j;return a});t("jsnx.is_frozen",function(a){return!!a.ja});t("jsnx.subgraph",function(a,b){return a.M(b)});
t("jsnx.create_empty_copy",function(a,b){o(b)||(b=j);var c=new a.constructor;b&&c.j(a);return c});
t("jsnx.info",function(a,b){var c="";if(p(b))a.k(b)||f(new X("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.p(b)+"\n"),c+="Neighbors: "+a.B(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.D()+"\n"),c=c+("Number of edges: "+a.L()+"\n"),d=a.D();if(0<d)if(a.l())c+="Average in degree: "+(Ua.apply(k,E(a.X()))/d).toFixed(4)+"\n",c+="Average out degree: "+(Ua.apply(k,E(a.Z()))/d).toFixed(4);
else var e=Ua.apply(k,E(a.p())),c=c+("Average degree: "+(e/d).toFixed())}return c});t("jsnx.set_node_attributes",function(a,b,c){D(c,function(c,e){a.g[e][b]=c})});function Ab(a,b){var c={};D(a.g,function(a,e){b in a&&(c[e]=a[b])});return c}t("jsnx.get_node_attributes",Ab);t("jsnx.set_edge_attributes",function(a,b,c){D(c,function(b,c){c=c.split(",");a.W(c[0])[c[1]]=b})});Ab=function(a,b){var c={};D(a.K(j),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};t("jsnx.get_edge_attributes",{}.ya);function Z(a,b){if(!(this instanceof Z))return new Z(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;p(a)&&ub(a,this);L(this.graph,b||{});this.edge=this.adj}t("jsnx.classes.DiGraph",Z);t("jsnx.DiGraph",Z);u(Z,Y);Z.__name__="DiGraph";Z.prototype.t=function(a,b){p(b)||(b={});"object"!==n(b)&&f(new X("The attr_dict argument must be an object."));a in this.succ?L(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};Z.prototype.add_node=Z.prototype.t;
Z.prototype.j=function(a,b){var c,d,e,g,i,b=b||{};N(M(a),function(a){c=!(a in this.succ);da(a)?(d=a[0],e=a[1],d in this.succ?(i=this.node[d],L(i,b,e)):(this.succ[d]={},this.pred[d]={},g=Fa(b),L(g,e),this.node[d]=g)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=Fa(b)):L(this.node[a],b)},this)};Z.prototype.add_nodes_from=Z.prototype.j;
Z.prototype.H=function(a){a in this.node||f(new X("The node "+a+" is not in the graph"));var b=this.succ[a];I(this.node,a);D(b,function(b,d){I(this.pred[d],a)},this);I(this.succ,a);D(this.pred[a],function(b,d){I(this.succ[d],a)},this);I(this.pred,a)};Z.prototype.remove_node=Z.prototype.H;
Z.prototype.I=function(a){var b;N(a,function(a){a in this.succ&&(b=this.succ[a],I(this.node,a),D(b,function(b,e){I(this.pred[e],a)},this),I(this.succ,a),D(this.pred[a],function(b,e){I(this.succ[e],a)},this),I(this.pred,a))},this)};Z.prototype.remove_nodes_from=Z.prototype.I;
Z.prototype.s=function(a,b,c){c=c||{};"object"!==n(c)&&f(new X("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=K(this.adj[a],b,{});L(d,c);this.succ[a][b]=d;this.pred[b][a]=d};Z.prototype.add_edge=Z.prototype.s;
Z.prototype.d=function(a,b){b=b||{};"object"!==n(b)&&f(new X("The attr_dict argument must be an object."));N(a,function(a){var d=Ja(a),e,g,i;3===d?(e=a[0],g=a[1],i=a[2]):2===d?(e=a[0],g=a[1],i={}):f(new X("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});g in this.succ||(this.succ[g]={},this.pred[g]={},this.node[g]={});a=K(this.adj[e],g,{});L(a,b,i);this.succ[e][g]=a;this.pred[g][e]=a},this)};
Z.prototype.add_edges_from=Z.prototype.d;Z.prototype.F=function(a,b){try{I(this.succ[a],b),I(this.pred[b],a)}catch(c){c instanceof TypeError&&f(new X("The edge "+a+"-"+b+" is not in the graph")),f(c)}};Z.prototype.remove_edge=Z.prototype.F;Z.prototype.G=function(a){N(a,function(a){var c=a[0],a=a[1];c in this.succ&&a in this.succ[c]&&(I(this.succ[c],a),I(this.pred[a],c))},this)};Z.prototype.remove_edges_from=Z.prototype.G;Z.prototype.ma=function(a,b){return a in this.succ&&b in this.succ[a]};
Z.prototype.has_successor=Z.prototype.ma;Z.prototype.la=function(a,b){return a in this.pred&&b in this.pred[a]};Z.prototype.has_predecessor=Z.prototype.la;Z.prototype.ca=function(a){a in this.succ||f(new X("The node "+a+" is not in the digraph."));return M(this.succ[a])};Z.prototype.successors_iter=Z.prototype.ca;Z.prototype.ua=function(a){a in this.pred||f(new X("The node "+a+" is not in the digraph."));return M(this.pred[a])};Z.prototype.predecessors_iter=Z.prototype.ua;
Z.prototype.ba=function(a){a in this.succ||f(new X("The node "+a+" is not in the digraph."));return T(this.succ[a])};Z.prototype.successors=Z.prototype.ba;Z.prototype.ta=function(a){a in this.succ||f(new X("The node "+a+" is not in the digraph."));return T(this.pred[a])};Z.prototype.predecessors=Z.prototype.ta;Z.prototype.B=Z.prototype.ba;Z.prototype.neighbors=Z.prototype.B;Z.prototype.S=Z.prototype.ca;Z.prototype.neighbors_iter=Z.prototype.S;
Z.prototype.h=function(a,b){ea(a)&&(b=a,a=k);var c,d,e;c=p?R(this.i(a),function(a){return[a,this.adj[a]]},this):Ra(this.adj);return b?V(c,function(a){d=a[0];e=a[1];return U(e)},function(a){return[d,a[0],a[1]]}):V(c,function(a){d=a[0];e=a[1];return U(e)},function(a){return[d,a[0]]})};Z.prototype.edges_iter=Z.prototype.h;Z.prototype.sa=Z.prototype.h;Z.prototype.out_edges_iter=Z.prototype.sa;Z.prototype.ra=Y.prototype.K;Z.prototype.out_edges=Z.prototype.ra;
Z.prototype.Y=function(a,b){ea(a)&&(b=a,a=k);var c,d,e;c=p?R(this.i(a),function(a){return[a,this.pred[a]]},this):Ra(this.pred);return b?V(c,function(a){d=a[0];e=a[1];return U(e)},function(a){return[a[0],d,a[1]]}):V(c,function(a){d=a[0];e=a[1];return U(e)},function(a){return[a[0],d]})};Z.prototype.in_edges_iter=Z.prototype.Y;Z.prototype.na=function(a,b){return T(this.Y(a,b))};Z.prototype.in_edges=Z.prototype.na;
Z.prototype.u=function(a,b){var c;c=p(a)?La(R(this.i(a),function(a){return[a,this.succ[a]]},this),R(this.i(a),function(a){return[a,this.pred[a]]},this)):La(U(this.succ),U(this.pred));return b?R(c,function(a){var c=a[0][1],g=a[1][1],i=0,r;for(r in c)i+=+K(c[r],b,1);for(r in g)i+=+K(g[r],b,1);return[a[0][0],i]}):R(c,function(a){return[a[0][0],Ja(a[0][1])+Ja(a[1][1])]})};Z.prototype.degree_iter=Z.prototype.u;
Z.prototype.Q=function(a,b){var c;c=p(a)?R(this.i(a),function(a){return[a,this.pred[a]]},this):U(this.pred);return b?R(c,function(a){var c=0,g=a[1],i;for(i in g)c+=+K(g[i],b,1);return[a[0],c]}):R(c,function(a){return[a[0],Ea(a[1])]})};Z.prototype.in_degree_iter=Z.prototype.Q;Z.prototype.T=function(a,b){var c;c=p(a)?R(this.i(a),function(a){return[a,this.succ[a]]},this):U(this.succ);return b?R(c,function(a){var c=0,g=a[1],i;for(i in g)c+=+K(g[i],b,1);return[a[0],c]}):R(c,function(a){return[a[0],Ea(a[1])]})};
Z.prototype.out_degree_iter=Z.prototype.T;Z.prototype.X=function(a,b){return this.k(a)?this.Q(a,b).next()[1]:Ha(this.Q(a,b))};Z.prototype.in_degree=Z.prototype.X;Z.prototype.Z=function(a,b){return this.k(a)?this.T(a,b).next()[1]:Ha(this.T(a,b))};Z.prototype.out_degree=Z.prototype.Z;Z.prototype.clear=function(){H(this.succ);H(this.pred);H(this.node);H(this.graph)};Z.prototype.clear=Z.prototype.clear;Z.prototype.R=aa(l);Z.prototype.is_multigraph=Z.prototype.R;Z.prototype.l=aa(j);
Z.prototype.is_directed=Z.prototype.l;Z.prototype.U=function(){return Sa(this)};Z.prototype.to_directed=Z.prototype.U;Z.prototype.V=function(a){var b=new Y;b.name(this.name());b.j(this);var c=this.pred,d;a?b.d(V(this.n(),function(a){d=a[0];return U(a[1])},function(a){if(a[0]in c[d])return[d,a[0],S(a[1])]})):b.d(V(this.n(),function(a){d=a[0];return U(a[1])},function(a){return[d,a[0],S(a[1])]}));b.graph=S(this.graph);b.node=S(this.node);return b};Z.prototype.to_undirected=Z.prototype.V;
Z.prototype.reverse=function(a){(a=!o(a)||a)?(a=new this.constructor(k,{name:"Reverse of ("+this.name()+")"}),a.j(this),a.d(R(this.h(j),function(a){return[a[1],a[0],S(a[2])]})),a.graph=S(this.graph),a.node=S(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Z.prototype.reverse=Z.prototype.reverse;
Z.prototype.M=function(a){var a=this.i(a),b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;N(a,function(a){c[a]={};d[a]={}});N(c,function(a){var b=c[a];D(e[a],function(e,G){G in c&&(b[G]=e,d[G][a]=e)})});N(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.M;}());
